import { expect, test } from "playwright/test"
import AxeBuilder from "@axe-core/playwright"
import { build } from "esbuild"

test("presidency and all 27 UF charts expose every candidate in their default stimulated scenario", async ({ page }) => {
  test.setTimeout(240_000)
  const ufs = ["ac", "al", "ap", "am", "ba", "ce", "df", "es", "go", "ma", "mt", "ms", "mg", "pa", "pb", "pr", "pe", "pi", "rj", "rn", "rs", "ro", "rr", "sc", "sp", "se", "to"]
  for (const path of ["/", ...ufs.map(uf => `/uf/${uf}`)]) {
    await page.goto(`${path}#pesquisas`, { waitUntil: "domcontentloaded" })
    const section = page.locator("[data-pf-polls]")
    const scenario = section.getByRole("combobox", { name: "Cenário", exact: true })
    await expect(scenario, path).toBeVisible()
    const selection = JSON.parse(await scenario.inputValue()) as [number, string, string, number, string, string, string[]]
    const options = await scenario.locator("option").evaluateAll(nodes => nodes.map(node => JSON.parse((node as HTMLOptionElement).value) as [number, string, string, number, string]))
    if (options.some(option => /^estimulad[ao]$/.test(option[4].split("|")[4]))) expect(selection[4].split("|")[4], path).toMatch(/^estimulad[ao]$/)
    await expect(section.getByRole("checkbox"), path).toHaveCount(selection[6].length)
    for (const checkbox of await section.getByRole("checkbox").all()) await expect(checkbox, path).toBeChecked()
  }
})

test("SP initially shows all seven stimulated candidates, including zero, and keeps spontaneous voting separate", async ({ page }, info) => {
  await page.goto("/uf/sp#pesquisas", { waitUntil: "domcontentloaded" })
  const section = page.locator("[data-pf-polls]")
  const scenario = section.getByRole("combobox", { name: "Cenário", exact: true })
  await expect(scenario.locator("option:checked")).toHaveText("1º turno estimulado")
  await expect(section.getByRole("checkbox")).toHaveCount(7)
  for (const [name, value] of [["Tarcísio de Freitas", 42], ["Fernando Haddad", 27], ["Policial Edjane", 1], ["Vera Lúcia", 1], ["Izadora Dias", 1], ["Carlos Machado", 1], ["Vivian Mendes", 0]] as const) {
    await expect(section.getByRole("checkbox", { name: `${name} ${value}%`, exact: true })).toBeChecked()
  }
  await expect(section.locator("[data-pf-poll-endpoint]")).toHaveCount(7)
  await section.screenshot({ path: info.outputPath("sp-stimulated-desktop.png") })
  await scenario.selectOption({ label: "1º turno espontâneo" })
  await expect(section.getByRole("checkbox")).toHaveCount(2)
  await expect(section.getByRole("checkbox", { name: "Tarcísio 22%", exact: true })).toBeChecked()
  await scenario.selectOption({ label: "1º turno estimulado" })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(section.getByRole("checkbox")).toHaveCount(7)
  for (const row of await section.locator("[data-pf-poll-candidate]").all()) await expect(row).toBeVisible()
  await expect.poll(() => section.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await section.screenshot({ path: info.outputPath("sp-stimulated-mobile.png") })
  const accessibility = await new AxeBuilder({ page }).include("[data-pf-polls]").withTags(["wcag2a", "wcag2aa"]).analyze()
  expect(accessibility.violations).toEqual([])
})

// Keep the fixed site header from obscuring element-only evidence captures.
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    document.addEventListener("DOMContentLoaded", () => {
      const style = document.createElement("style")
      style.textContent = "header.fixed { visibility: hidden; }"
      document.head.appendChild(style)
    })
  })
})

test("public catalog: separate incompatible series, preserve all responses and handle empty turn", async ({ page }, info) => {
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto("/#pesquisas", { waitUntil: "domcontentloaded" })
  const section = page.locator("[data-pf-polls]")
  await expect(section).toBeVisible()
  await expect(section.getByText('Pesquisa individual', { exact: true })).toHaveCount(0)
  await expect(section.getByRole('tablist')).toHaveCount(0)
  await expect(section.getByText('Evolução', { exact: true })).toBeVisible()
  await expect(section.locator("[data-pf-poll-line]")).toHaveCount(0)
  await expect(section.locator("[data-pf-poll-dot]")).toHaveCount(13)
  await expect(section.locator("[data-pf-poll-guide]")).toHaveCount(13)
  await expect(section).toContainText("Uma semana disponível neste cenário")
  await expect(section.getByRole("checkbox", { name: "Lula 38,4%", exact: true })).toBeChecked()
  await expect(section.getByText(/Mais candidatos/)).toHaveCount(0)
  await expect(section.getByRole("checkbox", { name: "Hertz Dias 0,1%", exact: true })).toBeVisible()
  const toggles = section.getByRole("checkbox")
  await expect(toggles).toHaveCount(13)
  for (const toggle of await toggles.all()) await expect(toggle).toBeChecked()
  const endpoints = section.locator('[data-pf-poll-endpoint]')
  await expect(endpoints).toHaveCount(13)
  for (const endpoint of await endpoints.all()) {
    await expect(endpoint).toBeVisible()
    await expect(endpoint.locator('[class*="avatar"]').first()).toBeVisible()
  }
  const endpointBounds = await endpoints.evaluateAll(nodes => nodes.map(node => {
    const avatar = node.querySelector('[class*="avatar"]')!.getBoundingClientRect()
    const bounds = node.getBoundingClientRect()
    const plot = node.parentElement!.parentElement!.getBoundingClientRect()
    return { top: bounds.top, bottom: bounds.bottom, left: bounds.left, right: bounds.right, valueY: Number(node.getAttribute('data-value-y')), avatarY: avatar.top + avatar.height / 2 - plot.top }
  }))
  for (let index = 0; index < endpointBounds.length; index++) {
    const current = endpointBounds[index]
    expect(Math.abs(current.avatarY - current.valueY)).toBeLessThan(1)
    for (const other of endpointBounds.slice(0, index)) expect(current.left >= other.right || current.right <= other.left || current.top >= other.bottom || current.bottom <= other.top).toBe(true)
  }
  const centerOffset = await section.locator('[data-pf-poll-dot]').first().evaluate(node => {
    const dot = node.getBoundingClientRect()
    const chart = node.closest('svg')!.parentElement!.parentElement!.getBoundingClientRect()
    return Math.abs(dot.x + dot.width / 2 - (chart.x + chart.width / 2))
  })
  expect(centerOffset).toBeLessThan(1)
  await expect(section.locator("[data-pf-poll-dot]")).toHaveCount(13)
  await expect(section.locator("[data-pf-poll-guide]")).toHaveCount(13)
  const guide = section.locator("[data-pf-poll-guide]").first()
  await expect(guide).toHaveAttribute("x1", "0")
  expect(await guide.getAttribute("x2")).toBe(await section.locator("[data-pf-poll-dot]").first().getAttribute("cx"))
  await expect(section.locator("[data-pf-poll-line]")).toHaveCount(0)
  await section.locator('fieldset').scrollIntoViewIfNeeded()
  await expect.poll(() => section.locator('img').evaluateAll(images => images.every(image => (image as HTMLImageElement).complete)), { timeout: 15_000 }).toBe(true)
  await section.screenshot({ path: info.outputPath("real-all-candidates.png") })
  await expect.poll(() => section.evaluate(node => getComputedStyle(node.querySelector("h2")!).fontFamily)).toContain("Anton")
  await section.screenshot({ path: info.outputPath("real-desktop.png") })
  const accessibility = await new AxeBuilder({ page }).include("[data-pf-polls]").withTags(["wcag2a", "wcag2aa"]).analyze()
  expect(accessibility.violations).toEqual([])

  const point = section.getByRole("button", { name: /institutos: Meio/ })
  await point.focus()
  await expect(section.getByRole("region", { name: "Pesquisa selecionada" })).toContainText("38,4%")
  await section.getByRole("button", { name: "Fechar detalhes do ponto" }).click()
  await expect(section.getByRole("region", { name: "Pesquisa selecionada" })).toHaveCount(0)
  await point.hover()
  await expect(section.getByRole("region", { name: "Pesquisa selecionada" })).toHaveCount(0)
  await point.click()
  await expect(section.getByRole("region", { name: "Pesquisa selecionada" })).toBeVisible()
  await section.getByRole("button", { name: "Fechar detalhes do ponto" }).press("Escape")
  await expect(section.getByRole("region", { name: "Pesquisa selecionada" })).toHaveCount(0)
  await point.press("Enter")
  await expect(section.getByRole('region', { name: 'Pesquisa selecionada' }).getByRole('link', { name: /Fonte: Meio/ })).toHaveAttribute('href', /cnn/)
  await section.getByRole('button', { name: 'Fechar detalhes do ponto' }).click()
  await expect(section.getByRole("list", { name: "Demais respostas da pesquisa" }).locator("li")).toHaveCount(2)
  await expect(section).toContainText("38,4%")
  await section.getByText("Ficha técnica e fonte", { exact: true }).click()
  await expect(section).toContainText("BR-07935/26")
  await expect(section.getByRole("link", { name: "Fonte da pesquisa" })).toHaveAttribute("href", /cnn/)
  await expect(section.locator('[data-pf-poll-source]')).toContainText('Meio/Ideia')
  await expect(section.locator('[data-pf-poll-source]')).toContainText('09/09/2026')
  await section.screenshot({ path: info.outputPath("real-details.png") })

  await section.getByRole("combobox", { name: "Instituto", exact: true }).selectOption("Datafolha")
  expect(await section.getByRole('checkbox').count() + await section.getByRole('list', { name: 'Demais respostas da pesquisa' }).locator('li').count()).toBe(14)
  await expect(section.locator('[data-pf-poll-source]')).toContainText('Datafolha')
  await expect(section.locator('[data-pf-poll-source]')).toContainText('19/08/2026')
  await expect(section.getByRole('link', { name: 'Fonte da pesquisa' })).toHaveAttribute('href', /folha/)
  await expect(section.locator("[data-pf-poll-line]")).toHaveCount(0)
  await expect(section).toContainText("39%")
  await section.getByRole("combobox", { name: "Turno", exact: true }).selectOption("2")
  await expect(section).toContainText("Sem pesquisa qualificada disponível")
  await expect(section.locator("[data-pf-poll-dot]")).toHaveCount(0)
  expect(errors).toEqual([])
})

test("mobile and tablet: no overflow, real photos, touch details and reduced motion", async ({ page }, info) => {
  await page.goto("/#pesquisas", { waitUntil: "domcontentloaded" })
  const section = page.locator("[data-pf-polls]")
  await expect(section).toBeVisible()
  for (const width of [320, 390, 768]) {
    await page.setViewportSize({ width, height: 844 })
    await page.emulateMedia({ reducedMotion: "reduce", colorScheme: "dark" })
    if (width <= 640) {
      await expect(section.getByRole("combobox", { name: "Instituto", exact: true })).toBeHidden()
      await section.getByRole("button", { name: "Filtros de pesquisa", exact: true }).click()
      await expect(section.getByRole("combobox", { name: "Instituto", exact: true })).toBeVisible()
      await section.getByRole("button", { name: "Filtros de pesquisa", exact: true }).click()
    }
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect.poll(() => section.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    if (width <= 640) {
      await expect(section.locator('[data-pf-poll-chart]')).toBeHidden()
      await expect(section.locator('[data-pf-poll-source]')).toContainText('07/09/2026')
      await expect(section.getByText('Pesquisa individual', { exact: true })).toHaveCount(0)
      await expect(section.getByRole('link', { name: 'Fonte da pesquisa' })).toBeVisible()
      await expect(section.getByRole('button', { name: 'Anterior', exact: true })).toHaveCount(0)
      await expect(section.locator('[data-pf-poll-mobile-bar]')).toHaveCount(13)
      for (const checkbox of await section.getByRole('checkbox').all()) await expect(checkbox).toBeChecked()
      for (const row of await section.locator('[data-pf-poll-candidate]').all()) await expect(row).toBeVisible()
      const firstBar = section.locator('[data-pf-poll-mobile-bar]').first()
      await expect(firstBar).toBeVisible()
      await expect.poll(() => firstBar.evaluate(node => (node as HTMLElement).style.width)).toBe('76.8%')
    } else {
      await section.getByRole("button", { name: /institutos: Meio/ }).click()
      await expect(section.getByRole("region", { name: "Pesquisa selecionada" })).toBeVisible()
      await section.getByRole("button", { name: "Fechar detalhes do ponto" }).click()
      await expect(section.getByRole("region", { name: "Pesquisa selecionada" })).toHaveCount(0)
    }
    await section.screenshot({ path: info.outputPath(`real-${width}.png`) })
    if (width === 390) {
      const accessibility = await new AxeBuilder({ page }).include("[data-pf-polls]").withTags(["wcag2a", "wcag2aa"]).analyze()
      expect(accessibility.violations).toEqual([])
      await expect(section.getByRole("list", { name: "Demais respostas da pesquisa" }).locator("li")).toHaveCount(2)
      await section.getByText('Ficha técnica e fonte', { exact: true }).click()
      await expect(section).toContainText('BR-07935/26')
      await expect.poll(() => section.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
      await section.screenshot({ path: info.outputPath("real-details-mobile.png") })
    }
  }
  // The site already supplies candidate photos; do not generate substitutes.
  await expect(section.locator("img").first()).toHaveAttribute("src", /.+/)
})

test("real UF surface uses the shared experience without presidential results", async ({ page }, info) => {
  await page.goto("/uf/am#pesquisas", { waitUntil: "domcontentloaded" })
  const section = page.locator("[data-pf-polls]")
  await expect(section).toBeVisible()
  await expect(section).not.toContainText("Lula")
  await expect(section).toContainText("Omar")
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => section.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await section.screenshot({ path: info.outputPath("real-am-mobile.png") })
})

test("test-only series: real line component, dates, candidate selection and drilldown", async ({ page }, info) => {
  await page.goto("/", { waitUntil: "domcontentloaded" })
  await expect(page.locator("[data-pf-polls]")).toBeVisible()
  const shell = await page.evaluate(() => ({
    styles: [...document.querySelectorAll<HTMLLinkElement>('link[rel="stylesheet"]')].map(link => link.href),
    htmlClass: document.documentElement.className,
    bodyClass: document.body.className,
  }))
  const bundle = await build({ entryPoints: ["tests/visual/fixtures/poll-evolution.tsx"], bundle: true, write: false, outdir: "/tmp/poll-evolution-bundle", jsx: "automatic", define: { "process.env.NODE_ENV": '"production"', "process.env": "{}" }, loader: { ".module.css": "local-css" } })
  const script = bundle.outputFiles.find(file => file.path.endsWith(".js"))!.text
  const css = bundle.outputFiles.find(file => file.path.endsWith(".css"))!.text
  await page.route("**/__poll_fixture*", route => route.fulfill({ contentType: "text/html", body: `<!doctype html><html lang="pt-BR" class="${shell.htmlClass}"><head><meta name="viewport" content="width=device-width, initial-scale=1"><title>Teste isolado de evolução</title>${shell.styles.map(url => `<link rel="stylesheet" href="${url}">`).join("")}<style>${css}</style></head><body class="${shell.bodyClass}"><div id="root"></div><script>${script.replaceAll("</script", "<\\/script")}</script></body></html>` }))
  await page.goto("/__poll_fixture")
  const section = page.locator("[data-pf-polls]")
  await expect(section.locator("[data-pf-poll-line]")).toHaveCount(3)
  await expect(section.locator("[data-pf-poll-dot]")).toHaveCount(12)
  await expect(section.getByRole('combobox', { name: 'Instituto', exact: true })).toHaveValue('all')
  const point = section.getByRole("button", { name: /semana 07\/09\/2026/ })
  await point.focus()
  await expect(section.getByRole("region", { name: "Pesquisa selecionada" })).toContainText("35%")
  await expect(section.locator('[data-pf-week-source]')).toContainText('Média de 2 pesquisas')
  await expect(section.locator('[data-pf-week-source]')).toContainText('Instituto A · Instituto B')
  const members = section.locator('[data-pf-week-member]')
  await expect(members).toHaveCount(2)
  await members.first().locator('summary').first().click()
  await expect(members.first().getByRole('list', { name: 'Resultados originais da pesquisa' })).toContainText('34%')
  await members.first().locator('summary').first().click()
  await section.screenshot({ path: info.outputPath("fixture-evolution-desktop.png") })
  const accessibility = await new AxeBuilder({ page }).include("[data-pf-polls]").withTags(["wcag2a", "wcag2aa"]).analyze()
  expect(accessibility.violations).toEqual([])
  await point.press("ArrowRight")
  await expect(section.getByRole("region", { name: "Pesquisa selecionada" })).toContainText("38%")
  await expect(section.locator("[data-pf-week-source]")).toContainText("Média de 2 pesquisas")
  await expect(section.locator("[data-pf-week-source]").getByRole("link", { name: /Fonte: Instituto A/ })).toHaveAttribute("href", "https://example.org/pesquisa/2026-09-15")
  await expect(section.locator("[data-pf-week-source]").getByRole("link", { name: /Fonte: Instituto B/ })).toHaveAttribute("href", "https://example.org/pesquisa/2026-09-17")
  await section.getByRole('button', { name: 'Fechar detalhes do ponto' }).click()
  await section.getByRole("checkbox", { name: "Candidato A 38%", exact: true }).uncheck()
  await expect(section.locator("[data-pf-poll-line]")).toHaveCount(2)
  await section.getByRole("checkbox", { name: "Candidato B 37%", exact: true }).uncheck()
  await section.getByRole("checkbox", { name: "Candidato C 7%", exact: true }).uncheck()
  await expect(section.getByRole("status")).toContainText("Selecione ao menos um candidato")
  await expect(section.locator("[data-pf-poll-dot]")).toHaveCount(0)
  await section.getByRole("combobox", { name: "Período", exact: true }).selectOption("2026-08")
  await expect(section.locator("[data-pf-poll-dot]")).toHaveCount(6)
  await expect(section.getByRole('checkbox', { name: 'Candidato A 34%', exact: true })).toBeChecked()
  await expect(section.locator('[data-pf-week-source]').getByRole('link', { name: /Fonte: Instituto B/ })).toHaveAttribute('href', 'https://example.org/pesquisa/2026-09-03')
  await section.getByRole("combobox", { name: "Período", exact: true }).selectOption("all")
  await section.getByRole('combobox', { name: 'Instituto', exact: true }).selectOption('Instituto A')
  await expect(section.getByRole('checkbox', { name: 'Candidato A 36%', exact: true })).toBeChecked()
  await expect(section.locator('[data-pf-week-source]')).toContainText('1 pesquisa na semana')
  await section.getByRole('combobox', { name: 'Instituto', exact: true }).selectOption('all')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const mobileResearch = section.locator('[data-pf-mobile-research]')
  await expect(section.locator('[data-pf-poll-chart]')).toBeVisible()
  await expect(mobileResearch).toContainText('14 de set. a 20 de set.')
  await expect(section.getByRole('button', { name: 'Próxima', exact: true })).toBeDisabled()
  await expect(section.getByRole('checkbox', { name: 'Candidato A 38%', exact: true })).toBeChecked()
  await section.getByRole('button', { name: 'Anterior', exact: true }).click()
  await expect(mobileResearch).toContainText('7 de set. a 13 de set.')
  await expect(section.getByRole('checkbox', { name: 'Candidato A 35%', exact: true })).toBeChecked()
  await expect(section.getByRole('region', { name: 'Pesquisa selecionada' })).toHaveCount(0)
  await section.getByRole('button', { name: /semana 24\/08\/2026/ }).click()
  await expect(mobileResearch).toContainText('24 de ago. a 30 de ago.')
  await expect(section.getByRole('checkbox', { name: 'Candidato A 31%', exact: true })).toBeChecked()
  await expect(section.getByRole('button', { name: 'Anterior', exact: true })).toBeDisabled()
  await section.getByRole('button', { name: 'Próxima', exact: true }).click()
  await expect(mobileResearch).toContainText('31 de ago. a 6 de set.')
  await expect(section.getByRole('checkbox', { name: 'Candidato A 34%', exact: true })).toBeChecked()
  await section.screenshot({ path: info.outputPath("fixture-evolution-mobile.png") })
  const mobileAccessibility = await new AxeBuilder({ page }).include('[data-pf-polls]').withTags(['wcag2a', 'wcag2aa']).analyze()
  expect(mobileAccessibility.violations).toEqual([])
  await expect(section.locator('[data-pf-week-source]')).toContainText('31 de ago. a 6 de set.')
  await expect(section.locator('[data-pf-week-source]').getByRole('link', { name: /Fonte: Instituto A/ })).toHaveAttribute('href', 'https://example.org/pesquisa/2026-09-01')
  await expect(section.locator('[data-pf-week-source]').getByRole('link', { name: /Fonte: Instituto B/ })).toHaveAttribute('href', 'https://example.org/pesquisa/2026-09-03')
  await page.setViewportSize({ width: 320, height: 844 })
  await expect.poll(() => section.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await page.goto('/__poll_fixture?missing=1')
  const zero = section.locator('[data-pf-poll-candidate]').filter({ hasText: 'Candidato B' })
  const missing = section.locator('[data-pf-poll-candidate]').filter({ hasText: 'Candidato C' })
  await expect(zero).toContainText('0%')
  await expect(zero.locator('[data-pf-poll-mobile-bar]')).toHaveAttribute('style', /width:\s*0%/)
  await expect(missing).toContainText('Sem resultado')
  await expect(missing.locator('[data-pf-poll-mobile-bar]')).toHaveCount(0)
  await page.goto('/__poll_fixture?partial=1')
  const partial = section.locator('[data-pf-poll-candidate]').filter({ hasText: 'Candidato C' })
  await expect(partial).toContainText('1 de 2 pesquisas com resultado')
  await expect(partial).toContainText('6%')
  await expect(section.locator('[data-pf-week-source]')).toContainText('Média de 2 pesquisas')
  await expect.poll(() => section.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/__poll_fixture?metadata=1')
  await section.getByRole('combobox', { name: 'Instituto', exact: true }).selectOption('Instituto não informado')
  await expect(section.getByRole('checkbox')).toHaveCount(3)
  await expect(section.locator('[data-pf-poll-source]')).toContainText('Instituto não informado')
  await expect(section).not.toContainText('Instituto B')
  await expect(section).not.toContainText('1.500')
  await expect(section).not.toContainText('95%')
  await section.getByText('Ficha técnica e fonte', { exact: true }).click()
  await expect(section.getByRole('link', { name: 'Registro no TSE' })).toHaveCount(0)
  await expect(section).not.toContainText('Pergunta de teste')
  await expect(section).not.toContainText('Contratante de teste')
})
