import { expect, test } from "playwright/test"
import AxeBuilder from "@axe-core/playwright"
import carlos from "../../src/data/programas-governo/governadores-2026/carlos-machado.json"

test("programs start with the approved summary and expose its full text and evidence", async ({ page }) => {
  await page.goto("/uf/sp#programas")
  const section = page.locator("#programas")
  await expect(section.getByRole("button", { name: "Resumo do programa", exact: true })).toHaveAttribute("aria-pressed", "true")
  await expect(section.getByRole("combobox", { name: "Tema do programa" })).toHaveCount(0)
  await expect(section.getByRole("complementary", { name: "Contexto do estado" })).toHaveCount(0)
  const candidate = section.getByRole("article", { name: "Carlos Machado", exact: true })
  await expect(candidate.getByRole("img", { name: "Partido PCB", exact: true })).toBeVisible()
  const logo = candidate.locator("[data-pf-party-logo] img")
  await expect(logo).toHaveAttribute("src", "/partidos/pcb.webp")
  await expect.poll(() => logo.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true)
  await expect(candidate.locator("header")).not.toContainText("PCB · SP")
  const vice = candidate.getByText("Vice: FELIPE QUEIROZ", { exact: true })
  await expect(vice).toBeVisible()
  expect(await vice.evaluate(el => parseFloat(getComputedStyle(el).fontSize)))
    .toBeLessThan(await candidate.locator("h4").evaluate(el => parseFloat(getComputedStyle(el).fontSize)))
  const summary = candidate.getByText(carlos.resumo.texto, { exact: true })
  await expect(summary).toHaveText(carlos.resumo.texto)
  const collapsedHeight = await summary.evaluate(el => el.clientHeight)
  const expand = candidate.getByRole("button", { name: "Ler resumo completo de Carlos Machado" })
  await expect(expand).toHaveAttribute("aria-expanded", "false")
  await expand.focus()
  await page.keyboard.press("Enter")
  await expect(candidate.getByRole("button", { name: "Recolher resumo de Carlos Machado" })).toHaveAttribute("aria-expanded", "true")
  expect(await summary.evaluate(el => el.clientHeight)).toBeGreaterThan(collapsedHeight)
  await candidate.getByText("Ver trechos e fonte", { exact: true }).click()
  await expect(candidate.locator("blockquote").first()).toContainText(carlos.resumo.frases[0].evidencias[0].trecho)
  await expect(candidate.getByRole("link", { name: "Documento no TSE" }).first()).toHaveAttribute("href", /tse\.jus\.br/)
  await expect(candidate.getByRole("link", { name: "Abrir programa de Carlos Machado" })).toHaveAttribute("href", "/candidato/carlos-machado?tab=programa")
})

test("candidate and theme filters preserve missing-program and missing-theme distinctions", async ({ page }) => {
  await page.goto("/uf/sp#programas")
  const section = page.locator("#programas")
  const rows = section.getByRole("article")
  await expect(rows.first()).toBeVisible()
  const alphabetical = await rows.locator("h4").allTextContents()
  expect(alphabetical.length).toBeGreaterThan(1)
  expect(alphabetical).toEqual([...alphabetical].sort((a, b) => a.localeCompare(b, "pt-BR")))
  await section.getByRole("combobox", { name: "Ordenação" }).selectOption("desc")
  await expect(rows.first().locator("h4")).toHaveText(alphabetical.at(-1)!)
  await section.getByRole("combobox", { name: "Candidaturas", exact: true }).selectOption("policial-edjane")
  await expect(rows).toHaveCount(1)
  await expect(rows.first()).toContainText("Programa revisado indisponível nesta cobertura.")
  await expect(rows.first()).toContainText("Vice: informação indisponível")
  await expect(rows.first().getByRole("button", { name: /Ler resumo completo/ })).toHaveCount(0)
  await expect(rows.first().getByRole("link", { name: "Consultar ficha" })).toHaveAttribute("href", "/candidato/policial-edjane")
  await section.getByRole("button", { name: "Por tema", exact: true }).click()
  await section.getByRole("combobox", { name: "Tema do programa" }).selectOption("clima")
  await expect(rows.first()).toContainText("Programa revisado indisponível nesta cobertura.")
  await section.getByRole("combobox", { name: "Candidaturas", exact: true }).selectOption("carlos-machado")
  await expect(rows.first()).toContainText("Tema não identificado no resumo revisado. Isso não significa ausência no documento completo.")
  await section.getByRole("button", { name: "Resumo do programa", exact: true }).click()
  await expect(rows.first()).toContainText(carlos.resumo.texto)
  await expect(section.getByText("Tema não identificado", { exact: false })).toHaveCount(0)
  await page.reload()
  await expect(section.getByRole("button", { name: "Resumo do programa", exact: true })).toHaveAttribute("aria-pressed", "true")
  await expect(section.getByRole("combobox", { name: "Candidaturas", exact: true })).toHaveValue("all")
})

for (const width of [1440, 765, 375]) {
  test(`program summary and theme views are accessible and fit ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto("/uf/sp#programas")
    const section = page.locator("#programas")
    await expect(section.getByRole("article").first()).toBeVisible()
    for (const view of ["Resumo do programa", "Por tema"]) {
      await section.getByRole("button", { name: view, exact: true }).click()
      if (view === "Por tema") {
        const select = section.getByRole("combobox", { name: "Tema do programa" })
        const longest = await select.evaluate((el: HTMLSelectElement) => [...el.options].sort((a, b) => b.text.length - a.text.length)[0].value)
        await select.selectOption(longest)
      }
      const bounds = await section.evaluate(el => ({ left: el.getBoundingClientRect().left, right: el.getBoundingClientRect().right, scroll: el.scrollWidth, width: el.clientWidth, viewport: window.innerWidth }))
      expect(bounds.left).toBeGreaterThanOrEqual(0)
      expect(bounds.right).toBeLessThanOrEqual(bounds.viewport)
      expect(bounds.scroll).toBeLessThanOrEqual(bounds.width)
      const a11y = await new AxeBuilder({ page }).include("#programas").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()
      expect(a11y.violations).toEqual([])
      await section.screenshot({ path: testInfo.outputPath(`programs-${width}-${view === "Por tema" ? "themes" : "summary"}.png`) })
    }
  })
}
