"use client"

import { useState } from "react"
import type { StatePollScenario } from "@/lib/state-polls"

const date = (value: string | null) => value ? value.split("-").reverse().join("/") : "Não informado"
export function StatePolls({ polls, unavailable = false }: { polls: StatePollScenario[]; unavailable?: boolean }) {
  const [turn, setTurn] = useState<1 | 2>(1)
  const [selected, setSelected] = useState("")
  const available = polls.filter(p => p.scenario.turn === turn)
  const current = available.find(p => `${p.id}:${p.scenario.id}` === selected) ?? available[0]
  return <section id="pesquisas" className="scroll-mt-24 space-y-6" aria-labelledby="state-polls-title">
    <div><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Pesquisas eleitorais</p><h2 id="state-polls-title" className="font-heading text-3xl uppercase">Um cenário por vez</h2><p className="mt-2 text-sm text-muted-foreground">Cada gráfico corresponde a uma pesquisa e a um cenário. Pesquisas retratam o período de coleta e não são previsão do resultado.</p></div>
    <div className="grid min-w-0 gap-3 sm:grid-cols-[150px_minmax(0,1fr)]"><label className="min-w-0 text-sm font-semibold">Turno<select className="ml-2 min-h-11 rounded-lg border bg-card px-3" value={turn} onChange={e => setTurn(Number(e.target.value) as 1 | 2)}><option value={1}>1º turno</option><option value={2}>2º turno</option></select></label>{current && <label className="min-w-0 text-sm font-semibold">Pesquisa e cenário<select className="mt-1 block min-h-11 w-full min-w-0 max-w-full overflow-hidden text-ellipsis rounded-lg border bg-card px-3" value={`${current.id}:${current.scenario.id}`} onChange={e => setSelected(e.target.value)}>{available.map(p => <option key={`${p.id}:${p.scenario.id}`} value={`${p.id}:${p.scenario.id}`}>{p.instituto.value ?? "Instituto não informado"} · {date(p.publicationDate.value)} · {p.scenario.labelRaw}</option>)}</select></label>}</div>
    {!current ? <p className="rounded-xl border bg-card p-5 text-sm text-muted-foreground">{unavailable ? "Não foi possível carregar as pesquisas agora." : "Sem pesquisa qualificada disponível para este turno na cobertura atual."} <a className="underline" href="https://pesqele-divulgacao.tse.jus.br/" target="_blank" rel="noopener noreferrer">Consultar registros no TSE</a></p> : <article className="rounded-xl border bg-card p-5 sm:p-6"><h3 className="font-semibold">{current.instituto.value ?? "Instituto não informado"} · {current.scenario.labelRaw}</h3><p className="mt-1 text-sm text-muted-foreground">Coleta: {date(current.fieldwork.start.value)} a {date(current.fieldwork.end.value)}</p>{current.scenario.question.value && <p className="mt-3 text-sm">Pergunta: {current.scenario.question.value}</p>}
      <div className="mt-6 grid items-start gap-8 lg:grid-cols-[minmax(0,1fr)_280px]"><ul className="space-y-4" aria-label="Todos os resultados do cenário">{current.scenario.resultados.map((r,i) => {
        const numeric = current.state === "publicado" && r.status === "publicado" && r.valuePercent !== null
        return <li key={`${r.rawLabel}:${i}`}><div className="flex justify-between gap-3 text-sm"><span>{r.rawLabel}{r.matchStatus === "indeterminado" ? " · vínculo com candidatura não confirmado" : ""}</span><strong className={numeric ? "shrink-0 whitespace-nowrap" : undefined}>{numeric ? `${r.valuePercent!.toLocaleString("pt-BR")}%` : "Resultado indisponível"}</strong></div>{numeric && <div className="mt-1 h-3 rounded bg-muted" aria-hidden="true"><div className="h-3 rounded bg-foreground" style={{width:`${r.valuePercent}%`}} /></div>}</li>
      })}</ul>
      <details className="rounded-lg border bg-muted/30 p-4 text-sm" open><summary className="cursor-pointer font-semibold">Ficha técnica e fonte</summary><dl className="mt-3 grid gap-3">{[["Publicação",date(current.publicationDate.value)],["Amostra",current.sample.size.value === null ? "Não informada" : `${current.sample.size.value.toLocaleString("pt-BR")} entrevistas`],["Margem de erro",current.marginErrorPp.value === null ? "Não informada" : `${current.marginErrorPp.value} pontos percentuais`],["Confiança",current.confidencePercent.value === null ? "Não informada" : `${current.confidencePercent.value}%`],["Método",current.method.value ?? "Não informado"],["Contratante",current.contratante.value ?? "Não informado"],["População",current.sample.population.value ?? "Não informada"],["Registro",current.registration.code.value ?? "Não informado"]].map(([label,value]) => <div key={label}><dt className="text-muted-foreground">{label}</dt><dd>{value}</dd></div>)}</dl><div className="mt-4 flex flex-wrap gap-4"><a className="underline" href={current.provenance.resultUrl} target="_blank" rel="noopener noreferrer">Fonte da pesquisa</a>{current.registration.url.value && <a className="underline" href={current.registration.url.value} target="_blank" rel="noopener noreferrer">Registro no TSE</a>}</div><p className="mt-4 text-xs text-muted-foreground">Consulta da fonte: {date(current.provenance.consultedAt.slice(0,10))}.</p></details></div>
    </article>}
  </section>
}
