import type { CandidatePublicSnapshot } from "./audit-types"

export type AssertionCohort =
  | "presidenciaveis"
  | "governadores-prioritarios"
  | "governadores"
  // "alto-trafego" e mantido por compatibilidade de CLI e artefatos.
  // Conceitualmente esta coorte representa trafego editorial estimado,
  // nao analytics reais do site.
  | "alto-trafego"
  | "alto-trafego-editorial"

export type AssertionConfidence = "curated" | "mirrored"

export interface CandidateAssertion {
  slug: string
  source: string
  verifiedAt: string
  confidence: AssertionConfidence
  cohorts: AssertionCohort[]
  expected: Partial<CandidatePublicSnapshot>
}

interface CandidateAssertionInput extends Omit<CandidateAssertion, "verifiedAt"> {
  verifiedAt?: string
}

const DEFAULT_VERIFIED_AT = "2026-04-01"

function inferVerifiedAt(source: string, fallback = DEFAULT_VERIFIED_AT): string {
  const match = source.match(/\b(20\d{2}-\d{2}-\d{2})\b/)
  return match?.[1] ?? fallback
}

const RAW_CANDIDATE_ASSERTIONS: CandidateAssertionInput[] = [
  {
    slug: "lula",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Luiz Inacio Lula da Silva",
      nome_urna: "Lula",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "flavio-bolsonaro",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Flavio Nantes Bolsonaro",
      nome_urna: "Flavio Bolsonaro",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "tarcisio",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Tarcisio Gomes de Freitas",
      nome_urna: "Tarcisio de Freitas",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "romeu-zema",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Romeu Zema Neto",
      nome_urna: "Romeu Zema",
      partido_atual: "Partido Novo",
      partido_sigla: "NOVO",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "ronaldo-caiado",
    source: "PSD oficial 2026-01-28",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Ronaldo Ramos Caiado",
      nome_urna: "Ronaldo Caiado",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "ratinho-junior",
    source: "PSD oficial 2026-03-12",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Carlos Roberto Massa Junior",
      nome_urna: "Ratinho Junior",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "aldo-rebelo",
    source: "DC oficial 2026-02-02",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Jose Aldo Rebelo Figueiredo",
      nome_urna: "Aldo Rebelo",
      partido_atual: "Democracia Crista",
      partido_sigla: "DC",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "renan-santos",
    source: "curadoria presidenciaveis",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Renan Santos",
      nome_urna: "Renan Santos",
      partido_atual: "Missao",
      partido_sigla: "MISSAO",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "ciro-gomes",
    source: "PSDB oficial 2025-10-22",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Ciro Ferreira Gomes",
      nome_urna: "Ciro Gomes",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "hertz-dias",
    source: "curadoria presidenciaveis",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Hertz da Conceicao Dias",
      nome_urna: "Hertz Dias",
      partido_atual: "Partido Socialista dos Trabalhadores Unificado",
      partido_sigla: "PSTU",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "eduardo-leite",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Eduardo Figueiredo Cavalheiro Leite",
      nome_urna: "Eduardo Leite",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "rui-costa-pimenta",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Rui Costa Pimenta",
      nome_urna: "Rui Costa Pimenta",
      partido_atual: "Partido da Causa Operaria",
      partido_sigla: "PCO",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "samara-martins",
    source: "curadoria presidenciaveis",
    verifiedAt: "2026-04-01",
    confidence: "curated",
    cohorts: ["presidenciaveis", "alto-trafego"],
    expected: {
      nome_completo: "Samara Martins",
      nome_urna: "Samara Martins",
      partido_atual: "Unidade Popular",
      partido_sigla: "UP",
      cargo_disputado: "Presidente",
      estado: null,
    },
  },
  {
    slug: "tarcisio-gov-sp",
    source: "Governo de SP + Republicanos oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Tarcisio Gomes de Freitas",
      nome_urna: "Tarcisio de Freitas",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: "Governador de Sao Paulo",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "nikolas-ferreira",
    source: "Camara dos Deputados 2026-03-31",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Nikolas Ferreira Oliveira",
      nome_urna: "Nikolas Ferreira",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_atual: "Deputado(a) Federal",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "rodrigo-pacheco",
    source: "Senado Federal 2026-03-31",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Rodrigo Pacheco Amaral",
      nome_urna: "Rodrigo Pacheco",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "eduardo-paes",
    source: "Prefeitura do Rio + PSD oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Eduardo da Costa Paes",
      nome_urna: "Eduardo Paes",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_atual: "Prefeito do Rio de Janeiro",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "jeronimo",
    source: "Governo da Bahia + PT Bahia 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Jeronimo Rodrigues de Jesus",
      nome_urna: "Jeronimo",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_atual: "Governador da Bahia",
      cargo_disputado: "Governador",
      estado: "BA",
    },
  },
  {
    slug: "elmano-de-freitas",
    source: "Governo do Ceara + PT Ceara 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Elmano de Freitas da Costa",
      nome_urna: "Elmano de Freitas",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_atual: "Governador do Ceara",
      cargo_disputado: "Governador",
      estado: "CE",
    },
  },
  {
    slug: "joao-campos",
    source: "Prefeitura do Recife + PSB oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Joao Henrique de Andrade Lima Campos",
      nome_urna: "Joao Campos",
      partido_atual: "Partido Socialista Brasileiro",
      partido_sigla: "PSB",
      cargo_atual: "Prefeito do Recife",
      cargo_disputado: "Governador",
      estado: "PE",
    },
  },
  {
    slug: "raquel-lyra",
    source: "Governo de Pernambuco + PSD oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Raquel Teixeira Lyra Lucena",
      nome_urna: "Raquel Lyra",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_atual: "Governadora de Pernambuco",
      cargo_disputado: "Governador",
      estado: "PE",
    },
  },
  {
    slug: "cleitinho",
    source: "Senado Federal 2026-03-31",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Cleiton Gontijo de Azevedo",
      nome_urna: "Cleitinho",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "sergio-moro-gov-pr",
    source: "Senado Federal 2026-04-01",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Sergio Fernando Moro",
      nome_urna: "Sergio Moro",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_atual: "Senador(a)",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "jorginho-mello",
    source: "Governo de Santa Catarina + ALESC oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Jorginho dos Santos Mello",
      nome_urna: "Jorginho Mello",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_atual: "Governador de Santa Catarina",
      cargo_disputado: "Governador",
      estado: "SC",
    },
  },
  {
    slug: "ricardo-nunes",
    source: "Prefeitura de Sao Paulo 2026-03-31",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Ricardo Luis Reis Nunes",
      nome_urna: "Ricardo Nunes",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_atual: "Prefeito de Sao Paulo",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "haddad-gov-sp",
    source: "gov.br Fazenda + PT oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Fernando Haddad",
      nome_urna: "Fernando Haddad",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_atual: "Ministro da Fazenda",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "erika-hilton",
    source: "Camara dos Deputados 2026-03-31",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Erika Santos Silva",
      nome_urna: "Erika Hilton",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_atual: "Deputado(a) Federal",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "geraldo-alckmin",
    source: "Vice-Presidencia + PSB oficial 2026-03",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Geraldo Jose Rodrigues Alckmin Filho",
      nome_urna: "Geraldo Alckmin",
      partido_atual: "Partido Socialista Brasileiro",
      partido_sigla: "PSB",
      cargo_atual: "Vice-Presidente da Republica",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "ciro-gomes-gov-ce",
    source: "PSDB oficial 2025-10-22",
    confidence: "curated",
    cohorts: ["governadores-prioritarios", "alto-trafego"],
    expected: {
      nome_completo: "Ciro Ferreira Gomes",
      nome_urna: "Ciro Gomes",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_atual: null,
      cargo_disputado: "Governador",
      estado: "CE",
    },
  },
  {
    slug: "alan-rick",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Alan Rick Pereira da Silva",
      nome_urna: "Alan Rick",
      partido_atual: "REPUBLICANOS",
      partido_sigla: "REPUBLICANOS",
      cargo_disputado: "Governador",
      estado: "AC",
    },
  },
  {
    slug: "andre-kamai",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Andre Luiz Oliveira Kamai",
      nome_urna: "Andre Kamai",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "AC",
    },
  },
  {
    slug: "mailza-assis",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Mailza Gomes Assis",
      nome_urna: "Mailza Assis",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "AC",
    },
  },
  {
    slug: "tiao-bocalom",
    source: "filiacao PSDB mar/2026 confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Sebastiao Bocalom Rodrigues",
      nome_urna: "Tiao Bocalom",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "AC",
    },
  },
  {
    slug: "jhc",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Joao Henrique Caldas",
      nome_urna: "JHC",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "AL",
    },
  },
  {
    slug: "renan-filho",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Renan Calheiros Filho",
      nome_urna: "Renan Filho",
      partido_atual: "MDB",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "AL",
    },
  },
  {
    slug: "david-almeida",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "David Antonio de Abreu Almeida",
      nome_urna: "David Almeida",
      partido_atual: "Avante",
      partido_sigla: "AVANTE",
      cargo_disputado: "Governador",
      estado: "AM",
    },
  },
  {
    slug: "eduardo-braga",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Eduardo Braga Granata",
      nome_urna: "Eduardo Braga",
      partido_atual: "MDB",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "AM",
    },
  },
  {
    slug: "maria-do-carmo",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Maria do Carmo Seffair",
      nome_urna: "Maria do Carmo",
      partido_atual: "PP",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "AM",
    },
  },
  {
    slug: "omar-aziz",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Omar Jose Abdel Aziz",
      nome_urna: "Omar Aziz",
      partido_atual: "PSD",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "AM",
    },
  },
  {
    slug: "tadeu-de-souza",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Tadeu de Souza Lima",
      nome_urna: "Tadeu de Souza",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "AM",
    },
  },
  {
    slug: "clecio-luis",
    source: "filiacao Uniao Brasil jan/2026 confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Clecio Luis Vilhena Vieira",
      nome_urna: "Clecio Luis",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "AP",
    },
  },
  {
    slug: "dr-furlan",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Jose Antonio D Almeida Furlan",
      nome_urna: "Dr. Furlan",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "AP",
    },
  },
  {
    slug: "joao-capiberibe",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Joao Alberto Rodrigues Capiberibe",
      nome_urna: "Joao Capiberibe",
      partido_atual: "PSB",
      partido_sigla: "PSB",
      cargo_disputado: "Governador",
      estado: "AP",
    },
  },
  {
    slug: "acm-neto",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Antonio Carlos Peixoto de Magalhaes Neto",
      nome_urna: "ACM Neto",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "BA",
    },
  },
  {
    slug: "joao-roma",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Joao Carlos Bacelar Batista",
      nome_urna: "Joao Roma",
      partido_atual: "PL",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "BA",
    },
  },
  {
    slug: "jose-carlos-aleluia",
    source: "filiacao NOVO confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Jose Carlos Aleluia Costa",
      nome_urna: "Jose Carlos Aleluia",
      partido_atual: "Partido Novo",
      partido_sigla: "NOVO",
      cargo_disputado: "Governador",
      estado: "BA",
    },
  },
  {
    slug: "ronaldo-mansur",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Ronaldo Mansur",
      nome_urna: "Ronaldo Mansur",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "BA",
    },
  },
  {
    slug: "capitao-wagner",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Wagner Sousa Gomes",
      nome_urna: "Capitao Wagner",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "CE",
    },
  },
  {
    slug: "eduardo-girao",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Eduardo Girao Monteiro Filho",
      nome_urna: "Eduardo Girao",
      partido_atual: "NOVO",
      partido_sigla: "NOVO",
      cargo_disputado: "Governador",
      estado: "CE",
    },
  },
  {
    slug: "roberto-claudio",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Roberto Claudio Rodrigues Bezerra",
      nome_urna: "Roberto Claudio",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "CE",
    },
  },
  {
    slug: "celina-leao",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Celina Leao Rocha de Siqueira Campos",
      nome_urna: "Celina Leao",
      partido_atual: "PP",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "DF",
    },
  },
  {
    slug: "leandro-grass",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Leandro Grass Peixoto",
      nome_urna: "Leandro Grass",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "DF",
    },
  },
  {
    slug: "paula-belmonte",
    source: "CLDF 2025-12-23",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Paula Francinete Belmonte da Silva",
      nome_urna: "Paula Belmonte",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "DF",
    },
  },
  {
    slug: "ricardo-cappelli",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Ricardo Ribeiro Cappelli",
      nome_urna: "Ricardo Cappelli",
      partido_atual: "Partido Socialista Brasileiro",
      partido_sigla: "PSB",
      cargo_disputado: "Governador",
      estado: "DF",
    },
  },
  {
    slug: "arnaldinho-borgo",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Arnaldinho Borgo",
      nome_urna: "Arnaldinho Borgo",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "da-vitoria",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Josias da Vitoria",
      nome_urna: "Da Vitoria",
      partido_atual: "PP",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "helder-salomao",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Helder Ignacio Salomao",
      nome_urna: "Helder Salomao",
      partido_atual: "PT",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "paulo-hartung",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Paulo Cesar Hartung Gomes",
      nome_urna: "Paulo Hartung",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "pazolini",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Lorenzo Pazolini",
      nome_urna: "Pazolini",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "ricardo-ferraco",
    source: "filiacao MDB confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Ricardo de Rezende Ferraco",
      nome_urna: "Ricardo Ferraco",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "sergio-vidigal",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Sergio Vidigal",
      nome_urna: "Sergio Vidigal",
      partido_atual: "PDT",
      partido_sigla: "PDT",
      cargo_disputado: "Governador",
      estado: "ES",
    },
  },
  {
    slug: "adriana-accorsi",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Adriana Accorsi de Queiroz",
      nome_urna: "Adriana Accorsi",
      partido_atual: "PT",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "GO",
    },
  },
  {
    slug: "daniel-vilela",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Daniel Goulart Vilela",
      nome_urna: "Daniel Vilela",
      partido_atual: "MDB",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "GO",
    },
  },
  {
    slug: "jose-eliton",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Jose Eliton de Figueredo Telles Junior",
      nome_urna: "Jose Eliton",
      partido_atual: "Partido Socialista Brasileiro",
      partido_sigla: "PSB",
      cargo_disputado: "Governador",
      estado: "GO",
    },
  },
  {
    slug: "marconi-perillo",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marconi Ferreira Perillo Junior",
      nome_urna: "Marconi Perillo",
      partido_atual: "PSDB",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "GO",
    },
  },
  {
    slug: "wilder-morais",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Wilder Gomes de Morais",
      nome_urna: "Wilder Morais",
      partido_atual: "PL",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "GO",
    },
  },
  {
    slug: "eduardo-braide",
    source: "PSD MA 2026-01-19",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Eduardo Costa Braide",
      nome_urna: "Eduardo Braide",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "MA",
    },
  },
  {
    slug: "enilton-rodrigues",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Enilton Rodrigues",
      nome_urna: "Enilton Rodrigues",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "MA",
    },
  },
  {
    slug: "felipe-camarao",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Felipe Costa Camarao",
      nome_urna: "Felipe Camarao",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "MA",
    },
  },
  {
    slug: "lahesio-bonfim",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Lahesio Rodrigues Bonfim",
      nome_urna: "Lahesio Bonfim",
      partido_atual: "Partido Novo",
      partido_sigla: "NOVO",
      cargo_disputado: "Governador",
      estado: "MA",
    },
  },
  {
    slug: "orleans-brandao",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Orleans Torres Ribeiro Brandao",
      nome_urna: "Orleans Brandao",
      partido_atual: "Partido Socialista Brasileiro",
      partido_sigla: "PSB",
      cargo_disputado: "Governador",
      estado: "MA",
    },
  },
  {
    slug: "gabriel-azevedo",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Gabriel Azevedo",
      nome_urna: "Gabriel Azevedo",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "maria-da-consolacao",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Maria da Consolacao Soares",
      nome_urna: "Maria da Consolacao",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "mateus-simoes",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Mateus Simoes",
      nome_urna: "Mateus Simoes",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "MG",
    },
  },
  {
    slug: "eduardo-riedel",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Eduardo Correa Riedel",
      nome_urna: "Eduardo Riedel",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "MS",
    },
  },
  {
    slug: "fabio-trad",
    source: "filiacao PT confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Fabio Trad",
      nome_urna: "Fabio Trad",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "MS",
    },
  },
  {
    slug: "joao-henrique-catan",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Joao Henrique Catan",
      nome_urna: "Joao Henrique Catan",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "MS",
    },
  },
  {
    slug: "lucien-rezende",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Lucien Miranda de Rezende",
      nome_urna: "Lucien Rezende",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "MS",
    },
  },
  {
    slug: "janaina-riva",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Janaina Riva",
      nome_urna: "Janaina Riva",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "MT",
    },
  },
  {
    slug: "natasha-slhessarenko",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Natasha Slhessarenko",
      nome_urna: "Natasha Slhessarenko",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "MT",
    },
  },
  {
    slug: "otaviano-pivetta",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Otaviano Pivetta",
      nome_urna: "Otaviano Pivetta",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_disputado: "Governador",
      estado: "MT",
    },
  },
  {
    slug: "wellington-fagundes",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Wellington Fagundes",
      nome_urna: "Wellington Fagundes",
      partido_atual: "PL",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "MT",
    },
  },
  {
    slug: "beto-faro",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Jose Beto Faro Pereira",
      nome_urna: "Beto Faro",
      partido_atual: "PT",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "PA",
    },
  },
  {
    slug: "delegado-eder-mauro",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Eder Braga Mauro",
      nome_urna: "Delegado Eder Mauro",
      partido_atual: "PL",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "PA",
    },
  },
  {
    slug: "dr-daniel",
    source: "O Liberal 2026-03-28",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Daniel Barbosa Santos",
      nome_urna: "Dr. Daniel",
      partido_atual: "Partido Socialista Brasileiro",
      partido_sigla: "PSB",
      cargo_disputado: "Governador",
      estado: "PA",
    },
  },
  {
    slug: "hana-ghassan",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Hana Ghassan Tuma",
      nome_urna: "Hana Ghassan",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "PA",
    },
  },
  {
    slug: "simao-jatene",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Simao Robison Oliveira Jatene",
      nome_urna: "Simao Jatene",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "PA",
    },
  },
  {
    slug: "cicero-lucena",
    source: "filiacao MDB set/2025 confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Cicero de Lucena Filho",
      nome_urna: "Cicero Lucena",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "PB",
    },
  },
  {
    slug: "efraim-filho",
    source: "Senado Federal 2026-04-01",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Efraim de Araujo Morais Filho",
      nome_urna: "Efraim Filho",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "PB",
    },
  },
  {
    slug: "lucas-ribeiro",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Lucas Ribeiro",
      nome_urna: "Lucas Ribeiro",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "PB",
    },
  },
  {
    slug: "pedro-cunha-lima",
    source: "MaisPB 2025-11-01",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Pedro Cunha Lima",
      nome_urna: "Pedro Cunha Lima",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "PB",
    },
  },
  {
    slug: "anderson-ferreira",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Anderson Ferreira de Alencar",
      nome_urna: "Anderson Ferreira",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "PE",
    },
  },
  {
    slug: "gilson-machado",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Gilson Machado Guimaraes Neto",
      nome_urna: "Gilson Machado",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "PE",
    },
  },
  {
    slug: "ivan-moraes",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Ivan Moraes Filho",
      nome_urna: "Ivan Moraes",
      partido_atual: "Partido Socialismo e Liberdade",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "PE",
    },
  },
  {
    slug: "joel-rodrigues",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Joel Rodrigues de Castro",
      nome_urna: "Joel Rodrigues",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "PI",
    },
  },
  {
    slug: "margarete-coelho",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Margarete de Castro Coelho",
      nome_urna: "Margarete Coelho",
      partido_atual: "PP",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "PI",
    },
  },
  {
    slug: "rafael-fonteles",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Rafael Tajra Fonteles",
      nome_urna: "Rafael Fonteles",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "PI",
    },
  },
  {
    slug: "silvio-mendes",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Silvio Mendes de Oliveira Filho",
      nome_urna: "Silvio Mendes",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "PI",
    },
  },
  {
    slug: "alexandre-curi",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Alexandre Curi",
      nome_urna: "Alexandre Curi",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "guto-silva",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Luiz Augusto Silva",
      nome_urna: "Guto Silva",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "paulo-martins-gov-pr",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Paulo Martins",
      nome_urna: "Paulo Martins",
      partido_atual: "PL",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "rafael-greca",
    source: "filiacao MDB mar/2026 confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Rafael Valdomiro Greca de Macedo",
      nome_urna: "Rafael Greca",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "requiao-filho",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Mauricio Thadeu de Mello e Silva",
      nome_urna: "Requiao Filho",
      partido_atual: "Partido Democratico Trabalhista",
      partido_sigla: "PDT",
      cargo_disputado: "Governador",
      estado: "PR",
    },
  },
  {
    slug: "douglas-ruas",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Douglas Ruas",
      nome_urna: "Douglas Ruas",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "garotinho",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Anthony William Matheus de Oliveira",
      nome_urna: "Garotinho",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "rodrigo-bacellar",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Rodrigo Bacellar",
      nome_urna: "Rodrigo Bacellar",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "tarcisio-motta",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Tarcisio Motta de Carvalho",
      nome_urna: "Tarcisio Motta",
      partido_atual: "PSOL",
      partido_sigla: "PSOL",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "washington-reis",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Washington Reis de Oliveira",
      nome_urna: "Washington Reis",
      partido_atual: "MDB",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "RJ",
    },
  },
  {
    slug: "alvaro-dias-rn",
    source: "Agora RN 2026-03-23",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Alvaro Costa Dias",
      nome_urna: "Alvaro Dias",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_disputado: "Governador",
      estado: "RN",
    },
  },
  {
    slug: "alysson-bezerra",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Alysson Leandro Barbate Bezerra",
      nome_urna: "Alysson Bezerra",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "RN",
    },
  },
  {
    slug: "cadu-xavier",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Carlos Eduardo Xavier",
      nome_urna: "Cadu Xavier",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "RN",
    },
  },
  {
    slug: "adailton-furia",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Adailton de Souza Furia",
      nome_urna: "Adailton Furia",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "confucio-moura",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Jose Confucio Aires Moura",
      nome_urna: "Confucio Moura",
      partido_atual: "MDB",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "dr-fernando-maximo",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Fernando Maximo de Oliveira",
      nome_urna: "Dr. Fernando Maximo",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "expedito-netto",
    source: "filiacao PT jan/2026 confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Expedito Goncalves Ferreira Netto",
      nome_urna: "Expedito Netto",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "hildon-chaves",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Hildon de Lima Chaves",
      nome_urna: "Hildon Chaves",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "marcos-rogerio",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marcos Rogerio da Silva Brito",
      nome_urna: "Marcos Rogerio",
      partido_atual: "PL",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "RO",
    },
  },
  {
    slug: "arthur-henrique",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Arthur Cesar Guedes Henrique",
      nome_urna: "Arthur Henrique",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "RR",
    },
  },
  {
    slug: "edilson-damiao",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Edilson Damiao da Silva",
      nome_urna: "Edilson Damiao",
      partido_atual: "Progressistas",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "RR",
    },
  },
  {
    slug: "soldado-sampaio",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Soldado Sampaio",
      nome_urna: "Soldado Sampaio",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "RR",
    },
  },
  {
    slug: "teresa-surita",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Teresa Juca Surita",
      nome_urna: "Teresa Surita",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "RR",
    },
  },
  {
    slug: "edegar-pretto",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Edegar Pretto",
      nome_urna: "Edegar Pretto",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "evandro-augusto",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Evandro Augusto",
      nome_urna: "Evandro Augusto",
      partido_atual: "Partido Missao",
      partido_sigla: "MISSAO",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "gabriel-souza",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Gabriel Souza",
      nome_urna: "Gabriel Souza",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "juliana-brizola",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Juliana Daudt Brizola",
      nome_urna: "Juliana Brizola",
      partido_atual: "Partido Democratico Trabalhista",
      partido_sigla: "PDT",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "luciano-zucco",
    source: "Camara dos Deputados 2026-04-01",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Luciano Lorenzini Zucco",
      nome_urna: "Luciano Zucco",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "marcelo-maranata",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marcelo Maranata",
      nome_urna: "Marcelo Maranata",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "RS",
    },
  },
  {
    slug: "decio-lima",
    source: "filiacao PT confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Decio Nery de Lima",
      nome_urna: "Decio Lima",
      partido_atual: "Partido dos Trabalhadores",
      partido_sigla: "PT",
      cargo_disputado: "Governador",
      estado: "SC",
    },
  },
  {
    slug: "joao-rodrigues",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Joao Rodrigues",
      nome_urna: "Joao Rodrigues",
      partido_atual: "AVANTE",
      partido_sigla: "AVANTE",
      cargo_disputado: "Governador",
      estado: "SC",
    },
  },
  {
    slug: "marcelo-brigadeiro",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marcelo Brigadeiro",
      nome_urna: "Marcelo Brigadeiro",
      partido_atual: "Partido Missao",
      partido_sigla: "MISSAO",
      cargo_disputado: "Governador",
      estado: "SC",
    },
  },
  {
    slug: "marcos-vieira",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marcos Vieira",
      nome_urna: "Marcos Vieira",
      partido_atual: "Partido da Social Democracia Brasileira",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "SC",
    },
  },
  {
    slug: "fabio-mitidieri",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Fabio Mitidieri de Amorim",
      nome_urna: "Fabio Mitidieri",
      partido_atual: "PSD",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "SE",
    },
  },
  {
    slug: "thiago-de-joaldo",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Thiago Rezende de Oliveira",
      nome_urna: "Thiago de Joaldo",
      partido_atual: "PP",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "SE",
    },
  },
  {
    slug: "valmir-de-francisquinho",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Valmir dos Santos Costa",
      nome_urna: "Valmir de Francisquinho",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "SE",
    },
  },
  {
    slug: "andre-do-prado",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Andre Luis do Prado",
      nome_urna: "Andre do Prado",
      partido_atual: "Partido Liberal",
      partido_sigla: "PL",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "felicio-ramuth",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Felicio Ramuth",
      nome_urna: "Felicio Ramuth",
      partido_atual: "Movimento Democratico Brasileiro",
      partido_sigla: "MDB",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "gilberto-kassab",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Gilberto Kassab",
      nome_urna: "Gilberto Kassab",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "guilherme-derrite",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Guilherme Muraro Derrite",
      nome_urna: "Guilherme Derrite",
      partido_atual: "PP",
      partido_sigla: "PP",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "marcio-franca",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Marcio Luiz Franca Gomes",
      nome_urna: "Marcio Franca",
      partido_atual: "PSB",
      partido_sigla: "PSB",
      cargo_disputado: "Governador",
      estado: "SP",
    },
  },
  {
    slug: "amelio-cayres",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Amelio Antunes Cayres",
      nome_urna: "Amelio Cayres",
      partido_atual: "Republicanos",
      partido_sigla: "REPUBLICANOS",
      cargo_disputado: "Governador",
      estado: "TO",
    },
  },
  {
    slug: "ataides-oliveira",
    source: "filiacao NOVO set/2025 confirmada",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Ataides de Oliveira Leite",
      nome_urna: "Ataides Oliveira",
      partido_atual: "Partido Novo",
      partido_sigla: "NOVO",
      cargo_disputado: "Governador",
      estado: "TO",
    },
  },
  {
    slug: "laurez-moreira",
    source: "Voz do Bico 2025-12-11",
    confidence: "curated",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Laurez da Rocha Moreira",
      nome_urna: "Laurez Moreira",
      partido_atual: "Partido Social Democratico",
      partido_sigla: "PSD",
      cargo_disputado: "Governador",
      estado: "TO",
    },
  },
  {
    slug: "professora-dorinha",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Maria Auxiliadora Seabra Rezende",
      nome_urna: "Professora Dorinha",
      partido_atual: "Uniao Brasil",
      partido_sigla: "UNIAO",
      cargo_disputado: "Governador",
      estado: "TO",
    },
  },
  {
    slug: "vicentinho-junior",
    source: "banco auditado 2026-04-01",
    confidence: "mirrored",
    cohorts: ["governadores"],
    expected: {
      nome_completo: "Vicente Lopes de Oliveira Junior",
      nome_urna: "Vicentinho Junior",
      partido_atual: "PSDB",
      partido_sigla: "PSDB",
      cargo_disputado: "Governador",
      estado: "TO",
    },
  },
]

export const CANDIDATE_ASSERTIONS: CandidateAssertion[] = RAW_CANDIDATE_ASSERTIONS.map((item) => ({
  ...item,
  verifiedAt: item.verifiedAt ?? inferVerifiedAt(item.source),
}))

export const ASSERTIONS_MAP = new Map(
  CANDIDATE_ASSERTIONS.map((item) => [item.slug, item])
)

export function getAssertionSlugsForCohort(cohort: AssertionCohort): string[] {
  const normalizedCohort =
    cohort === "alto-trafego-editorial" ? "alto-trafego" : cohort

  return CANDIDATE_ASSERTIONS.filter((item) => item.cohorts.includes(normalizedCohort)).map(
    (item) => item.slug
  )
}
