-- Restaura rótulos CEAPS gravados com U+FFFD (Latin-1 lido como UTF-8).
-- Fonte: https://www.senado.leg.br/transparencia/LAI/verba/despesa_ceaps_{ano}.csv
-- O arquivo oficial chega application/octet-stream sem charset; os bytes são
-- ISO-8859-1. UTF-8 nesse buffer produz U+FFFD em TIPO_DESPESA. Confirmado no
-- JSON persistido de alan-rick e mailza-assis; cleitinho tem os mesmos rótulos
-- em UTF-8 correto. Não é correção de display: o replace é no jsonb gravado.

-- @write tabela=gastos_parlamentares slug=alan-rick campos=detalhamento,gastos_destaque
UPDATE public.gastos_parlamentares g
SET
  detalhamento = replace(replace(replace(replace(replace(replace(replace(g.detalhamento::text, $ceaps$Aluguel de im�veis para escrit�rio pol�tico, compreendendo despesas concernentes a eles.$ceaps$, $ceaps$Aluguel de imóveis para escritório político, compreendendo despesas concernentes a eles.$ceaps$), $ceaps$Aquisi��o de material de consumo para uso no escrit�rio pol�tico, inclusive aquisi��o ou loca��o de software, despesas postais, aquisi��o de publica��es, loca��o de m�veis e de equipamentos. $ceaps$, $ceaps$Aquisição de material de consumo para uso no escritório político, inclusive aquisição ou locação de software, despesas postais, aquisição de publicações, locação de móveis e de equipamentos. $ceaps$), $ceaps$Contrata��o de consultorias, assessorias, pesquisas, trabalhos t�cnicos e outros servi�os de apoio ao exerc�cio do mandato parlamentar$ceaps$, $ceaps$Contratação de consultorias, assessorias, pesquisas, trabalhos técnicos e outros serviços de apoio ao exercício do mandato parlamentar$ceaps$), $ceaps$Divulga��o da atividade parlamentar$ceaps$, $ceaps$Divulgação da atividade parlamentar$ceaps$), $ceaps$Locomo��o, hospedagem, alimenta��o, combust�veis e lubrificantes$ceaps$, $ceaps$Locomoção, hospedagem, alimentação, combustíveis e lubrificantes$ceaps$), $ceaps$Passagens a�reas, aqu�ticas e terrestres nacionais$ceaps$, $ceaps$Passagens aéreas, aquáticas e terrestres nacionais$ceaps$), $ceaps$Servi�os de Seguran�a Privada$ceaps$, $ceaps$Serviços de Segurança Privada$ceaps$)::jsonb,
  gastos_destaque = replace(replace(replace(replace(replace(replace(replace(coalesce(g.gastos_destaque::text, '[]'), $ceaps$Aluguel de im�veis para escrit�rio pol�tico, compreendendo despesas concernentes a eles.$ceaps$, $ceaps$Aluguel de imóveis para escritório político, compreendendo despesas concernentes a eles.$ceaps$), $ceaps$Aquisi��o de material de consumo para uso no escrit�rio pol�tico, inclusive aquisi��o ou loca��o de software, despesas postais, aquisi��o de publica��es, loca��o de m�veis e de equipamentos. $ceaps$, $ceaps$Aquisição de material de consumo para uso no escritório político, inclusive aquisição ou locação de software, despesas postais, aquisição de publicações, locação de móveis e de equipamentos. $ceaps$), $ceaps$Contrata��o de consultorias, assessorias, pesquisas, trabalhos t�cnicos e outros servi�os de apoio ao exerc�cio do mandato parlamentar$ceaps$, $ceaps$Contratação de consultorias, assessorias, pesquisas, trabalhos técnicos e outros serviços de apoio ao exercício do mandato parlamentar$ceaps$), $ceaps$Divulga��o da atividade parlamentar$ceaps$, $ceaps$Divulgação da atividade parlamentar$ceaps$), $ceaps$Locomo��o, hospedagem, alimenta��o, combust�veis e lubrificantes$ceaps$, $ceaps$Locomoção, hospedagem, alimentação, combustíveis e lubrificantes$ceaps$), $ceaps$Passagens a�reas, aqu�ticas e terrestres nacionais$ceaps$, $ceaps$Passagens aéreas, aquáticas e terrestres nacionais$ceaps$), $ceaps$Servi�os de Seguran�a Privada$ceaps$, $ceaps$Serviços de Segurança Privada$ceaps$)::jsonb
FROM public.candidatos c
WHERE g.candidato_id = c.id
  AND c.slug = 'alan-rick'
  AND (
    g.detalhamento::text LIKE '%' || U&'\FFFD' || '%'
    OR coalesce(g.gastos_destaque::text, '') LIKE '%' || U&'\FFFD' || '%'
  );

-- @write tabela=gastos_parlamentares slug=mailza-assis campos=detalhamento,gastos_destaque
UPDATE public.gastos_parlamentares g
SET
  detalhamento = replace(replace(replace(replace(replace(replace(replace(g.detalhamento::text, $ceaps$Aluguel de im�veis para escrit�rio pol�tico, compreendendo despesas concernentes a eles.$ceaps$, $ceaps$Aluguel de imóveis para escritório político, compreendendo despesas concernentes a eles.$ceaps$), $ceaps$Aquisi��o de material de consumo para uso no escrit�rio pol�tico, inclusive aquisi��o ou loca��o de software, despesas postais, aquisi��o de publica��es, loca��o de m�veis e de equipamentos. $ceaps$, $ceaps$Aquisição de material de consumo para uso no escritório político, inclusive aquisição ou locação de software, despesas postais, aquisição de publicações, locação de móveis e de equipamentos. $ceaps$), $ceaps$Contrata��o de consultorias, assessorias, pesquisas, trabalhos t�cnicos e outros servi�os de apoio ao exerc�cio do mandato parlamentar$ceaps$, $ceaps$Contratação de consultorias, assessorias, pesquisas, trabalhos técnicos e outros serviços de apoio ao exercício do mandato parlamentar$ceaps$), $ceaps$Divulga��o da atividade parlamentar$ceaps$, $ceaps$Divulgação da atividade parlamentar$ceaps$), $ceaps$Locomo��o, hospedagem, alimenta��o, combust�veis e lubrificantes$ceaps$, $ceaps$Locomoção, hospedagem, alimentação, combustíveis e lubrificantes$ceaps$), $ceaps$Passagens a�reas, aqu�ticas e terrestres nacionais$ceaps$, $ceaps$Passagens aéreas, aquáticas e terrestres nacionais$ceaps$), $ceaps$Servi�os de Seguran�a Privada$ceaps$, $ceaps$Serviços de Segurança Privada$ceaps$)::jsonb,
  gastos_destaque = replace(replace(replace(replace(replace(replace(replace(coalesce(g.gastos_destaque::text, '[]'), $ceaps$Aluguel de im�veis para escrit�rio pol�tico, compreendendo despesas concernentes a eles.$ceaps$, $ceaps$Aluguel de imóveis para escritório político, compreendendo despesas concernentes a eles.$ceaps$), $ceaps$Aquisi��o de material de consumo para uso no escrit�rio pol�tico, inclusive aquisi��o ou loca��o de software, despesas postais, aquisi��o de publica��es, loca��o de m�veis e de equipamentos. $ceaps$, $ceaps$Aquisição de material de consumo para uso no escritório político, inclusive aquisição ou locação de software, despesas postais, aquisição de publicações, locação de móveis e de equipamentos. $ceaps$), $ceaps$Contrata��o de consultorias, assessorias, pesquisas, trabalhos t�cnicos e outros servi�os de apoio ao exerc�cio do mandato parlamentar$ceaps$, $ceaps$Contratação de consultorias, assessorias, pesquisas, trabalhos técnicos e outros serviços de apoio ao exercício do mandato parlamentar$ceaps$), $ceaps$Divulga��o da atividade parlamentar$ceaps$, $ceaps$Divulgação da atividade parlamentar$ceaps$), $ceaps$Locomo��o, hospedagem, alimenta��o, combust�veis e lubrificantes$ceaps$, $ceaps$Locomoção, hospedagem, alimentação, combustíveis e lubrificantes$ceaps$), $ceaps$Passagens a�reas, aqu�ticas e terrestres nacionais$ceaps$, $ceaps$Passagens aéreas, aquáticas e terrestres nacionais$ceaps$), $ceaps$Servi�os de Seguran�a Privada$ceaps$, $ceaps$Serviços de Segurança Privada$ceaps$)::jsonb
FROM public.candidatos c
WHERE g.candidato_id = c.id
  AND c.slug = 'mailza-assis'
  AND (
    g.detalhamento::text LIKE '%' || U&'\FFFD' || '%'
    OR coalesce(g.gastos_destaque::text, '') LIKE '%' || U&'\FFFD' || '%'
  );
