-- Carga do snapshot TSE de 12/08/2026 sobre a estrutura criada pela 20260813040000.
DO $$
DECLARE encontrados integer;
        coorte_presente integer;
        ledger_presente boolean;
BEGIN
  PERFORM set_config('pf.chapas_apply','false',true);
  SELECT count(*) INTO coorte_presente FROM public.candidatos WHERE slug IN ('eduardo-girao', 'luiz-carlos-teodoro', 'rafael-greca', 'francisco-dias', 'geraldo-alckmin', 'raquel-bricio', 'carlos-cley', 'ariel-capistrano', 'pedro-brito', 'reginaldo-lima', 'alexandre-salomao', 'samuel-de-mattos', 'arinalda-do-mlb', 'rodrigo-bolsonaro', 'farah-mesquita', 'policial-edjane', 'du-pereira', 'subtenente-luiz-carlos');
  IF coorte_presente = 0 THEN
    RAISE NOTICE 'banco vazio de replay; carga de chapas 2026 ignorada';
    RETURN;
  END IF;
  ledger_presente := false;
  IF to_regclass('supabase_migrations.schema_migrations') IS NOT NULL THEN
    EXECUTE 'SELECT EXISTS (SELECT 1 FROM supabase_migrations.schema_migrations WHERE version=''20260812130000'')' INTO ledger_presente;
  END IF;
  IF NOT ledger_presente THEN
    RAISE NOTICE 'replay linear sem ledger; carga de chapas 2026 ignorada com % dos 18 slugs sintéticos', coorte_presente;
    RETURN;
  END IF;
  PERFORM set_config('pf.chapas_apply','true',true);
  SELECT count(*) INTO encontrados
  FROM public.candidatos c
  JOIN (VALUES
    ('eduardo-girao', 'Governador', 'CE', 'Vice-Presidente', NULL),
    ('luiz-carlos-teodoro', 'Governador', 'RO', 'Vice-Governador', 'RO'),
    ('rafael-greca', 'Governador', 'PR', 'Vice-Governador', 'PR'),
    ('francisco-dias', 'Governador', 'RN', 'Vice-Governador', 'RN'),
    ('geraldo-alckmin', 'Governador', 'SP', 'Vice-Presidente', NULL),
    ('raquel-bricio', 'Governador', 'PA', 'Vice-Presidente', NULL)
  ) AS e(slug, cargo_antigo, uf_antiga, cargo_novo, uf_nova)
    ON e.slug = c.slug AND c.cargo_disputado = e.cargo_antigo
   AND c.estado IS NOT DISTINCT FROM e.uf_antiga;
  IF encontrados <> 6 THEN
    RAISE EXCEPTION 'pre-condição: esperava 6 papéis antigos exatos, encontrou %', encontrados;
  END IF;
  SELECT count(*) INTO encontrados FROM public.candidatos WHERE slug IN ('carlos-cley', 'ariel-capistrano', 'pedro-brito', 'reginaldo-lima', 'alexandre-salomao', 'samuel-de-mattos', 'arinalda-do-mlb', 'rodrigo-bolsonaro', 'farah-mesquita', 'policial-edjane', 'du-pereira', 'subtenente-luiz-carlos');
  IF encontrados <> 0 THEN
    RAISE EXCEPTION 'pre-condição: % dos 12 slugs oficiais novos já existem', encontrados;
  END IF;
END $$;

-- @write tabela=candidatos slug=carlos-cley campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=ariel-capistrano campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=pedro-brito campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=reginaldo-lima campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=alexandre-salomao campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=samuel-de-mattos campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=arinalda-do-mlb campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=rodrigo-bolsonaro campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=farah-mesquita campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=policial-edjane campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=du-pereira campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
-- @write tabela=candidatos slug=subtenente-luiz-carlos campos=slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,status,situacao_candidatura,publicavel,fonte_dados,verificacao_campos,ultima_atualizacao
INSERT INTO public.candidatos
  (slug, nome_completo, nome_urna, partido_sigla, partido_atual, cargo_disputado,
   estado, data_nascimento, formacao, profissao_declarada, genero, estado_civil, cor_raca,
   status, situacao_candidatura, publicavel, fonte_dados, verificacao_campos, ultima_atualizacao)
SELECT slug, nome_completo, nome_urna, partido_sigla, partido_atual, cargo_disputado,
       estado, data_nascimento::date, formacao, profissao_declarada, genero, estado_civil, cor_raca,
       status, situacao_candidatura, true,
       ARRAY['TSE consulta_cand 2026; snapshot 12/08/2026', 'https://cdn.tse.jus.br/estatistica/sead/odsele/consulta_cand/consulta_cand_2026.zip'],
       '{"candidate_registration":"2026-08-12","candidate_complement":"2026-08-12"}'::jsonb,
       '2026-08-13T07:37:13Z'::timestamptz
FROM (VALUES
  ('carlos-cley', 'CARLOS CLEY RAMOS PAIVA', 'CARLOS CLEY', 'PSTU', 'PARTIDO SOCIALISTA  DOS TRABALHADORES UNIFICADO', 'Governador', 'AP', '1972-07-08', 'ENSINO MÉDIO COMPLETO', 'MOTORISTA PARTICULAR', 'MASCULINO', 'CASADO(A)', 'PARDA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('ariel-capistrano', 'ARIEL DA SILVA CAPISTRANO', 'ARIEL CAPISTRANO', 'DC', 'DEMOCRACIA CRISTÃ', 'Governador', 'BA', '1986-11-01', 'ENSINO MÉDIO INCOMPLETO', 'EMPRESÁRIO', 'MASCULINO', 'CASADO(A)', 'PRETA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('pedro-brito', 'PEDRO FELIPE PINHEIRO BRITO', 'PEDRO BRITO', 'NOVO', 'PARTIDO NOVO', 'Governador', 'CE', '1993-05-26', 'SUPERIOR COMPLETO', 'ADVOGADO', 'MASCULINO', 'SOLTEIRO(A)', 'BRANCA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('reginaldo-lima', 'REGINALDO LIMA BRAUNO', 'REGINALDO LIMA', 'PCB', 'PARTIDO COMUNISTA BRASILEIRO', 'Governador', 'MA', '1983-02-16', 'ENSINO MÉDIO COMPLETO', 'LOCUTOR E COMENTARISTA DE RÁDIO E TELEVISÃO E RADIALISTA', 'MASCULINO', 'CASADO(A)', 'PRETA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('alexandre-salomao', 'ALEXANDRE SALOMAO', 'ALEXANDRE SALOMÃO', 'MOBILIZA', 'MOBILIZAÇÃO NACIONAL', 'Governador', 'PR', '1971-05-30', 'SUPERIOR COMPLETO', 'ADVOGADO', 'MASCULINO', 'CASADO(A)', 'BRANCA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('samuel-de-mattos', 'SAMUEL DE MATTOS FIGUEIREDO', 'SAMUEL DE MATTOS', 'PSTU', 'PARTIDO SOCIALISTA  DOS TRABALHADORES UNIFICADO', 'Governador', 'PR', '1988-03-25', 'SUPERIOR COMPLETO', 'PROFESSOR DE ENSINO MÉDIO', 'MASCULINO', 'CASADO(A)', 'PARDA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('arinalda-do-mlb', 'ARINALDA VASCONCELOS DE MEDEIROS', 'ARINALDA DO MLB', 'UP', 'UNIDADE POPULAR', 'Governador', 'RN', '1980-06-28', 'ENSINO FUNDAMENTAL INCOMPLETO', 'EMPREGADO DOMÉSTICO', 'FEMININO', 'SOLTEIRO(A)', 'PRETA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('rodrigo-bolsonaro', 'KARLO RODRIGO LUCIO VIEIRA', 'RODRIGO BOLSONARO', 'AGIR', 'AGIR', 'Governador', 'RN', '1980-07-17', 'ENSINO MÉDIO COMPLETO', 'EMPRESÁRIO', 'MASCULINO', 'DIVORCIADO(A)', 'BRANCA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('farah-mesquita', 'FARAH MESQUITA', 'FARAH MESQUITA', 'SOLIDARIEDADE', 'SOLIDARIEDADE', 'Governador', 'RR', '1974-11-12', 'SUPERIOR INCOMPLETO', 'OUTROS', 'MASCULINO', 'SOLTEIRO(A)', 'PARDA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('policial-edjane', 'EDJANE LIMA DE SOUSA', 'POLICIAL EDJANE', 'AGIR', 'AGIR', 'Governador', 'SP', '1977-04-28', 'ENSINO MÉDIO COMPLETO', 'POLICIAL MILITAR', 'FEMININO', 'CASADO(A)', 'BRANCA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('du-pereira', 'IVAILDO PEREIRA DA CRUZ', 'DU PEREIRA', 'DC', 'DEMOCRACIA CRISTÃ', 'Governador', 'TO', '1988-09-13', 'ENSINO MÉDIO COMPLETO', 'EMPRESÁRIO', 'MASCULINO', 'SOLTEIRO(A)', 'PARDA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot'),
  ('subtenente-luiz-carlos', 'LUIZ CARLOS FERREIRA DA SILVA', 'SUBTENENTE LUIZ CARLOS', 'DEMOCRATA', 'DEMOCRATA', 'Governador', 'TO', '1968-12-12', 'SUPERIOR COMPLETO', 'POLICIAL MILITAR', 'MASCULINO', 'CASADO(A)', 'PARDA', 'candidato', 'pedido de registro no TSE; situação não informada no snapshot')
) AS v(slug,nome_completo,nome_urna,partido_sigla,partido_atual,cargo_disputado,
       estado,data_nascimento,formacao,profissao_declarada,genero,estado_civil,cor_raca,
       status,situacao_candidatura)
WHERE current_setting('pf.chapas_apply',true)='true';

-- @write tabela=candidatos slug=eduardo-girao campos=cargo_disputado,estado,status,situacao_candidatura,publicavel,fonte_dados,ultima_atualizacao
-- @write tabela=candidatos slug=luiz-carlos-teodoro campos=cargo_disputado,estado,status,situacao_candidatura,publicavel,fonte_dados,ultima_atualizacao
-- @write tabela=candidatos slug=rafael-greca campos=cargo_disputado,estado,status,situacao_candidatura,publicavel,fonte_dados,ultima_atualizacao
-- @write tabela=candidatos slug=francisco-dias campos=cargo_disputado,estado,status,situacao_candidatura,publicavel,fonte_dados,ultima_atualizacao
-- @write tabela=candidatos slug=geraldo-alckmin campos=cargo_disputado,estado,status,situacao_candidatura,publicavel,fonte_dados,ultima_atualizacao
-- @write tabela=candidatos slug=raquel-bricio campos=cargo_disputado,estado,status,situacao_candidatura,publicavel,fonte_dados,ultima_atualizacao
UPDATE public.candidatos c
SET cargo_disputado = e.cargo_novo,
    estado = e.uf_nova,
    status = 'candidato',
    situacao_candidatura = 'pedido de registro no TSE; situação não informada no snapshot',
    publicavel = true,
    fonte_dados = CASE WHEN 'TSE consulta_cand 2026; snapshot 12/08/2026' = ANY(COALESCE(c.fonte_dados, ARRAY[]::text[]))
      THEN c.fonte_dados ELSE COALESCE(c.fonte_dados, ARRAY[]::text[]) || ARRAY['TSE consulta_cand 2026; snapshot 12/08/2026'] END,
    ultima_atualizacao = '2026-08-13T07:37:13Z'::timestamptz
FROM (VALUES
  ('eduardo-girao', 'Governador', 'CE', 'Vice-Presidente', NULL),
    ('luiz-carlos-teodoro', 'Governador', 'RO', 'Vice-Governador', 'RO'),
    ('rafael-greca', 'Governador', 'PR', 'Vice-Governador', 'PR'),
    ('francisco-dias', 'Governador', 'RN', 'Vice-Governador', 'RN'),
    ('geraldo-alckmin', 'Governador', 'SP', 'Vice-Presidente', NULL),
    ('raquel-bricio', 'Governador', 'PA', 'Vice-Presidente', NULL)
) AS e(slug, cargo_antigo, uf_antiga, cargo_novo, uf_nova)
WHERE c.slug = e.slug
  AND current_setting('pf.chapas_apply',true)='true';

-- @write tabela=chapas_2026 ref=snapshot-20260812 chave=686fe1717dd0b860d714f878bf3d75a388478ebab2a56a2f963e6bba50ff0ce7 campos=chave,eleicao_codigo,eleicao_data,uf,cargo_titular,sq_coligacao,identidade_status,vinculo_titular_status,tse_situacao_codigo,titular_candidato_id,vice_candidato_id,titular_sq_candidato,vice_sq_candidato,nomes,partidos,fonte_url,fonte_sha256,snapshot_em
INSERT INTO public.chapas_2026
  (chave,eleicao_codigo,eleicao_data,uf,cargo_titular,sq_coligacao,identidade_status,
   vinculo_titular_status,tse_situacao_codigo,tse_situacao_titular_codigo,
   tse_situacao_vice_codigo,tipo_agremiacao,composicao,titular_candidato_id,
   vice_candidato_id,titular_sq_candidato,vice_sq_candidato,titular_nome_completo,
   titular_nome_urna,titular_partido_sigla,vice_nome_completo,vice_nome_urna,
   vice_partido_sigla,alternativas_oficiais,fonte_url,fonte_sha256,snapshot_em,created_at)
SELECT v.chave,v.eleicao_codigo,v.eleicao_data::date,v.uf,v.cargo_titular,v.sq_coligacao,
       v.identidade_status,v.vinculo_titular_status,v.tse_situacao_codigo,
       v.tse_situacao_titular_codigo,v.tse_situacao_vice_codigo,v.tipo_agremiacao,v.composicao,
       titular.id,vice.id,v.titular_sq_candidato,v.vice_sq_candidato,
       v.titular_nome_completo,v.titular_nome_urna,v.titular_partido_sigla,
       v.vice_nome_completo,v.vice_nome_urna,v.vice_partido_sigla,v.alternativas_oficiais,
       'https://cdn.tse.jus.br/estatistica/sead/odsele/consulta_cand/consulta_cand_2026.zip',
       '686fe1717dd0b860d714f878bf3d75a388478ebab2a56a2f963e6bba50ff0ce7', '2026-08-13T07:37:13Z'::timestamptz,
       '2026-08-13T07:37:13Z'::timestamptz
FROM (VALUES
  ('2026:BR:hertz-da-conceicao-dias', '6257', '2026-10-04', NULL, 'Presidente', '280001800485', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'hertz-dias', NULL, '280002541457', NULL, 'HERTZ DA CONCEICAO DIAS', 'HERTZ DIAS', 'PSTU', 'VANESSA PORTUGAL BARBOSA', 'VANESSA PORTUGAL', 'PSTU', '[]'::jsonb),
  ('2026:BR:luiz-inacio-lula-da-silva', '6257', '2026-10-04', NULL, 'Presidente', '280001800617', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PSB / PDT / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV) / FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'lula', 'geraldo-alckmin', '280002542548', '280002542549', 'LUIZ INÁCIO LULA DA SILVA', 'LULA', 'PT', 'GERALDO JOSE RODRIGUES ALCKMIN FILHO', 'GERALDO ALCKMIN', 'PSB', '[]'::jsonb),
  ('2026:BR:renan-antonio-ferreira-dos-santos', '6257', '2026-10-04', NULL, 'Presidente', '280001800499', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MISSÃO', 'renan-santos', NULL, '280002540694', NULL, 'RENAN ANTONIO FERREIRA DOS SANTOS', 'RENAN SANTOS', 'MISSÃO', 'AROLDO MEDINA', 'CORONEL MEDINA', 'MISSÃO', '[]'::jsonb),
  ('2026:BR:samara-martins-da-silva-feitosa', '6257', '2026-10-04', NULL, 'Presidente', '280001800442', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', 'samara-martins', 'raquel-bricio', '280002538811', '280002538812', 'SAMARA MARTINS DA SILVA FEITOSA', 'SAMARA', 'UP', 'RAQUEL NONATO DE BRICIO', 'RAQUEL BRÍCIO', 'UP', '[]'::jsonb),
  ('2026:BR:wilson-grassi-junior', '6257', '2026-10-04', NULL, 'Presidente', '280001800972', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'DEMOCRATA', NULL, NULL, NULL, NULL, 'WILSON GRASSI JUNIOR', 'VETERINÁRIO WILSON GRASSI', 'DEMOCRATA', 'SUÊD HAIDAR NOGUEIRA', 'SUÊD HAIDAR', 'DEMOCRATA', '[]'::jsonb),
  ('2026:BR:romeu-zema-neto', '6257', '2026-10-04', NULL, 'Presidente', '280001800487', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'NOVO', 'romeu-zema', 'eduardo-girao', '280002539826', '280002539825', 'ROMEU ZEMA NETO', 'ZEMA', 'NOVO', 'LUIS EDUARDO GRANGEIRO GIRÃO', 'EDUARDO GIRÃO', 'NOVO', '[]'::jsonb),
  ('2026:AC:alan-rick-miranda', '6259', '2026-10-04', 'AC', 'Governador', '10001800116', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / NOVO / PSD / AVANTE', 'alan-rick', 'ricardo-leite', '10002532492', '10002532493', 'ALAN RICK MIRANDA', 'ALAN RICK', 'REPUBLICANOS', 'FABIO RICARDO LEITE', 'RICARDO LEITE', 'REPUBLICANOS', '[]'::jsonb),
  ('2026:AC:francisco-das-chagas-conceicao-da-silva', '6259', '2026-10-04', 'AC', 'Governador', '10001800168', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'AGIR', 'dr-luisinho', 'daniela-paiva', '10002533539', '10002533538', 'FRANCISCO DAS CHAGAS CONCEICAO DA SILVA', 'DR.LUISINHO', 'AGIR', 'DANIELA PAIVA DE OLIVEIRA', 'DANIELA PAIVA', 'AGIR', '[]'::jsonb),
  ('2026:AC:eudo-raffael-lima-da-silva', '6259', '2026-10-04', 'AC', 'Governador', '10001801047', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PCB', 'eudo-raffael', NULL, '10002549500', NULL, 'EUDO RAFFAEL LIMA DA SILVA', 'EUDO RAFFAEL', 'PCB', 'CESAR AUGUSTO FELIX DA SILVA', 'POETA CESINHA', 'PCB', '[]'::jsonb),
  ('2026:AC:mailza-assis-cameli', '6259', '2026-10-04', 'AC', 'Governador', '10001800654', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / MDB / PL / DEMOCRATA / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', NULL, NULL, NULL, NULL, 'MAILZA ASSIS CAMELI', 'MAILZA ASSIS', 'PP', 'JESSICA ROJAS SALES', 'JESSICA SALES', 'MDB', '[]'::jsonb),
  ('2026:AC:sebastiao-bocalom-rodrigues', '6259', '2026-10-04', 'AC', 'Governador', '10001800730', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE) / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA)', 'tiao-bocalom', NULL, '10002544015', NULL, 'SEBASTIAO BOCALOM RODRIGUES', 'TIÃO BOCALOM', 'PSDB', 'ADONIS FRANCISCO DE ALMEIDA SOUZA', 'SARGENTO ADONIS', 'PSDB', '[]'::jsonb),
  ('2026:AL:lenilda-luna-de-almeida', '6259', '2026-10-04', 'AL', 'Governador', '20001800463', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', 'lenilda-luna', NULL, '20002539642', NULL, 'LENILDA LUNA DE ALMEIDA', 'LENILDA LUNA', 'UP', 'JARDEL WANDSON QUEIROZ DA CRUZ', 'JARDEL QUEIROZ', 'UP', '[]'::jsonb),
  ('2026:AM:david-antonio-abisai-pereira-de-almeida', '6259', '2026-10-04', 'AM', 'Governador', '40001800278', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / DC / AGIR / AVANTE / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE)', 'david-almeida', NULL, '40002536086', NULL, 'DAVID ANTÔNIO ABISAI PEREIRA DE ALMEIDA', 'DAVID ALMEIDA', 'AVANTE', 'SHADIA HUSSAMI HAUACHE FRAXE', 'DRA. SHÁDIA', 'AVANTE', '[]'::jsonb),
  ('2026:AM:gilberto-vasconcelos-da-silva', '6259', '2026-10-04', 'AM', 'Governador', '40001800269', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'gilberto-vasconcelos', NULL, '40002535267', NULL, 'GILBERTO VASCONCELOS DA SILVA', 'GILBERTO VASCONCELOS', 'PSTU', 'JULIANA FROTA REBOUÇAS', 'JULIANA FROTA', 'PSTU', '[]'::jsonb),
  ('2026:AM:omar-jose-abdel-aziz', '6259', '2026-10-04', 'AM', 'Governador', '40001799964', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / MDB / PSD', 'omar-aziz', 'alessandra-campelo', '40002532272', '40002532271', 'OMAR JOSÉ ABDEL AZIZ', 'OMAR AZIZ', 'PSD', 'ALESSANDRA CAMPELO DA SILVA', 'ALESSANDRA CAMPELO', 'PSD', '[]'::jsonb),
  ('2026:AM:maria-do-carmo-seffair-lins-de-albuquerque', '6259', '2026-10-04', 'AM', 'Governador', '40001800574', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PL / NOVO', 'maria-do-carmo', NULL, '40002541626', NULL, 'MARIA DO CARMO SEFFAIR LINS DE ALBUQUERQUE', 'PROFESSORA MARIA DO CARMO', 'PL', 'MARIO ANIBAL GOMES DA COSTA JUNIOR', 'CORONEL ANIBAL', 'PL', '[]'::jsonb),
  ('2026:AM:roberto-maia-cidade-filho', '6259', '2026-10-04', 'AM', 'Governador', '40001800579', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PSB / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', 'roberto-cidade', NULL, '40002541741', NULL, 'ROBERTO MAIA CIDADE FILHO', 'ROBERTO CIDADE', 'UNIÃO', 'SERAFIM FERNANDES CORREA', 'SERAFIM', 'PSB', '[]'::jsonb),
  ('2026:AP:carlos-cley-ramos-paiva', '6259', '2026-10-04', 'AP', 'Governador', '30001800258', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'carlos-cley', NULL, '30002536313', NULL, 'CARLOS CLEY RAMOS PAIVA', 'CARLOS CLEY', 'PSTU', 'ANA PAULA PINHEIRO DE ARAUJO', 'ANA PAULA PINHEIRO', 'PSTU', '[]'::jsonb),
  ('2026:AP:clecio-luis-vilhena-vieira', '6259', '2026-10-04', 'AP', 'Governador', '30001800257', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / PDT / AGIR / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP) / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA) / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV)', 'clecio-luis', NULL, '30002536311', NULL, 'CLÉCIO LUÍS VILHENA VIEIRA', 'CLÉCIO', 'UNIÃO', 'ANTONIO PINHEIRO TELES JUNIOR', 'TELES JR.', 'PDT', '[]'::jsonb),
  ('2026:AP:antonio-paulo-de-oliveira-furlan', '6259', '2026-10-04', 'AP', 'Governador', '30001799947', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'NOVO / PSD / PODE / PL', 'dr-furlan', 'luciana-gurgel', '30002530014', '30002530015', 'ANTONIO PAULO DE OLIVEIRA FURLAN', 'DR. FURLAN', 'PSD', 'LUCIANA ARAUJO GOES GURGEL', 'LUCIANA GURGEL', 'PL', '[]'::jsonb),
  ('2026:BA:antonio-carlos-peixoto-de-magalhaes-neto', '6259', '2026-10-04', 'BA', 'Governador', '50001800154', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / PODE / PL / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA) / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE) / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', 'acm-neto', 'ze-coca', '50002533190', '50002533189', 'ANTONIO CARLOS PEIXOTO DE MAGALHÃES NETO', 'ACM NETO', 'UNIÃO', 'ZENILDO BRANDÃO SANTANA', 'ZÉ COCÁ', 'PP', '[]'::jsonb),
  ('2026:BA:ariel-da-silva-capistrano', '6259', '2026-10-04', 'BA', 'Governador', '50001800206', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'DC', 'ariel-capistrano', NULL, '50002535253', NULL, 'ARIEL DA SILVA CAPISTRANO', 'ARIEL CAPISTRANO', 'DC', 'JOSE AUGUSTO MACIEL TORRES', 'ZÉ AUGUSTO', 'DC', '[]'::jsonb),
  ('2026:BA:aroldo-felix-de-azevedo-junior', '6259', '2026-10-04', 'BA', 'Governador', '50001800741', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', 'aroldo-felix', NULL, '50002544692', NULL, 'AROLDO FELIX DE AZEVEDO JUNIOR', 'AROLDO FELIX', 'UP', 'MARILIA REGINA SANTANA DOS SANTOS', 'MARILIA DO MLB', 'UP', '[]'::jsonb),
  ('2026:BA:jose-estevao-dos-santos-barbosa', '6259', '2026-10-04', 'BA', 'Governador', '50001800245', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'DC', 'jose-estevao', NULL, '50002536579', NULL, 'JOSE ESTEVAO DOS SANTOS BARBOSA', 'ESTÊVÃO', 'DC', 'NEUZIMAR MARQUES CAMACAM DÍAZ MORALES', 'NEUZIMAR CAMACAM', 'DC', '[]'::jsonb),
  ('2026:BA:jeronimo-rodrigues-souza', '6259', '2026-10-04', 'BA', 'Governador', '50001800259', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / MDB / PSB / PSD / AVANTE / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV)', 'jeronimo', NULL, '50002536314', NULL, 'JERONIMO RODRIGUES SOUZA', 'JERÔNIMO RODRIGUES', 'PT', 'GERALDO ALVES FERREIRA JUNIOR', 'GERALDO JÚNIOR', 'MDB', '[]'::jsonb),
  ('2026:BA:ronaldo-mansur-santos-silva', '6259', '2026-10-04', 'BA', 'Governador', '50001799963', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'ronaldo-mansur', 'prof-meire-reis', '50002532269', '50002532270', 'RONALDO MANSUR SANTOS SILVA', 'RONALDO MANSUR', 'PSOL', 'MEIRE LUCIA ALVES DOS REIS', 'PROF. MEIRE REIS', 'PSOL', '[]'::jsonb),
  ('2026:CE:ciro-ferreira-gomes', '6259', '2026-10-04', 'CE', 'Governador', '60001800087', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PL / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA) / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP) / DC / AVANTE', 'ciro-gomes-gov-ce', 'roberto-claudio', '60002531351', '60002531352', 'CIRO FERREIRA GOMES', 'CIRO GOMES', 'PSDB', 'ROBERTO CLAUDIO RODRIGUES BEZERRA', 'ROBERTO CLAUDIO', 'UNIÃO', '[]'::jsonb),
  ('2026:CE:huggo-leonardo-de-lima-anastacio', '6259', '2026-10-04', 'CE', 'Governador', '60001800520', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MISSÃO', NULL, NULL, NULL, NULL, 'HUGGO LEONARDO DE LIMA ANASTACIO', 'DELEGADO HUGGO', 'MISSÃO', 'FELIPE SILVA MOREIRA', 'FELIPE MOREIRA', 'MISSÃO', '[]'::jsonb),
  ('2026:CE:elmano-de-freitas-da-costa', '6259', '2026-10-04', 'CE', 'Governador', '60001800686', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PSB / PDT / PODE / MOBILIZA / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV) / REPUBLICANOS / PSD / MDB / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE) / FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'elmano-de-freitas', NULL, '60002543969', NULL, 'ELMANO DE FREITAS DA COSTA', 'ELMANO DE FREITAS', 'PT', 'GABRIELLA PEQUENO COSTA GOMES DE AGUIAR', 'GABRIELLA AGUIAR', 'PSD', '[]'::jsonb),
  ('2026:CE:pedro-felipe-pinheiro-brito', '6259', '2026-10-04', 'CE', 'Governador', '60001800513', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'NOVO', 'pedro-brito', NULL, '60002540336', NULL, 'PEDRO FELIPE PINHEIRO BRITO', 'PEDRO BRITO', 'NOVO', 'VERA LUCIA DA SILVA', 'VERA LÚCIA', 'NOVO', '[]'::jsonb),
  ('2026:CE:serley-de-souza-leal', '6259', '2026-10-04', 'CE', 'Governador', '60001800188', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', NULL, 'catherine-teles', NULL, '60002533730', 'SERLEY DE SOUZA LEAL', 'SERLEY LEAL', 'UP', 'CATHERINE MORAIS TELES', 'CATHERINE TELES', 'UP', '[]'::jsonb),
  ('2026:CE:jose-batista-neto', '6259', '2026-10-04', 'CE', 'Governador', '60001801046', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'ze-batista', NULL, '60002549967', NULL, 'JOSE BATISTA NETO', 'ZÉ BATISTA', 'PSTU', 'MARIA IVONETE FERREIRA FELIX', 'IVONETE', 'PSTU', '[]'::jsonb),
  ('2026:DF:francisco-queiroz-caputo-neto', '6259', '2026-10-04', 'DF', 'Governador', '70001800901', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'NOVO', NULL, NULL, NULL, NULL, 'FRANCISCO QUEIROZ CAPUTO NETO', 'KIKO CAPUTO', 'NOVO', 'RAFAEL DE SA SAMPAIO', 'RAFAEL SAMPAIO', 'NOVO', '[]'::jsonb),
  ('2026:DF:robson-raymundo-da-silva', '6259', '2026-10-04', 'DF', 'Governador', '70001800218', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'robson-raymundo', NULL, '70002535930', NULL, 'ROBSON RAYMUNDO DA SILVA', 'PROFESSOR ROBSON', 'PSTU', 'ANTONIO RICARDO MARTINS GUILLEN', 'GUILLEN', 'PSTU', '[]'::jsonb),
  ('2026:DF:samara-mineiro-oliveira', '6259', '2026-10-04', 'DF', 'Governador', '70001800354', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', 'samara-mineiro', NULL, '70002537111', NULL, 'SAMARA MINEIRO OLIVEIRA', 'PROFESSORA SAMARA MINEIRO', 'UP', 'THAIS OLIVEIRA SILVA', 'THAÍS OLIVEIRA', 'UP', '[]'::jsonb),
  ('2026:ES:breno-augusto-fagundes-barcelos', '6259', '2026-10-04', 'ES', 'Governador', '80001800540', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MISSÃO', NULL, NULL, NULL, NULL, 'BRENO AUGUSTO FAGUNDES BARCELOS', 'BRENO BARCELOS', 'MISSÃO', 'VICTOR RICARDO DE OLIVEIRA', 'VICTOR OLIVEIRA', 'MISSÃO', '[]'::jsonb),
  ('2026:GO:daniel-elias-carvalho-vilela', '6259', '2026-10-04', 'GO', 'Governador', '90001800536', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / MDB / PODE / MOBILIZA / DEMOCRATA / AGIR / PSD / AVANTE / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE) / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', 'daniel-vilela', NULL, '90002540993', NULL, 'DANIEL ELIAS CARVALHO VILELA', 'DANIEL VILELA', 'MDB', 'LUIZ CARLOS DO CARMO', 'LUIZ DO CARMO', 'PSD', '[]'::jsonb),
  ('2026:GO:luis-cesar-bueno-e-freitas', '6259', '2026-10-04', 'GO', 'Governador', '90001800791', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / PSB / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV) / FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'luis-cesar-bueno', NULL, '90002545476', NULL, 'LUIS CESAR BUENO E FREITAS', 'LUIS CESAR BUENO', 'PT', 'CARLOS GOMES CAVALCANTE MUNDIM', 'CARLOS MUNDIM', 'PDT', '[]'::jsonb),
  ('2026:GO:marconi-ferreira-perillo-junior', '6259', '2026-10-04', 'GO', 'Governador', '90001800640', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'DC / PRTB / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA)', 'marconi-perillo', NULL, '90002543463', NULL, 'MARCONI FERREIRA PERILLO JUNIOR', 'MARCONI PERILLO', 'PSDB', 'JACQUELINE FREITAS NASCIMENTO ZAIDEN', 'JACQUELINE ZAIDEN', 'PSDB', '[]'::jsonb),
  ('2026:MA:andre-luis-caetano-dos-santos', '6259', '2026-10-04', 'MA', 'Governador', '100001800702', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MISSÃO', NULL, NULL, NULL, NULL, 'ANDRÉ LUÍS CAETANO DOS SANTOS', 'ANDRÉ LUIS', 'MISSÃO', 'CARLOS EDUARDO SOUSA AGUIAR', 'PROF. CADU', 'MISSÃO', '[]'::jsonb),
  ('2026:MA:eduardo-salim-braide', '6259', '2026-10-04', 'MA', 'Governador', '100001800907', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'NOVO / PSD', 'eduardo-braide', NULL, '100002545679', NULL, 'EDUARDO SALIM BRAIDE', 'EDUARDO BRAIDE', 'PSD', 'ELAINE CORTEZ CARNEIRO', 'ELAINE CARNEIRO', 'PSD', '[]'::jsonb),
  ('2026:MA:felipe-costa-camarao', '6259', '2026-10-04', 'MA', 'Governador', '100001800619', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV) / PSB / FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'felipe-camarao', NULL, '100002542556', NULL, 'FELIPE COSTA CAMARAO', 'FELIPE CAMARÃO', 'PT', 'RICARDO RODRIGUES DE MATOS', 'RICARDO RODRIGUES', 'PT', '[]'::jsonb),
  ('2026:MA:carlos-orleans-braide-brandao', '6259', '2026-10-04', 'MA', 'Governador', '100001800678', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'MDB / PDT / REPUBLICANOS / PODE / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE)', 'orleans-brandao', NULL, '100002543869', NULL, 'CARLOS ORLEANS BRAIDE BRANDÃO', 'ORLEANS BRANDÃO', 'MDB', 'EDIVALDO DE HOLANDA BRAGA JUNIOR', 'EDIVALDO HOLANDA JUNIOR', 'REPUBLICANOS', '[]'::jsonb),
  ('2026:MA:reginaldo-lima-brauno', '6259', '2026-10-04', 'MA', 'Governador', '100001800701', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PCB', 'reginaldo-lima', NULL, '100002544073', NULL, 'REGINALDO LIMA BRAUNO', 'REGINALDO LIMA', 'PCB', 'BARTOLOMEU MOREIRA', 'BARTOLOMEU', 'PCB', '[]'::jsonb),
  ('2026:MA:saulo-costa-arcangeli', '6259', '2026-10-04', 'MA', 'Governador', '100001800182', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'saulo-arcangeli', 'preta-lu', '100002534190', '100002534191', 'SAULO COSTA ARCANGELI', 'SAULO ARCANGELI', 'PSTU', 'LUCIANA COSTA CORREA', 'PRETA LU', 'PSTU', '[]'::jsonb),
  ('2026:MG:alexandre-kalil', '6259', '2026-10-04', 'MG', 'Governador', '130001800385', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA)', 'alexandre-kalil', NULL, '130002539775', NULL, 'ALEXANDRE KALIL', 'ALEXANDRE KALIL', 'PDT', 'CARLOS EDUARDO VENTURELLI MOSCONI', 'CARLOS MOSCONI', 'PSDB', '[]'::jsonb),
  ('2026:MG:benoni-benjamin-cardoso-mendes', '6259', '2026-10-04', 'MG', 'Governador', '130001800712', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MISSÃO', 'ben-mendes', NULL, '130002544411', NULL, 'BENONI BENJAMIN CARDOSO MENDES', 'BEN MENDES', 'MISSÃO', 'DEIVID FERNANDES DE SOUZA', 'CABO DAVID SOUZA', 'MISSÃO', '[]'::jsonb),
  ('2026:MG:gabriel-sousa-marques-de-azevedo', '6259', '2026-10-04', 'MG', 'Governador', '130001801053', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MDB', NULL, NULL, NULL, NULL, 'GABRIEL SOUSA MARQUES DE AZEVEDO', 'GABRIEL', 'MDB', 'MARIA HELENA DE QUADROS LOPES', 'MARIA HELENA', 'MDB', '[]'::jsonb),
  ('2026:MG:indira-ivanise-xavier', '6259', '2026-10-04', 'MG', 'Governador', '130001800956', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', 'indira-xavier', NULL, '130002547874', NULL, 'INDIRA IVANISE XAVIER', 'INDIRA XAVIER', 'UP', 'RENATO CAMPOS AMARAL', 'RENATO CAMPOS', 'UP', '[]'::jsonb),
  ('2026:MG:mateus-simoes-de-almeida', '6259', '2026-10-04', 'MG', 'Governador', '130001800588', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PSD / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP) / NOVO / AVANTE / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE) / MOBILIZA / DC / AGIR', 'mateus-simoes', NULL, '130002541911', NULL, 'MATEUS SIMÕES DE ALMEIDA', 'MATEUS SIMÕES DE ALMEIDA', 'PSD', 'DANILO DE CASTRO', 'DANILO DE CASTRO', 'UNIÃO', '[]'::jsonb),
  ('2026:MG:tulio-cesar-dias-lopes', '6259', '2026-10-04', 'MG', 'Governador', '130001800710', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PCB', 'tulio-lopes', NULL, '130002544122', NULL, 'TULIO CESAR DIAS LOPES', 'PROFESSOR TÚLIO LOPES', 'PCB', 'WARLEN NUNES DOS SANTOS', 'WARLEN NUNES', 'PCB', '[]'::jsonb),
  ('2026:MG:rafael-ribeiro-de-avila', '6259', '2026-10-04', 'MG', 'Governador', '130001800843', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'rafael-duda', NULL, '130002546802', NULL, 'RAFAEL RIBEIRO DE ÁVILA', 'RAFAEL DUDA', 'PSTU', 'DIANA DE CASSIA SILVA', 'PROF. DIANA DE CÁSSIA', 'PSTU', '[]'::jsonb),
  ('2026:MS:renato-wanderley-gomes', '6259', '2026-10-04', 'MS', 'Governador', '120001801019', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'DC', NULL, NULL, NULL, NULL, 'RENATO WANDERLEY GOMES', 'ECONOMISTA RENATO GOMES', 'DC', 'THIAGO MARTINS DOS SANTOS', 'THIAGO MARTINS', 'DC', '[]'::jsonb),
  ('2026:MS:eduardo-correa-riedel', '6259', '2026-10-04', 'MS', 'Governador', '120001800246', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP) / PL / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA) / PODE / AVANTE / REPUBLICANOS / PSD / MDB', 'eduardo-riedel', NULL, '120002536582', NULL, 'EDUARDO CORREA RIEDEL', 'EDUARDO RIEDEL', 'PP', 'JOSE CARLOS BARBOSA', 'BARBOSINHA', 'REPUBLICANOS', '[]'::jsonb),
  ('2026:MS:fabio-ricardo-trad', '6259', '2026-10-04', 'MS', 'Governador', '120001800491', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / PSB / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV)', 'fabio-trad', NULL, '120002539834', NULL, 'FABIO RICARDO TRAD', 'FÁBIO TRAD', 'PT', 'GILDA MARIA GOMES DOS SANTOS', 'DONA GILDA', 'PT', '[]'::jsonb),
  ('2026:MS:jeferson-jose-bezerra', '6259', '2026-10-04', 'MS', 'Governador', '120001801095', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'AGIR', 'jeferson-bezerra', NULL, '120002550198', NULL, 'JEFERSON JOSE BEZERRA', 'JEFERSON BEZERRA', 'AGIR', 'VALDENIR APARECIDO DUARTE', 'VALDENIR DUARTE', 'AGIR', '[]'::jsonb),
  ('2026:MS:lucien-roberto-garcia-de-rezende', '6259', '2026-10-04', 'MS', 'Governador', '120001799961', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO PSOL REDE(PSOL/REDE)', NULL, 'prof-enfermeira-kaelly', NULL, '120002532256', 'LUCIEN ROBERTO GARCIA DE REZENDE', 'LUCIEN REZENDE', 'PSOL', 'KAELLY VIRGINIA DE OLIVEIRA SARAIVA', 'PROF. ENFERMEIRA KAELLY', 'PSOL', '[]'::jsonb),
  ('2026:MT:natasha-slhessarenko', '6259', '2026-10-04', 'MT', 'Governador', '110001800770', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / PSB / PSD / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV) / FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'natasha-slhessarenko', NULL, '110002544985', NULL, 'NATASHA SLHESSARENKO', 'DOUTORA NATASHA', 'PSD', 'DIOGO PEIXOTO BOTELHO', 'DIOGO BOTELHO', 'PDT', '[]'::jsonb),
  ('2026:MT:rafaell-milas-de-oliveira', '6259', '2026-10-04', 'MT', 'Governador', '110001800682', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MISSÃO', 'rafaell-milas', NULL, '110002543953', NULL, 'RAFAELL MILAS DE OLIVEIRA', 'RAFAELL MILAS', 'MISSÃO', 'THALES RODRIGO SARTORELO', 'THALES SARTORELO', 'MISSÃO', '[]'::jsonb),
  ('2026:PA:araceli-maria-pereira-lemos', '6259', '2026-10-04', 'PA', 'Governador', '140001800602', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'araceli-lemos', NULL, '140002542386', NULL, 'ARACELI MARIA PEREIRA LEMOS', 'ARACELI', 'PSOL', 'MARIA DE FATIMA SANTANA DA SILVA', 'FATIMA SANTANA', 'PSOL', '[]'::jsonb),
  ('2026:PA:jose-cleber-barros-rabelo', '6259', '2026-10-04', 'PA', 'Governador', '140001800402', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'cleber-rabelo', NULL, '140002538631', NULL, 'JOSE CLEBER BARROS RABELO', 'CLEBER RABELO', 'PSTU', 'WELLINGTA JOSYANE SIQUEIRA MACEDO', 'WELL MACEDO', 'PSTU', '[]'::jsonb),
  ('2026:PA:daniel-barbosa-santos', '6259', '2026-10-04', 'PA', 'Governador', '140001801043', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PODE / PL / DC / NOVO / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE)', 'dr-daniel', NULL, '140002549930', NULL, 'DANIEL BARBOSA SANTOS', 'DR. DANIEL', 'PODE', 'ELLAYNE CRISTINA GURGEL DE ALMEIDA', 'ELLAYNE D ALMEIDA', 'PL', '[]'::jsonb),
  ('2026:PB:cicero-de-lucena-filho', '6259', '2026-10-04', 'PB', 'Governador', '150001800704', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'MDB / DEMOCRATA / PSD / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA)', 'cicero-lucena', NULL, '150002544133', NULL, 'CICERO DE LUCENA FILHO', 'CÍCERO LUCENA', 'MDB', 'DIOGO OLIVEIRA CUNHA LIMA', 'DIOGO CUNHA LIMA', 'PSD', '[]'::jsonb),
  ('2026:PB:efraim-de-araujo-morais-filho', '6259', '2026-10-04', 'PB', 'Governador', '150001800409', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PL', 'efraim-filho', NULL, '150002538692', NULL, 'EFRAIM DE ARAUJO MORAIS FILHO', 'EFRAIM FILHO', 'PL', 'NAYANA PONTES PEREIRA GOMES', 'NAYANA PONTES', 'PL', '[]'::jsonb),
  ('2026:PB:yuri-ezequiel-de-lima-silva', '6259', '2026-10-04', 'PB', 'Governador', '150001800507', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', NULL, NULL, NULL, NULL, 'YURI EZEQUIEL DE LIMA SILVA', 'YURI EZEQUIEL', 'UP', 'MARIA DO CARMO LOURENÇO', 'CARMINHA LOURENÇO', 'UP', '[]'::jsonb),
  ('2026:PE:guilherme-fonseca', '6259', '2026-10-04', 'PE', 'Governador', '170001800243', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'guilherme-fonseca', NULL, '170002536575', NULL, 'GUILHERME FONSECA', 'GUILHERME FONSECA', 'PSTU', 'VALÉRIA DO NASCIMENTO FELIX', 'VALÉRIA FÉLIX', 'PSTU', '[]'::jsonb),
  ('2026:PE:ivan-vasconcellos-de-moraes-filho', '6259', '2026-10-04', 'PE', 'Governador', '170001800371', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PCB / FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'ivan-moraes', NULL, '170002538097', NULL, 'IVAN VASCONCELLOS DE MORAES FILHO', 'IVAN MORAES', 'PSOL', 'ALICE DOS SANTOS GABINO', 'ALICE GABINO', 'REDE', '[]'::jsonb),
  ('2026:PE:joao-henrique-de-andrade-lima-campos', '6259', '2026-10-04', 'PE', 'Governador', '170001800295', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / PDT / MDB / PSB / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV) / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE)', 'joao-campos', NULL, '170002537230', NULL, 'JOÃO HENRIQUE DE ANDRADE LIMA CAMPOS', 'JOÃO CAMPOS', 'PSB', 'CARLOS ANTONIO DA COSTA CAVALCANTI NETO', 'CARLOS COSTA', 'REPUBLICANOS', '[]'::jsonb),
  ('2026:PE:jeremias-cosmo-silva-dos-santos', '6259', '2026-10-04', 'PE', 'Governador', '170001800550', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'DEMOCRATA', 'jeremias-cosmo', NULL, '170002541258', NULL, 'JEREMIAS COSMO SILVA DOS SANTOS', 'PROFESSOR JEREMIAS DO BANCO', 'DEMOCRATA', 'CARLOS ALBERTO DE BRITO JUNIOR', 'CARLOS ALBERTO', 'DEMOCRATA', '[]'::jsonb),
  ('2026:PE:maria-camila-da-silva-falcao', '6259', '2026-10-04', 'PE', 'Governador', '170001800301', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', NULL, NULL, NULL, NULL, 'MARIA CAMILA DA SILVA FALCÃO', 'PROFESSORA CAMILA', 'UP', 'MARCELO PESSOA DA SILVA', 'MARCELO PESSOA', 'UP', '[]'::jsonb),
  ('2026:PE:raquel-teixeira-lyra-lucena', '6259', '2026-10-04', 'PE', 'Governador', '170001800294', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PODE / PSD / AVANTE / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA) / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', 'raquel-lyra', NULL, '170002537227', NULL, 'RAQUEL TEIXEIRA LYRA LUCENA', 'RAQUEL LYRA', 'PSD', 'PRISCILA KRAUSE BRANCO', 'PRISCILA KRAUSE', 'PSD', '[]'::jsonb),
  ('2026:PE:renan-lucio-sant-anna-hallais', '6259', '2026-10-04', 'PE', 'Governador', '170001800514', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MISSÃO', NULL, NULL, NULL, NULL, 'RENAN LUCIO SANT ANNA HALLAIS', 'RENAN', 'MISSÃO', 'LUCAS XAVIER BEZERRA DOS SANTOS', 'LUCAS XAVIER', 'MISSÃO', '[]'::jsonb),
  ('2026:PI:lucia-maria-de-sousa-aguiar-dos-santos', '6259', '2026-10-04', 'PI', 'Governador', '180001800751', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA)', 'lucia-santos', NULL, '180002544216', NULL, 'LÚCIA MARIA DE SOUSA AGUIAR DOS SANTOS', 'DRA. LÚCIA SANTOS', 'PSDB', 'PAULO EUDES CARNEIRO', 'DR. PAULO EUDES', 'PSDB', '[]'::jsonb),
  ('2026:PI:elizeu-morais-de-aguiar', '6259', '2026-10-04', 'PI', 'Governador', NULL, 'duplicidade_oficial', 'duplicidade_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'NOVO', NULL, NULL, NULL, NULL, 'ELIZEU MORAIS DE AGUIAR', 'ELIZEU AGUIAR', 'NOVO', 'ISMAR AGUIAR MARQUES', 'ISMAR MARQUES', 'NOVO', '[{"sq_coligacao":"180001800158","titular_sq_candidato":"180002533958","vice_sq_candidato":"180002533957"},{"sq_coligacao":"180001801041","titular_sq_candidato":"180002549920","vice_sq_candidato":"180002549919"}]'::jsonb),
  ('2026:PI:geraldo-do-nascimento-carvalho', '6259', '2026-10-04', 'PI', 'Governador', '180001800360', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'geraldo-carvalho', NULL, '180002537422', NULL, 'GERALDO DO NASCIMENTO CARVALHO', 'GERALDO CARVALHO', 'PSTU', 'JOÃO GERVÁSIO DOS SANTOS NETO', 'GERVÁSIO SANTOS', 'PSTU', '[]'::jsonb),
  ('2026:PI:gustavo-henrique-leite-feijo', '6259', '2026-10-04', 'PI', 'Governador', '180001801079', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'AVANTE', 'gustavo-henrique', NULL, '180002550421', NULL, 'GUSTAVO HENRIQUE LEITE FEIJÓ', 'GUSTAVO PELO PIAUÍ OU GUSTAVO', 'AVANTE', 'LUCAS VERAS DE MORAES', 'LUCAS VERAS DE MORAES', 'AVANTE', '[]'::jsonb),
  ('2026:PI:joel-rodrigues-da-silva', '6259', '2026-10-04', 'PI', 'Governador', '180001800399', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PODE / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE) / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP) / PL', 'joel-rodrigues', NULL, '180002538530', NULL, 'JOEL RODRIGUES DA SILVA', 'JOEL RODRIGUES', 'PP', 'JEOVA BARBOSA DE CARVALHO ALENCAR', 'JEOVÁ ALENCAR', 'UNIÃO', '[]'::jsonb),
  ('2026:PI:gisvaldo-oliveira-da-silva', '6259', '2026-10-04', 'PI', 'Governador', '180001801067', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO PSOL REDE(PSOL/REDE)', NULL, NULL, NULL, NULL, 'GISVALDO OLIVEIRA DA SILVA', 'PROFESSOR GISVALDO', 'PSOL', 'FRANCISCA EDILENE PINHO GOMES BARBOSA', 'EDILENE PINHO', 'PSOL', '[]'::jsonb),
  ('2026:PI:francisco-jose-martins-jurity', '6259', '2026-10-04', 'PI', 'Governador', '180001800923', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'DC', NULL, NULL, NULL, NULL, 'FRANCISCO JOSÉ MARTINS JURITY', 'PROFESSOR JURITY', 'DC', 'PEDRO PEREIRA DOS SANTOS FILHO', 'PEDRO PEREIRA', 'DC', '[]'::jsonb),
  ('2026:PI:rafael-tajra-fonteles', '6259', '2026-10-04', 'PI', 'Governador', '180001800103', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / PDT / MDB / PSD / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV)', 'rafael-fonteles', 'washington-bandeira', '180002532987', '180002532986', 'RAFAEL TAJRA FONTELES', 'RAFAEL FONTELES', 'PT', 'FRANCISCO WASHINGTON BANDEIRA SANTOS FILHO', 'WASHINGTON BANDEIRA', 'PT', '[]'::jsonb),
  ('2026:PI:ravenna-de-castro-lima-azevedo', '6259', '2026-10-04', 'PI', 'Governador', '180001800937', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'DEMOCRATA', 'ravenna-castro', NULL, '180002548388', NULL, 'RAVENNA DE CASTRO LIMA AZEVEDO', 'RAVENNA DA INCLUSÃO', 'DEMOCRATA', 'JOÃO RICARDO SOARES DA SILVA', 'JOÃO RICARDO', 'DEMOCRATA', '[]'::jsonb),
  ('2026:PI:jose-santiago-belizario', '6259', '2026-10-04', 'PI', 'Governador', '180001801070', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', 'santiago-belizario', NULL, '180002549995', NULL, 'JOSÉ SANTIAGO BELIZÁRIO', 'SANTIAGO BELIZÁRIO', 'UP', 'THAYS DIAS DE MORAIS', 'THAYS DIAS', 'UP', '[]'::jsonb),
  ('2026:PR:alexandre-salomao', '6259', '2026-10-04', 'PR', 'Governador', '160001800891', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MOBILIZA', 'alexandre-salomao', NULL, '160002547594', NULL, 'ALEXANDRE SALOMAO', 'ALEXANDRE SALOMÃO', 'MOBILIZA', 'DAIANA DA SILVA CRIMINACIO', 'DAIANA CRIMINACIO', 'MOBILIZA', '[]'::jsonb),
  ('2026:PR:mauricio-thadeu-de-mello-e-silva', '6259', '2026-10-04', 'PR', 'Governador', '160001800896', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV) / FEDERAÇÃO PSOL REDE(PSOL/REDE) / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE)', 'requiao-filho', NULL, '160002547666', NULL, 'MAURICIO THADEU DE MELLO E SILVA', 'REQUIÃO FILHO', 'PDT', 'MICHELE CAPUTO NETO', 'MICHELE CAPUTO', 'SOLIDARIEDADE', '[]'::jsonb),
  ('2026:PR:samuel-de-mattos-figueiredo', '6259', '2026-10-04', 'PR', 'Governador', '160001800881', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'samuel-de-mattos', NULL, '160002548010', NULL, 'SAMUEL DE MATTOS FIGUEIREDO', 'SAMUEL DE MATTOS', 'PSTU', 'HELENA FIGUEIREDO DA COSTA', 'HELENA FIGUEIREDO', 'PSTU', '[]'::jsonb),
  ('2026:PR:sandro-alex-cruz-de-oliveira', '6259', '2026-10-04', 'PR', 'Governador', '160001801051', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / MDB / DEMOCRATA / PSD / AVANTE / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA) / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', 'sandro-alex', 'rafael-greca', '160002549553', '160002549552', 'SANDRO ALEX CRUZ DE OLIVEIRA', 'SANDRO ALEX', 'PSD', 'RAFAEL VALDOMIRO GRECA DE MACEDO', 'RAFAEL GRECA', 'MDB', '[]'::jsonb),
  ('2026:PR:sergio-fernando-moro', '6259', '2026-10-04', 'PR', 'Governador', '160001800506', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PODE / PL / NOVO', 'sergio-moro-gov-pr', NULL, '160002540833', NULL, 'SERGIO FERNANDO MORO', 'SERGIO MORO', 'PL', 'EDSON JOSE DE VASCONCELOS', 'EDSON VASCONCELOS', 'PL', '[]'::jsonb),
  ('2026:RJ:andre-bourguignon-marinho', '6259', '2026-10-04', 'RJ', 'Governador', '190001800365', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'NOVO', 'andre-marinho', NULL, '190002537524', NULL, 'ANDRÉ BOURGUIGNON MARINHO', 'ANDRÉ MARINHO', 'NOVO', 'ERIGREYCE DE ALCANTARA MONTEIRO', 'TENETE CORONEL ERIGREYCE', 'NOVO', '[]'::jsonb),
  ('2026:RJ:joao-jacques-soares-busnello', '6259', '2026-10-04', 'RJ', 'Governador', '190001800709', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MISSÃO', 'coronel-busnello', NULL, '190002544120', NULL, 'JOÃO JACQUES SOARES BUSNELLO', 'CORONEL BUSNELLO', 'MISSÃO', 'RAFAEL BARROS SILVA DA LUZ', 'RAFA LUZ', 'MISSÃO', '[]'::jsonb),
  ('2026:RJ:cyro-garcia', '6259', '2026-10-04', 'RJ', 'Governador', '190001800425', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'cyro-garcia', NULL, '190002540198', NULL, 'CYRO GARCIA', 'CYRO GARCIA', 'PSTU', 'PERCILIANA COSTA RODRIGUES', 'PERCILIANA', 'PSTU', '[]'::jsonb),
  ('2026:RJ:douglas-ruas-dos-santos', '6259', '2026-10-04', 'RJ', 'Governador', '190001800632', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PL / MOBILIZA / AGIR / AVANTE', 'douglas-ruas', NULL, '190002542887', NULL, 'DOUGLAS RUAS DOS SANTOS', 'DOUGLAS RUAS', 'PL', 'FERNANDA ANCHIETA LOUBACK', 'FERNANDA LOUBACK', 'PL', '[]'::jsonb),
  ('2026:RJ:eduardo-da-costa-paes', '6259', '2026-10-04', 'RJ', 'Governador', '190001800636', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / MDB / DC / PSB / PSD / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA) / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV) / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE)', 'eduardo-paes', NULL, '190002543380', NULL, 'EDUARDO DA COSTA PAES', 'EDUARDO PAES', 'PSD', 'JEANNIE MAYR REIS DE OLIVEIRA', 'JANE REIS', 'MDB', '[]'::jsonb),
  ('2026:RJ:anthony-william-garotinho-matheus-de-oliveira', '6259', '2026-10-04', 'RJ', 'Governador', '190001801094', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / DEMOCRATA', 'garotinho', NULL, '190002550196', NULL, 'ANTHONY WILLIAM GAROTINHO MATHEUS DE OLIVEIRA', 'GAROTINHO', 'REPUBLICANOS', 'ELAINE CRISTINA GONÇALVES NOGAROL DE ANDRADE', 'MAJOR ELAINE', 'DEMOCRATA', '[]'::jsonb),
  ('2026:RJ:juliete-pantoja-alves', '6259', '2026-10-04', 'RJ', 'Governador', '190001800867', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', 'juliete-pantoja', NULL, '190002547272', NULL, 'JULIETE PANTOJA ALVES', 'JULIETE', 'UP', 'MEIBY JEANINE MARTINS LIMA', 'BIA MARTINS', 'UP', '[]'::jsonb),
  ('2026:RJ:william-carlos-brum-bispo', '6259', '2026-10-04', 'RJ', 'Governador', '190001800282', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'william-siri', NULL, '190002536162', NULL, 'WILLIAM CARLOS BRUM BISPO', 'WILLIAM SIRI', 'PSOL', 'JULIANA PEREIRA DE CARVALHO', 'JULIANA CARVALHO', 'PSOL', '[]'::jsonb),
  ('2026:RN:allyson-leandro-bezerra-silva', '6259', '2026-10-04', 'RN', 'Governador', '200001800267', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / MDB / PSD / AVANTE / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE) / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', 'alysson-bezerra', NULL, '200002535255', NULL, 'ALLYSON LEANDRO BEZERRA SILVA', 'ALLYSON', 'UNIÃO', 'HERMANO DA COSTA MORAES', 'HERMANO MORAIS', 'MDB', '[]'::jsonb),
  ('2026:RN:arinalda-vasconcelos-de-medeiros', '6259', '2026-10-04', 'RN', 'Governador', '200001800947', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', 'arinalda-do-mlb', 'francisco-dias', '200002547826', '200002547827', 'ARINALDA VASCONCELOS DE MEDEIROS', 'ARINALDA DO MLB', 'UP', 'FRANCISCO DE ASSIS DA COSTA DIAS', 'FRANCISCO DIAS', 'UP', '[]'::jsonb),
  ('2026:RN:carlos-eduardo-xavier', '6259', '2026-10-04', 'RN', 'Governador', '200001800178', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / PSB / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV)', NULL, 'larissa-rosado', NULL, '200002534002', 'CARLOS EDUARDO XAVIER', 'CADU DE LULA', 'PT', 'LARISSA DANIELA ESCOSSIA ROSADO', 'LARISSA', 'PSB', '[]'::jsonb),
  ('2026:RN:dario-barbosa-de-melo', '6259', '2026-10-04', 'RN', 'Governador', '200001800610', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'dario-barbosa', NULL, '200002542481', NULL, 'DARIO BARBOSA DE MELO', 'DÁRIO BARBOSA', 'PSTU', 'FERNANDA LOURENA PEREIRA SOARES', 'FERNANDA SOARES', 'PSTU', '[]'::jsonb),
  ('2026:RN:roberio-paulino-rodrigues', '6259', '2026-10-04', 'RN', 'Governador', '200001800837', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'roberio-paulino', NULL, '200002546757', NULL, 'ROBERIO PAULINO RODRIGUES', 'PROFESSOR ROBERIO PAULINO', 'PSOL', 'LENY MACIEL GRILO', 'LENNY GRILO', 'PSOL', '[]'::jsonb),
  ('2026:RN:karlo-rodrigo-lucio-vieira', '6259', '2026-10-04', 'RN', 'Governador', '200001800836', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'AGIR', 'rodrigo-bolsonaro', NULL, '200002546756', NULL, 'KARLO RODRIGO LUCIO VIEIRA', 'RODRIGO BOLSONARO', 'AGIR', 'MARIA SOCORRO BATISTA DE MACEDO', 'SOCORRO BATISTA', 'AGIR', '[]'::jsonb),
  ('2026:RN:alvaro-costa-dias', '6259', '2026-10-04', 'RN', 'Governador', '200001800163', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PODE / PL / NOVO / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA)', 'alvaro-dias-rn', 'baba', '200002534442', '200002534441', 'ÁLVARO COSTA DIAS', 'ÁLVARO DIAS', 'PL', 'ANTEOMAR PEREIRA DA SILVA', 'BABÁ', 'PL', '[]'::jsonb),
  ('2026:RO:adailton-antunes-ferreira', '6259', '2026-10-04', 'RO', 'Governador', '220001800312', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PSD / AVANTE / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE)', NULL, NULL, NULL, NULL, 'ADAILTON ANTUNES FERREIRA', 'ADAILTON FURIA', 'PSD', 'EVERTON LEONI', 'EVERTON LEONI', 'PSD', '[]'::jsonb),
  ('2026:RO:expedito-goncalves-ferreira-netto', '6259', '2026-10-04', 'RO', 'Governador', '220001800564', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV) / FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'expedito-netto', 'luiz-carlos-teodoro', '220002542185', '220002542186', 'EXPEDITO GONCALVES FERREIRA NETTO', 'EXPEDITO NETTO', 'PT', 'LUIZ CARLOS TEODORO', 'DR, LUIZ TEODORO', 'PSOL', '[]'::jsonb),
  ('2026:RO:hildon-de-lima-chaves', '6259', '2026-10-04', 'RO', 'Governador', '220001800687', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', 'hildon-chaves', NULL, '220002542916', NULL, 'HILDON DE LIMA CHAVES', 'HILDON CHAVES', 'UNIÃO', 'ELCIRONE MOREIRA DEIRO', 'CIRONE DEIRÓ', 'UNIÃO', '[]'::jsonb),
  ('2026:RO:marcos-rogerio-da-silva-brito', '6259', '2026-10-04', 'RO', 'Governador', '220001800593', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PODE / PL / DC / NOVO / MOBILIZA', 'marcos-rogerio', NULL, '220002541939', NULL, 'MARCOS ROGERIO DA SILVA BRITO', 'MARCOS ROGÉRIO', 'PL', 'RODRIGO CAMARGO RIBEIRO PINHO', 'RODRIGO CAMARGO', 'PODE', '[]'::jsonb),
  ('2026:RR:arthur-henrique-brandao-machado', '6259', '2026-10-04', 'RR', 'Governador', '230001800997', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PL / NOVO', 'arthur-henrique', NULL, '230002549223', NULL, 'ARTHUR HENRIQUE BRANDAO MACHADO', 'ARTHUR HENRIQUE', 'PL', 'HAROLDO ALVES CAMPOS', 'HAROLDO CATHEDRAL', 'NOVO', '[]'::jsonb),
  ('2026:RR:farah-mesquita', '6259', '2026-10-04', 'RR', 'Governador', '230001801001', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE)', 'farah-mesquita', NULL, '230002549294', NULL, 'FARAH MESQUITA', 'FARAH MESQUITA', 'SOLIDARIEDADE', 'MARIA NATALIA SOUSA CIPRIANO', 'NATÁLIA WAKIRI', 'SOLIDARIEDADE', '[]'::jsonb),
  ('2026:RS:gabriel-vieira-de-souza', '6259', '2026-10-04', 'RS', 'Governador', '210001800634', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'MDB / AGIR / PSD / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE)', 'gabriel-souza', NULL, '210002542892', NULL, 'GABRIEL VIEIRA DE SOUZA', 'GABRIEL SOUZA', 'MDB', 'ERNANI POLO', 'ERNANI POLO', 'PSD', '[]'::jsonb),
  ('2026:RS:marcelo-maranata-soares-reinaldo', '6259', '2026-10-04', 'RS', 'Governador', '210001800241', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA)', 'marcelo-maranata', NULL, '210002535802', NULL, 'MARCELO MARANATA SOARES REINALDO', 'MARCELO MARANATA', 'PSDB', 'CLAUDIO CASTANHEIRA DIAZ', 'CLAUDIO DIAZ', 'PSDB', '[]'::jsonb),
  ('2026:RS:priscila-voigt-severiano', '6259', '2026-10-04', 'RS', 'Governador', '210001800140', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', 'priscila-voigt', 'naf-nascimento', '210002533355', '210002533354', 'PRISCILA VOIGT SEVERIANO', 'PRISCILA VOIGT', 'UP', 'NAFTALY PEREIRA DO NASCIMENTO', 'NAF NASCIMENTO', 'UP', '[]'::jsonb),
  ('2026:RS:rejane-silva-de-oliveira', '6259', '2026-10-04', 'RS', 'Governador', '210001800478', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'rejane-oliveira', NULL, '210002541367', NULL, 'REJANE SILVA DE OLIVEIRA', 'REJANE DE OLIVEIRA', 'PSTU', 'ADÃO ALBERTO TEIXEIRA LIMA', 'ADÃO LIMA', 'PSTU', '[]'::jsonb),
  ('2026:RS:luciano-lorenzini-zucco', '6259', '2026-10-04', 'RS', 'Governador', '210001800953', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / PODE / PL / DC / NOVO / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', 'luciano-zucco', NULL, '210002547857', NULL, 'LUCIANO LORENZINI ZUCCO', 'ZUCCO', 'PL', 'SILVANA MARIA FRANCISCATTO COVATTI', 'SILVANA COVATTI', 'PP', '[]'::jsonb),
  ('2026:SC:gelson-luiz-merisio', '6259', '2026-10-04', 'SC', 'Governador', '240001800990', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / PSB / FEDERAÇÃO PSOL REDE(PSOL/REDE) / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV)', 'gelson-merisio', NULL, '240002548628', NULL, 'GELSON LUIZ MERISIO', 'GELSON MERÍSIO', 'PSB', 'ANGELA ALBINO', 'ANGELA ALBINO', 'PDT', '[]'::jsonb),
  ('2026:SC:jorginho-dos-santos-mello', '6259', '2026-10-04', 'SC', 'Governador', '240001800349', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'AVANTE / AGIR / DC / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA) / NOVO / REPUBLICANOS / PODE / PL', 'jorginho-mello', NULL, '240002537073', NULL, 'JORGINHO DOS SANTOS MELLO', 'JORGINHO MELLO', 'PL', 'ADRIANO BORNSCHEIN SILVA', 'ADRIANO SILVA', 'NOVO', '[]'::jsonb),
  ('2026:SC:lais-paganelli-chaud', '6259', '2026-10-04', 'SC', 'Governador', '240001801062', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', NULL, NULL, NULL, NULL, 'LAÍS PAGANELLI CHAUD', 'LAÍS CHAUD', 'UP', 'NATHÁLIA TARSES GOMES DE MELO', 'NATHÁLIA MELO', 'UP', '[]'::jsonb),
  ('2026:SC:marcelo-marcel-franco-jose-da-silva', '6259', '2026-10-04', 'SC', 'Governador', '240001800708', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'MISSÃO', 'marcelo-brigadeiro', NULL, '240002544118', NULL, 'MARCELO MARCEL FRANCO JOSE DA SILVA', 'MARCELO BRIGADEIRO', 'MISSÃO', 'MARCELO RODRIGUES', 'CORONEL RODRIGUES', 'MISSÃO', '[]'::jsonb),
  ('2026:SC:marcus-alexandre-sodre', '6259', '2026-10-04', 'SC', 'Governador', '240001800589', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'marcus-sodre', NULL, '240002541913', NULL, 'MARCUS ALEXANDRE SODRE', 'PROFESSOR MARCUS SODRÉ', 'PSTU', 'TATIANE PASDIORA', 'PROFESSORA TATY', 'PSTU', '[]'::jsonb),
  ('2026:SE:jose-helton-silva-monteiro', '6259', '2026-10-04', 'SE', 'Governador', '260001800858', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO PSOL REDE(PSOL/REDE)', NULL, NULL, NULL, NULL, 'JOSE HELTON SILVA MONTEIRO', 'DR. HELTON', 'PSOL', 'MARIA IZALTINA SILVA SANTOS', 'IZALTINA QUILOMBOLA', 'PSOL', '[]'::jsonb),
  ('2026:SE:fabio-cruz-mitidieri', '6259', '2026-10-04', 'SE', 'Governador', '260001800613', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PSB / PSD / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP) / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV)', 'fabio-mitidieri', NULL, '260002542491', NULL, 'FABIO CRUZ MITIDIERI', 'FÁBIO', 'PSD', 'JEFERSON LUIZ DE ANDRADE', 'JEFERSON ANDRADE', 'PSD', '[]'::jsonb),
  ('2026:SE:jose-ricardo-marques-dos-santos', '6259', '2026-10-04', 'SE', 'Governador', '260001800984', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PODE / PL / NOVO', 'ricardo-marques', NULL, '260002549466', NULL, 'JOSE RICARDO MARQUES DOS SANTOS', 'RICARDO MARQUES', 'PL', 'SALETE FERNANDES DA SILVA', 'PASTORA SALETE', 'PL', '[]'::jsonb),
  ('2026:SE:valmir-dos-santos-costa', '6259', '2026-10-04', 'SE', 'Governador', '260001800085', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / AVANTE', 'valmir-de-francisquinho', 'priscila-felizola', '260002532010', '260002532011', 'VALMIR DOS SANTOS COSTA', 'VALMIR DE FRANCISQUINHO', 'REPUBLICANOS', 'PRISCILA DIAS SILVA FELIZOLA', 'PRISCILA FELIZOLA', 'REPUBLICANOS', '[]'::jsonb),
  ('2026:SP:fernando-haddad', '6259', '2026-10-04', 'SP', 'Governador', '250001801022', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / PSB / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV) / FEDERAÇÃO PSOL REDE(PSOL/REDE)', 'haddad-gov-sp', 'marcio-franca', '250002549705', '250002549704', 'FERNANDO HADDAD', 'FERNANDO HADDAD', 'PT', 'MARCIO LUIZ FRANÇA GOMES', 'MÁRCIO FRANÇA', 'PSB', '[]'::jsonb),
  ('2026:SP:edjane-lima-de-sousa', '6259', '2026-10-04', 'SP', 'Governador', '250001800968', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'AGIR', 'policial-edjane', NULL, '250002548080', NULL, 'EDJANE LIMA DE SOUSA', 'POLICIAL EDJANE', 'AGIR', 'RENATA CRISTINA TEDESQUE BOLSONARO', 'RENATA BOLSONARO', 'AGIR', '[]'::jsonb),
  ('2026:SP:tarcisio-gomes-de-freitas', '6259', '2026-10-04', 'SP', 'Governador', '250001800554', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / PL / MDB / DEMOCRATA / AVANTE / PSD / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE) / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', 'tarcisio-gov-sp', 'felicio-ramuth', '250002541303', '250002541302', 'TARCISIO GOMES DE FREITAS', 'TARCÍSIO', 'REPUBLICANOS', 'FELICIO RAMUTH', 'FELICIO RAMUTH', 'MDB', '[]'::jsonb),
  ('2026:SP:vera-lucia-pereira-da-silva-salgado', '6259', '2026-10-04', 'SP', 'Governador', '250001800332', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'PSTU', 'vera-lucia', NULL, '250002536915', NULL, 'VERA LÚCIA PEREIRA DA SILVA SALGADO', 'VERA LÚCIA', 'PSTU', 'RENATA LONGATTI FRANÇA', 'RENATA FRANÇA', 'PSTU', '[]'::jsonb),
  ('2026:SP:vivian-mendes-da-silva', '6259', '2026-10-04', 'SP', 'Governador', '250001800766', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'UP', 'vivian-mendes', NULL, '250002544912', NULL, 'VIVIAN MENDES DA SILVA', 'VIVIAN MENDES', 'UP', 'MARCELO PEREIRA DE AZEVEDO', 'MARCELO PEREIRA', 'UP', '[]'::jsonb),
  ('2026:TO:ataides-de-oliveira', '6259', '2026-10-04', 'TO', 'Governador', '270001800913', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'NOVO', 'ataides-oliveira', NULL, '270002548412', NULL, 'ATAIDES DE OLIVEIRA', 'ATAIDES DE OLIVEIRA', 'NOVO', 'ROSILEIA DIAS CARNEIRO', 'ROSILEIA DIAS CARNEIRO', 'NOVO', '[]'::jsonb),
  ('2026:TO:ivaildo-pereira-da-cruz', '6259', '2026-10-04', 'TO', 'Governador', '270001801082', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'DC', 'du-pereira', NULL, '270002550458', NULL, 'IVAILDO PEREIRA DA CRUZ', 'DU PEREIRA', 'DC', 'SILVINO VITOR PERES DE SANTANA', 'SILVINO VITOR', 'DC', '[]'::jsonb),
  ('2026:TO:laurez-da-rocha-moreira', '6259', '2026-10-04', 'TO', 'Governador', '270001800720', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'PDT / PSB / PSD / FEDERAÇÃO BRASIL DA ESPERANÇA - FE BRASIL(PT/PC do B/PV)', 'laurez-moreira', NULL, '270002544494', NULL, 'LAUREZ DA ROCHA MOREIRA', 'LAUREZ MOREIRA', 'PSD', 'JULIO MANOEL DA SILVA NETO', 'CORONEL SILVA NETO', 'PSD', '[]'::jsonb),
  ('2026:TO:witer-fonseca-naves', '6259', '2026-10-04', 'TO', 'Governador', '270001800451', 'confirmada', 'revisao_identidade', '#NE', '-3', '-3', 'FEDERAÇÃO', 'FEDERAÇÃO PSOL REDE(PSOL/REDE)', NULL, NULL, NULL, NULL, 'WITER FONSECA NAVES', 'PROF WITER NAVES', 'PSOL', 'MARIA LUCIA SOARES VIANA', 'LÚCIA VIANA', 'PSOL', '[]'::jsonb),
  ('2026:TO:maria-auxiliadora-seabra-rezende', '6259', '2026-10-04', 'TO', 'Governador', '270001800733', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'REPUBLICANOS / PODE / AVANTE / PL / FEDERAÇÃO RENOVAÇÃO SOLIDÁRIA(25-PRD/77-SOLIDARIEDADE) / FEDERAÇÃO UNIÃO PROGRESSISTA(44-UNIÃO/11-PP)', 'professora-dorinha', NULL, '270002544599', NULL, 'MARIA AUXILIADORA SEABRA REZENDE', 'PROFESSORA DORINHA', 'UNIÃO', 'ATOS GOMES DE ARAÚJO', 'ATOS GOMES', 'REPUBLICANOS', '[]'::jsonb),
  ('2026:TO:luiz-carlos-ferreira-da-silva', '6259', '2026-10-04', 'TO', 'Governador', '270001800814', 'confirmada', 'novo_perfil_oficial', '#NE', '-3', '-3', 'PARTIDO ISOLADO', 'DEMOCRATA', 'subtenente-luiz-carlos', NULL, '270002546368', NULL, 'LUIZ CARLOS FERREIRA DA SILVA', 'SUBTENENTE LUIZ CARLOS', 'DEMOCRATA', 'JAIR MEDEIRO DA CUNHA', 'JAIR MEDEIROS', 'DEMOCRATA', '[]'::jsonb),
  ('2026:TO:vicente-alves-de-oliveira-junior', '6259', '2026-10-04', 'TO', 'Governador', '270001800725', 'confirmada', 'confirmado', '#NE', '-3', '-3', 'COLIGAÇÃO', 'MDB / FEDERAÇÃO PSDB CIDADANIA(PSDB/CIDADANIA)', 'vicentinho-junior', 'amelio-cayres', '270002544544', '270002544545', 'VICENTE ALVES DE OLIVEIRA JÚNIOR', 'VICENTINHO JÚNIOR', 'PSDB', 'AMELIO CAYRES DE ALMEIDA', 'AMÉLIO CAYRES', 'MDB', '[]'::jsonb)
) AS v(chave,eleicao_codigo,eleicao_data,uf,cargo_titular,sq_coligacao,
       identidade_status,vinculo_titular_status,tse_situacao_codigo,
       tse_situacao_titular_codigo,tse_situacao_vice_codigo,tipo_agremiacao,composicao,
       titular_slug,vice_slug,titular_sq_candidato,vice_sq_candidato,
       titular_nome_completo,titular_nome_urna,titular_partido_sigla,
       vice_nome_completo,vice_nome_urna,vice_partido_sigla,alternativas_oficiais)
LEFT JOIN public.candidatos titular ON titular.slug = v.titular_slug
LEFT JOIN public.candidatos vice ON vice.slug = v.vice_slug
WHERE current_setting('pf.chapas_apply',true)='true';

DO $$
DECLARE total integer; confirmadas integer; duplicadas integer; vinculadas integer; revisoes integer;
BEGIN
  IF current_setting('pf.chapas_apply',true) IS DISTINCT FROM 'true' THEN RETURN; END IF;
  SELECT count(*), count(*) FILTER (WHERE identidade_status='confirmada'),
         count(*) FILTER (WHERE identidade_status='duplicidade_oficial'),
         count(*) FILTER (WHERE titular_candidato_id IS NOT NULL),
         count(*) FILTER (WHERE vinculo_titular_status='revisao_identidade')
    INTO total, confirmadas, duplicadas, vinculadas, revisoes FROM public.chapas_2026;
  IF total <> 134 THEN RAISE EXCEPTION 'esperava 134 chapas, encontrou %', total; END IF;
  IF confirmadas <> 133 THEN RAISE EXCEPTION 'esperava 133 identidades confirmadas, encontrou %', confirmadas; END IF;
  IF duplicadas <> 1 THEN RAISE EXCEPTION 'esperava 1 duplicidade oficial, encontrou %', duplicadas; END IF;
  IF vinculadas <> 113 THEN RAISE EXCEPTION 'esperava 113 vínculos seguros, encontrou %', vinculadas; END IF;
  IF revisoes <> 20 THEN RAISE EXCEPTION 'esperava 20 vínculos em revisão de identidade, encontrou %', revisoes; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.chapas_2026
    WHERE identidade_status='duplicidade_oficial' AND titular_nome_urna='ELIZEU AGUIAR'
      AND vinculo_titular_status = 'duplicidade_oficial'
      AND vice_nome_urna='ISMAR MARQUES' AND sq_coligacao IS NULL
      AND titular_sq_candidato IS NULL AND vice_sq_candidato IS NULL) THEN
    RAISE EXCEPTION 'duplicidade oficial Elizeu/Ismar não preservada em quarentena';
  END IF;
END $$;
