-- Backfill de créditos de foto medido em 15/08/2026.
-- Wikimedia: metadados da API oficial do Commons para as 134 fichas
-- encontradas no banco. Uma ficha sem arquivo recuperável fica nula e
-- consta na evidência versionada. TSE: somente URLs diretas do domínio
-- divulgacandcontas.tse.jus.br, sem inferir origem para outros hosts.

-- @write tabela=candidatos slug=acm-neto campos=foto_credito
-- @write tabela=candidatos slug=adriana-accorsi campos=foto_credito
-- @write tabela=candidatos slug=alan-rick campos=foto_credito
-- @write tabela=candidatos slug=aldo-rebelo campos=foto_credito
-- @write tabela=candidatos slug=alessandra-campelo campos=foto_credito
-- @write tabela=candidatos slug=alexandre-curi campos=foto_credito
-- @write tabela=candidatos slug=alexandre-kalil campos=foto_credito
-- @write tabela=candidatos slug=alvaro-dias-rn campos=foto_credito
-- @write tabela=candidatos slug=alysson-bezerra campos=foto_credito
-- @write tabela=candidatos slug=andre-do-prado campos=foto_credito
-- @write tabela=candidatos slug=andre-marinho campos=foto_credito
-- @write tabela=candidatos slug=ataides-oliveira campos=foto_credito
-- @write tabela=candidatos slug=augusto-cury campos=foto_credito
-- @write tabela=candidatos slug=baba campos=foto_credito
-- @write tabela=candidatos slug=beto-faro campos=foto_credito
-- @write tabela=candidatos slug=cabo-daciolo campos=foto_credito
-- @write tabela=candidatos slug=capitao-wagner campos=foto_credito
-- @write tabela=candidatos slug=carlos-brandao-ma-historico campos=foto_credito
-- @write tabela=candidatos slug=catherine-teles campos=foto_credito
-- @write tabela=candidatos slug=celina-leao campos=foto_credito
-- @write tabela=candidatos slug=cicero-lucena campos=foto_credito
-- @write tabela=candidatos slug=ciro-gomes campos=foto_credito
-- @write tabela=candidatos slug=ciro-gomes-gov-ce campos=foto_credito
-- @write tabela=candidatos slug=clariana-barao campos=foto_credito
-- @write tabela=candidatos slug=clecio-luis campos=foto_credito
-- @write tabela=candidatos slug=cleitinho campos=foto_credito
-- @write tabela=candidatos slug=confucio-moura campos=foto_credito
-- @write tabela=candidatos slug=daniel-vilela campos=foto_credito
-- @write tabela=candidatos slug=daniela-paiva campos=foto_credito
-- @write tabela=candidatos slug=david-almeida campos=foto_credito
-- @write tabela=candidatos slug=decio-lima campos=foto_credito
-- @write tabela=candidatos slug=douglas-ruas campos=foto_credito
-- @write tabela=candidatos slug=dr-daniel campos=foto_credito
-- @write tabela=candidatos slug=dr-furlan campos=foto_credito
-- @write tabela=candidatos slug=dr-luisinho campos=foto_credito
-- @write tabela=candidatos slug=edegar-pretto campos=foto_credito
-- @write tabela=candidatos slug=eduardo-braga campos=foto_credito
-- @write tabela=candidatos slug=eduardo-braide campos=foto_credito
-- @write tabela=candidatos slug=eduardo-girao campos=foto_credito
-- @write tabela=candidatos slug=eduardo-leite campos=foto_credito
-- @write tabela=candidatos slug=eduardo-paes campos=foto_credito
-- @write tabela=candidatos slug=eduardo-riedel campos=foto_credito
-- @write tabela=candidatos slug=efraim-filho campos=foto_credito
-- @write tabela=candidatos slug=elmano-de-freitas campos=foto_credito
-- @write tabela=candidatos slug=expedito-netto campos=foto_credito
-- @write tabela=candidatos slug=fabio-mitidieri campos=foto_credito
-- @write tabela=candidatos slug=fabio-trad campos=foto_credito
-- @write tabela=candidatos slug=flavio-bolsonaro campos=foto_credito
-- @write tabela=candidatos slug=gabriel-souza campos=foto_credito
-- @write tabela=candidatos slug=garotinho campos=foto_credito
-- @write tabela=candidatos slug=geraldo-alckmin campos=foto_credito
-- @write tabela=candidatos slug=gilberto-kassab campos=foto_credito
-- @write tabela=candidatos slug=gilson-machado campos=foto_credito
-- @write tabela=candidatos slug=guilherme-derrite campos=foto_credito
-- @write tabela=candidatos slug=guto-silva campos=foto_credito
-- @write tabela=candidatos slug=haddad-gov-sp campos=foto_credito
-- @write tabela=candidatos slug=hana-ghassan campos=foto_credito
-- @write tabela=candidatos slug=hildon-chaves campos=foto_credito
-- @write tabela=candidatos slug=jeronimo campos=foto_credito
-- @write tabela=candidatos slug=jesus-rodrigues campos=foto_credito
-- @write tabela=candidatos slug=joao-capiberibe campos=foto_credito
-- @write tabela=candidatos slug=joao-henrique-catan campos=foto_credito
-- @write tabela=candidatos slug=joao-roma campos=foto_credito
-- @write tabela=candidatos slug=joaquim-barbosa campos=foto_credito
-- @write tabela=candidatos slug=jorginho-mello campos=foto_credito
-- @write tabela=candidatos slug=jose-carlos-aleluia campos=foto_credito
-- @write tabela=candidatos slug=jose-eliton campos=foto_credito
-- @write tabela=candidatos slug=juliana-brizola campos=foto_credito
-- @write tabela=candidatos slug=lahesio-bonfim campos=foto_credito
-- @write tabela=candidatos slug=laurez-moreira campos=foto_credito
-- @write tabela=candidatos slug=leandro-grass campos=foto_credito
-- @write tabela=candidatos slug=leonardo-avalanche campos=foto_credito
-- @write tabela=candidatos slug=lucas-ribeiro campos=foto_credito
-- @write tabela=candidatos slug=luciana-gurgel campos=foto_credito
-- @write tabela=candidatos slug=lula campos=foto_credito
-- @write tabela=candidatos slug=mailza-assis campos=foto_credito
-- @write tabela=candidatos slug=marcio-franca campos=foto_credito
-- @write tabela=candidatos slug=marconi-perillo campos=foto_credito
-- @write tabela=candidatos slug=marcos-rogerio campos=foto_credito
-- @write tabela=candidatos slug=margarete-coelho campos=foto_credito
-- @write tabela=candidatos slug=mario-couto campos=foto_credito
-- @write tabela=candidatos slug=mateus-simoes campos=foto_credito
-- @write tabela=candidatos slug=naf-nascimento campos=foto_credito
-- @write tabela=candidatos slug=natasha-slhessarenko campos=foto_credito
-- @write tabela=candidatos slug=nikolas-ferreira campos=foto_credito
-- @write tabela=candidatos slug=omar-aziz campos=foto_credito
-- @write tabela=candidatos slug=otaviano-pivetta campos=foto_credito
-- @write tabela=candidatos slug=patrus-ananias campos=foto_credito
-- @write tabela=candidatos slug=paula-belmonte campos=foto_credito
-- @write tabela=candidatos slug=paulo-hartung campos=foto_credito
-- @write tabela=candidatos slug=paulo-serra campos=foto_credito
-- @write tabela=candidatos slug=pazolini campos=foto_credito
-- @write tabela=candidatos slug=pedro-cunha-lima campos=foto_credito
-- @write tabela=candidatos slug=prof-meire-reis campos=foto_credito
-- @write tabela=candidatos slug=rafael-fonteles campos=foto_credito
-- @write tabela=candidatos slug=rafael-greca campos=foto_credito
-- @write tabela=candidatos slug=rafaell-milas campos=foto_credito
-- @write tabela=candidatos slug=raquel-lyra campos=foto_credito
-- @write tabela=candidatos slug=ratinho-junior campos=foto_credito
-- @write tabela=candidatos slug=renan-filho campos=foto_credito
-- @write tabela=candidatos slug=renan-santos campos=foto_credito
-- @write tabela=candidatos slug=requiao-filho campos=foto_credito
-- @write tabela=candidatos slug=ricardo-cappelli campos=foto_credito
-- @write tabela=candidatos slug=ricardo-ferraco campos=foto_credito
-- @write tabela=candidatos slug=ricardo-leite campos=foto_credito
-- @write tabela=candidatos slug=roberto-cidade campos=foto_credito
-- @write tabela=candidatos slug=roberto-claudio campos=foto_credito
-- @write tabela=candidatos slug=robson-raymundo campos=foto_credito
-- @write tabela=candidatos slug=rodrigo-bacellar campos=foto_credito
-- @write tabela=candidatos slug=romeu-zema campos=foto_credito
-- @write tabela=candidatos slug=ronaldo-caiado campos=foto_credito
-- @write tabela=candidatos slug=rui-costa-pimenta campos=foto_credito
-- @write tabela=candidatos slug=sergio-goncalves campos=foto_credito
-- @write tabela=candidatos slug=sergio-moro-gov-pr campos=foto_credito
-- @write tabela=candidatos slug=sergio-vidigal campos=foto_credito
-- @write tabela=candidatos slug=simao-jatene campos=foto_credito
-- @write tabela=candidatos slug=soldado-sampaio campos=foto_credito
-- @write tabela=candidatos slug=tadeu-de-souza campos=foto_credito
-- @write tabela=candidatos slug=tarcisio campos=foto_credito
-- @write tabela=candidatos slug=tarcisio-gov-sp campos=foto_credito
-- @write tabela=candidatos slug=tarcisio-motta campos=foto_credito
-- @write tabela=candidatos slug=teresa-surita campos=foto_credito
-- @write tabela=candidatos slug=tiao-bocalom campos=foto_credito
-- @write tabela=candidatos slug=tony-garcia campos=foto_credito
-- @write tabela=candidatos slug=valmir-de-francisquinho campos=foto_credito
-- @write tabela=candidatos slug=vera-lucia campos=foto_credito
-- @write tabela=candidatos slug=vicentinho-junior campos=foto_credito
-- @write tabela=candidatos slug=vittorio-medioli campos=foto_credito
-- @write tabela=candidatos slug=washington-reis campos=foto_credito
-- @write tabela=candidatos slug=wellington-fagundes campos=foto_credito
-- @write tabela=candidatos slug=wilder-morais campos=foto_credito
-- @write tabela=candidatos slug=wilson-witzel campos=foto_credito
-- @write tabela=candidatos slug=ze-coca campos=foto_credito
-- @write tabela=candidatos slug=alex-pucineli campos=foto_credito
-- @write tabela=candidatos slug=andre-portugues campos=foto_credito
-- @write tabela=candidatos slug=araceli-lemos campos=foto_credito
-- @write tabela=candidatos slug=caiubi-kuhn campos=foto_credito
-- @write tabela=candidatos slug=cintia-dias campos=foto_credito
-- @write tabela=candidatos slug=cleber-rabelo campos=foto_credito
-- @write tabela=candidatos slug=cyro-garcia campos=foto_credito
-- @write tabela=candidatos slug=jenilson-leite campos=foto_credito
-- @write tabela=candidatos slug=juliete-pantoja campos=foto_credito
-- @write tabela=candidatos slug=laudicerio-aguiar campos=foto_credito
-- @write tabela=candidatos slug=lourdes-melo campos=foto_credito
-- @write tabela=candidatos slug=luan-monteiro campos=foto_credito
-- @write tabela=candidatos slug=lucia-santos campos=foto_credito
-- @write tabela=candidatos slug=luiz-carlos-teodoro campos=foto_credito
-- @write tabela=candidatos slug=marcelo-maluf campos=foto_credito
-- @write tabela=candidatos slug=mauricio-coelho campos=foto_credito
-- @write tabela=candidatos slug=mauricio-tonha campos=foto_credito
-- @write tabela=candidatos slug=priscila-voigt campos=foto_credito
-- @write tabela=candidatos slug=ralf-zimmer campos=foto_credito
-- @write tabela=candidatos slug=rejane-oliveira campos=foto_credito
-- @write tabela=candidatos slug=samuel-costa campos=foto_credito
-- @write tabela=candidatos slug=sandro-alex campos=foto_credito
-- @write tabela=candidatos slug=toni-rodrigues campos=foto_credito
-- @write tabela=candidatos slug=tonny-kerley campos=foto_credito
-- @write tabela=candidatos slug=tulio-lopes campos=foto_credito
-- @write tabela=candidatos slug=wanderlei-barbosa campos=foto_credito
-- @write tabela=candidatos slug=william-siri campos=foto_credito
-- @write tabela=candidatos slug=wilson-grassi-junior campos=foto_credito
WITH creditos_fotos_20260815(slug, foto_url, credito) AS (
  VALUES
    ('acm-neto', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/ACM_Neto_%28cropped%29.jpg/960px-ACM_Neto_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Palácio do Planalto from Brasilia, Brasil","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:ACM_Neto_(cropped).jpg"}'::jsonb),
    ('adriana-accorsi', 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Adriana_Accorsi%2C_November_2024_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Elio Rizzo / Câmara dos Deputados","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Adriana_Accorsi,_November_2024_(cropped).jpg"}'::jsonb),
    ('alan-rick', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Alan_Rick.jpg/960px-Alan_Rick.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Alan_Rick.jpg"}'::jsonb),
    ('aldo-rebelo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Ministro_Aldo_Rebelo_2015.jpg/960px-Ministro_Aldo_Rebelo_2015.jpg', '{"origem":"wikimedia_commons","autor":"Foto: Giba/ Ascom/ MCTI","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Ministro_Aldo_Rebelo_2015.jpg"}'::jsonb),
    ('alessandra-campelo', 'https://upload.wikimedia.org/wikipedia/commons/a/ad/2023-05-16_Deputada_Alessandra_Camp%C3%AAlo_%28PSC%29_%28cropped%29.jpg?utm_source=pt.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', '{"origem":"wikimedia_commons","autor":"assembleiaam","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:2023-05-16_Deputada_Alessandra_Camp%C3%AAlo_(PSC)_(cropped).jpg"}'::jsonb),
    ('alexandre-curi', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Sess%C3%A3o_Plen%C3%A1ria_-_foto_D%C3%A1lie_Felberg_-_09-09-19_%28138%29.jpg/960px-Sess%C3%A3o_Plen%C3%A1ria_-_foto_D%C3%A1lie_Felberg_-_09-09-19_%28138%29.jpg', '{"origem":"wikimedia_commons","autor":"Assembleia Legislativa do Paraná","licenca":"Public domain","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Sess%C3%A3o_Plen%C3%A1ria_-_foto_D%C3%A1lie_Felberg_-_09-09-19_(138).jpg"}'::jsonb),
    ('alexandre-kalil', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/2016_KALIL_CANDIDATO_PREFEITO_MG_BELO_HORIZONTE_TSE_%28130000083186%29.jpg', '{"origem":"wikimedia_commons","autor":"Portal de Dados Abertos do Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2016_KALIL_CANDIDATO_PREFEITO_MG_BELO_HORIZONTE_TSE_(130000083186).jpg"}'::jsonb),
    ('alvaro-dias-rn', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/%C3%81lvaro_Costa_Dias_em_maio_de_2020.jpg', '{"origem":"wikimedia_commons","autor":"Marcos Corrêa/PR","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:%C3%81lvaro_Costa_Dias_em_maio_de_2020.jpg"}'::jsonb),
    ('alysson-bezerra', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Allyson_Bezerra.jpg', '{"origem":"wikimedia_commons","autor":"Portal de Dados Abertos do Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Allyson_Bezerra.jpg"}'::jsonb),
    ('andre-do-prado', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Assinatura_de_R%24_150_milh%C3%B5es_em_Conv%C3%AAnios_com_189_Munic%C3%ADpios_Paulistas_via_Painsp.jpg/960px-Assinatura_de_R%24_150_milh%C3%B5es_em_Conv%C3%AAnios_com_189_Munic%C3%ADpios_Paulistas_via_Painsp.jpg', '{"origem":"wikimedia_commons","autor":"Governo do Estado de São Paulo","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Assinatura_de_R$_150_milh%C3%B5es_em_Conv%C3%AAnios_com_189_Munic%C3%ADpios_Paulistas_via_Painsp.jpg"}'::jsonb),
    ('andre-marinho', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Andr%C3%A9_Marinho.tif/lossy-page1-500px-Andr%C3%A9_Marinho.tif.jpg', '{"origem":"wikimedia_commons","autor":"Vitor Garcia","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Andr%C3%A9_Marinho.tif"}'::jsonb),
    ('ataides-oliveira', 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Foto_oficial_de_Ata%C3%ADdes_Oliveira.jpg', '{"origem":"wikimedia_commons","autor":"Senado Federal","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_oficial_de_Ata%C3%ADdes_Oliveira.jpg"}'::jsonb),
    ('augusto-cury', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Augusto_Cury%2C_escritor_%2828339139296%29.jpg/250px-Augusto_Cury%2C_escritor_%2828339139296%29.jpg', '{"origem":"wikimedia_commons","autor":"Lima Andruška from Rio de Janeiro, Brazil","licenca":"CC BY-SA 2.0","licenca_url":"https://creativecommons.org/licenses/by-sa/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Augusto_Cury,_escritor_(28339139296).jpg"}'::jsonb),
    ('baba', 'https://upload.wikimedia.org/wikipedia/commons/e/e3/2021_Cerim%C3%B4nia_de_Assinatura_da_Ordem_de_Servi%C3%A7o_do_Ramal_do_Apodi_-_51268866143_%28cropped%29.jpg?utm_source=pt.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', '{"origem":"wikimedia_commons","autor":"Marcos Corrêa/PR","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2021_Cerim%C3%B4nia_de_Assinatura_da_Ordem_de_Servi%C3%A7o_do_Ramal_do_Apodi_-_51268866143_(cropped).jpg"}'::jsonb),
    ('beto-faro', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Beto_Faro.jpg/960px-Beto_Faro.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Beto_Faro.jpg"}'::jsonb),
    ('cabo-daciolo', 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Cabo_Daciolo_em_maio_de_2017.jpg', '{"origem":"wikimedia_commons","autor":"Alex Ferreira","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Cabo_Daciolo_em_maio_de_2017.jpg"}'::jsonb),
    ('capitao-wagner', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Deputado_Federal_Capit%C3%A3o_Wagner_%28cropped%29.jpg/960px-Deputado_Federal_Capit%C3%A3o_Wagner_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Michel Jesus/ Câmara dos Deputados","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Deputado_Federal_Capit%C3%A3o_Wagner_(cropped).jpg"}'::jsonb),
    ('carlos-brandao-ma-historico', 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Retrato_Oficial_de_Carlos_Brand%C3%A3o_como_governador_do_Maranh%C3%A3o.jpg', '{"origem":"wikimedia_commons","autor":"Governo do Maranhão","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Retrato_Oficial_de_Carlos_Brand%C3%A3o_como_governador_do_Maranh%C3%A3o.jpg"}'::jsonb),
    ('catherine-teles', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/2026_CATHERINE_TELES_CANDIDATA_VICE-GOVERNADORA_CE_TSE_%2860002533730%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', '{"origem":"wikimedia_commons","autor":"Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2026_CATHERINE_TELES_CANDIDATA_VICE-GOVERNADORA_CE_TSE_(60002533730).jpg"}'::jsonb),
    ('celina-leao', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Celina_Leao_Posse_2026_%28cropped%29.jpg/960px-Celina_Leao_Posse_2026_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"George Gianni/Agência Brasília","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Celina_Leao_Posse_2026_(cropped).jpg"}'::jsonb),
    ('cicero-lucena', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/11_12_2024_-_Reuni%C3%A3o_com_Cicero_Lucena%2C_Prefeito_de_Jo%C3%A3o_Pessoa_%2854198867920%29_%28cropped%29.jpg/960px-11_12_2024_-_Reuni%C3%A3o_com_Cicero_Lucena%2C_Prefeito_de_Jo%C3%A3o_Pessoa_%2854198867920%29_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Ministério da Ciência, Tecnologia e Inovação from Brasília - DF, Brasil","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:11_12_2024_-_Reuni%C3%A3o_com_Cicero_Lucena,_Prefeito_de_Jo%C3%A3o_Pessoa_(54198867920)_(cropped).jpg"}'::jsonb),
    ('ciro-gomes', 'https://upload.wikimedia.org/wikipedia/commons/3/34/Presidente_Ciro_Gomes.png', '{"origem":"wikimedia_commons","autor":"Loberos","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Presidente_Ciro_Gomes.png"}'::jsonb),
    ('ciro-gomes-gov-ce', 'https://upload.wikimedia.org/wikipedia/commons/3/34/Presidente_Ciro_Gomes.png', '{"origem":"wikimedia_commons","autor":"Loberos","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Presidente_Ciro_Gomes.png"}'::jsonb),
    ('clariana-barao', 'https://upload.wikimedia.org/wikipedia/commons/4/45/Clariana_Zacarkim_Bar%C3%A3o.jpg', '{"origem":"wikimedia_commons","autor":"LFLN","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Clariana_Zacarkim_Bar%C3%A3o.jpg"}'::jsonb),
    ('clecio-luis', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Foto_oficial_do_governador_do_Estado_do_Amap%C3%A1%2C_Cl%C3%A9cio_Lu%C3%ADs.jpg/960px-Foto_oficial_do_governador_do_Estado_do_Amap%C3%A1%2C_Cl%C3%A9cio_Lu%C3%ADs.jpg', '{"origem":"wikimedia_commons","autor":"Governo do Amapá","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_oficial_do_governador_do_Estado_do_Amap%C3%A1,_Cl%C3%A9cio_Lu%C3%ADs.jpg"}'::jsonb),
    ('cleitinho', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Senadores_da_57%C2%AA_Legislatura_%2852689522963%29.jpg/960px-Senadores_da_57%C2%AA_Legislatura_%2852689522963%29.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado from Brasilia, Brazil","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Senadores_da_57%C2%AA_Legislatura_(52689522963).jpg"}'::jsonb),
    ('confucio-moura', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Senador_Conf%C3%BAcio_Moura.jpg/960px-Senador_Conf%C3%BAcio_Moura.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Senador_Conf%C3%BAcio_Moura.jpg"}'::jsonb),
    ('daniel-vilela', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Daniel_Vilela_em_2024_%28retouched%29.jpg', '{"origem":"wikimedia_commons","autor":"Emerson Júnior GSF","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:Daniel_Vilela_em_2024_(retouched).jpg"}'::jsonb),
    ('daniela-paiva', 'https://upload.wikimedia.org/wikipedia/commons/a/a6/2026_DANIELA_PAIVA_CANDIDATA_VICE-GOVERNADORA_AC_TSE_%2810002533538%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', '{"origem":"wikimedia_commons","autor":"Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2026_DANIELA_PAIVA_CANDIDATA_VICE-GOVERNADORA_AC_TSE_(10002533538).jpg"}'::jsonb),
    ('david-almeida', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/David_Almeida.jpg/960px-David_Almeida.jpg', '{"origem":"wikimedia_commons","autor":"Alcides Neto","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:David_Almeida.jpg"}'::jsonb),
    ('decio-lima', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/D%C3%A9cio_para_wiki.png/960px-D%C3%A9cio_para_wiki.png', '{"origem":"wikimedia_commons","autor":"Tulioborges sc","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:D%C3%A9cio_para_wiki.png"}'::jsonb),
    ('douglas-ruas', 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Entrevista_do_Secretario_de_Cidades_do_RJ%2C_Douglas_Ruas_2_%28cropped%29.png', '{"origem":"wikimedia_commons","autor":"TV ALERJ","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Entrevista_do_Secretario_de_Cidades_do_RJ,_Douglas_Ruas_2_(cropped).png"}'::jsonb),
    ('dr-daniel', 'https://upload.wikimedia.org/wikipedia/commons/0/02/Dr._Daniel_Santos.jpg', '{"origem":"wikimedia_commons","autor":"Perfil oficial do deputado Daniel Santos no Flickr","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Dr._Daniel_Santos.jpg"}'::jsonb),
    ('dr-furlan', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Dr._Furlan_Candidato_a_Prefeito_de_Macap%C3%A1_2024_-_TSE.jpg', '{"origem":"wikimedia_commons","autor":"Portal de Dados Abertos do Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Dr._Furlan_Candidato_a_Prefeito_de_Macap%C3%A1_2024_-_TSE.jpg"}'::jsonb),
    ('dr-luisinho', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/2026_DR.LUISINHO_CANDIDATO_GOVERNADOR_AC_TSE_%2810002533539%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', '{"origem":"wikimedia_commons","autor":"Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2026_DR.LUISINHO_CANDIDATO_GOVERNADOR_AC_TSE_(10002533539).jpg"}'::jsonb),
    ('edegar-pretto', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/CRA_-_Comiss%C3%A3o_de_Agricultura_e_Reforma_Agr%C3%A1ria_%2854442000420%29.jpg/960px-CRA_-_Comiss%C3%A3o_de_Agricultura_e_Reforma_Agr%C3%A1ria_%2854442000420%29.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado from Brasilia, Brazil","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:CRA_-_Comiss%C3%A3o_de_Agricultura_e_Reforma_Agr%C3%A1ria_(54442000420).jpg"}'::jsonb),
    ('eduardo-braga', 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Foto_oficial_de_Eduardo_Braga.jpg', '{"origem":"wikimedia_commons","autor":"Senado Federal","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_oficial_de_Eduardo_Braga.jpg"}'::jsonb),
    ('eduardo-braide', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Eduardo_Braide_%28cropped%29.jpg/960px-Eduardo_Braide_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Cleia Viana/Câmara dos Deputados","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Eduardo_Braide_(cropped).jpg"}'::jsonb),
    ('eduardo-girao', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Senador_Eduardo_Gir%C3%A3o.jpg/960px-Senador_Eduardo_Gir%C3%A3o.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Senador_Eduardo_Gir%C3%A3o.jpg"}'::jsonb),
    ('eduardo-leite', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/09.02.2026_%E2%80%93_Eduardo_Leite_in_February_2026_-_55087496770_%283x4%29.jpg/960px-09.02.2026_%E2%80%93_Eduardo_Leite_in_February_2026_-_55087496770_%283x4%29.jpg', '{"origem":"wikimedia_commons","autor":"Governo RS","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:09.02.2026_%E2%80%93_Eduardo_Leite_in_February_2026_-_55087496770_(3x4).jpg"}'::jsonb),
    ('eduardo-paes', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eduardo_Paes%2C_October_2024.jpg/960px-Eduardo_Paes%2C_October_2024.jpg', '{"origem":"wikimedia_commons","autor":"Lula Oficial","licenca":"CC BY-SA 2.0","licenca_url":"https://creativecommons.org/licenses/by-sa/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Eduardo_Paes,_October_2024.jpg"}'::jsonb),
    ('eduardo-riedel', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/XIV_Reuni%C3%A3o_do_F%C3%B3rum_Nacional_de_Governadores_em_Bras%C3%ADlia_%2852922688344%29.jpg/960px-XIV_Reuni%C3%A3o_do_F%C3%B3rum_Nacional_de_Governadores_em_Bras%C3%ADlia_%2852922688344%29.jpg', '{"origem":"wikimedia_commons","autor":"Agência Brasília from Brasília, Brasil","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:XIV_Reuni%C3%A3o_do_F%C3%B3rum_Nacional_de_Governadores_em_Bras%C3%ADlia_(52922688344).jpg"}'::jsonb),
    ('efraim-filho', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Efraim_Filho_%28PB%29.jpg/960px-Efraim_Filho_%28PB%29.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Efraim_Filho_(PB).jpg"}'::jsonb),
    ('elmano-de-freitas', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Plen%C3%A1rio_do_Congresso_%2854441463325%29.jpg/960px-Plen%C3%A1rio_do_Congresso_%2854441463325%29.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado from Brasilia, Brazil","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Plen%C3%A1rio_do_Congresso_(54441463325).jpg"}'::jsonb),
    ('expedito-netto', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Expedito_Netto_em_fevereiro_de_2015.jpg/960px-Expedito_Netto_em_fevereiro_de_2015.jpg', '{"origem":"wikimedia_commons","autor":"Gustavo Lima","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Expedito_Netto_em_fevereiro_de_2015.jpg"}'::jsonb),
    ('fabio-mitidieri', 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Foto_oficial_do_governador_F%C3%A1bio_Mitidieri.jpg', '{"origem":"wikimedia_commons","autor":"Governo do Sergipe","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_oficial_do_governador_F%C3%A1bio_Mitidieri.jpg"}'::jsonb),
    ('fabio-trad', 'https://upload.wikimedia.org/wikipedia/commons/1/13/F%C3%A1bio_Trad_em_2013_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Gustavo Lima / Câmara dos Deputados","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:F%C3%A1bio_Trad_em_2013_(cropped).jpg"}'::jsonb),
    ('flavio-bolsonaro', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Foto_oficial_do_senador_Fl%C3%A1vio_Bolsonaro_%28v._AgSen%29_%283x4%29.jpg/960px-Foto_oficial_do_senador_Fl%C3%A1vio_Bolsonaro_%28v._AgSen%29_%283x4%29.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_oficial_do_senador_Fl%C3%A1vio_Bolsonaro_(v._AgSen)_(3x4).jpg"}'::jsonb),
    ('gabriel-souza', 'https://upload.wikimedia.org/wikipedia/commons/4/40/Vice-governador_do_Rio_Grande_do_Sul%2C_Gabriel_Souza.jpg', '{"origem":"wikimedia_commons","autor":"Joel Vargas","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Vice-governador_do_Rio_Grande_do_Sul,_Gabriel_Souza.jpg"}'::jsonb),
    ('garotinho', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Deputado_Anthony_Garotinho_entrevistado_em_2011_%28cropped%29.jpg/960px-Deputado_Anthony_Garotinho_entrevistado_em_2011_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Leonardo Prado/Câmara dos Deputados","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Deputado_Anthony_Garotinho_entrevistado_em_2011_(cropped).jpg"}'::jsonb),
    ('geraldo-alckmin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Alckmin_2024.jpg/960px-Alckmin_2024.jpg', '{"origem":"wikimedia_commons","autor":"Cadu Gomes/Vice-Presidência da República","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Alckmin_2024.jpg"}'::jsonb),
    ('gilberto-kassab', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Governo_do_Estado_de_S%C3%A3o_Paulo_-_52600908378.jpg/960px-Governo_do_Estado_de_S%C3%A3o_Paulo_-_52600908378.jpg', '{"origem":"wikimedia_commons","autor":"Governo do Estado de São Paulo","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Governo_do_Estado_de_S%C3%A3o_Paulo_-_52600908378.jpg"}'::jsonb),
    ('gilson-machado', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Gilson_Machado_Neto_%28cropped%29.jpg/960px-Gilson_Machado_Neto_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Isac Nóbrega/PR","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Gilson_Machado_Neto_(cropped).jpg"}'::jsonb),
    ('guilherme-derrite', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Retratos_Oficiais_-_Secret%C3%A1rios_de_Estado_de_S%C3%A3o_Paulo_em_2023_02.jpg/960px-Retratos_Oficiais_-_Secret%C3%A1rios_de_Estado_de_S%C3%A3o_Paulo_em_2023_02.jpg', '{"origem":"wikimedia_commons","autor":"Governo do Estado de São Paulo","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Retratos_Oficiais_-_Secret%C3%A1rios_de_Estado_de_S%C3%A3o_Paulo_em_2023_02.jpg"}'::jsonb),
    ('guto-silva', 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Guto_Silva.jpg', '{"origem":"wikimedia_commons","autor":"Luiz Tagliacollo","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:Guto_Silva.jpg"}'::jsonb),
    ('haddad-gov-sp', 'https://upload.wikimedia.org/wikipedia/commons/5/52/Fernando_Haddad_posse_min._da_Fazenda.jpg', '{"origem":"wikimedia_commons","autor":"Ricardo Stuckert","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Fernando_Haddad_posse_min._da_Fazenda.jpg"}'::jsonb),
    ('hana-ghassan', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/2023-06-30_Medalha_da_Ordem_do_M%C3%A9rito_Dom_Pedro_II_09_%28Hana_Ghassan%29.jpg/960px-2023-06-30_Medalha_da_Ordem_do_M%C3%A9rito_Dom_Pedro_II_09_%28Hana_Ghassan%29.jpg', '{"origem":"wikimedia_commons","autor":"Tribunal de Justiça do Estado do Pará","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:2023-06-30_Medalha_da_Ordem_do_M%C3%A9rito_Dom_Pedro_II_09_(Hana_Ghassan).jpg"}'::jsonb),
    ('hildon-chaves', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Dr_Hildon_%28cortado%29.png', '{"origem":"wikimedia_commons","autor":"Planeta Folha","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Dr_Hildon_(cortado).png"}'::jsonb),
    ('jeronimo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/18_01_2023_-_Visita_de_Cortesia_Jer%C3%B4nimo_Rodrigues_%28Governador_do_Estado_da_Bahia-BA%29_%2852635213362%29_%28cropped%29.jpg/960px-18_01_2023_-_Visita_de_Cortesia_Jer%C3%B4nimo_Rodrigues_%28Governador_do_Estado_da_Bahia-BA%29_%2852635213362%29_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Ministério da Ciência, Tecnologia e Inovação from Brasília - DF, Brasil","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:18_01_2023_-_Visita_de_Cortesia_Jer%C3%B4nimo_Rodrigues_(Governador_do_Estado_da_Bahia-BA)_(52635213362)_(cropped).jpg"}'::jsonb),
    ('jesus-rodrigues', 'https://upload.wikimedia.org/wikipedia/commons/2/23/DeputadoJesusRodriguesPIAUI.JPG', '{"origem":"wikimedia_commons","autor":"Almanaque Lusofonista","licenca":"Public domain","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:DeputadoJesusRodriguesPIAUI.JPG"}'::jsonb),
    ('joao-capiberibe', 'https://upload.wikimedia.org/wikipedia/commons/0/07/Foto_oficial_de_Jo%C3%A3o_Capiberibe.jpg', '{"origem":"wikimedia_commons","autor":"Senado Federal","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_oficial_de_Jo%C3%A3o_Capiberibe.jpg"}'::jsonb),
    ('joao-henrique-catan', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Deputado_Jo%C3%A3o_Henrique_%28cropped%29.jpg/960px-Deputado_Jo%C3%A3o_Henrique_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Caiqueolima23","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Deputado_Jo%C3%A3o_Henrique_(cropped).jpg"}'::jsonb),
    ('joao-roma', 'https://upload.wikimedia.org/wikipedia/commons/6/64/Jo%C3%A3o_Roma.jpg', '{"origem":"wikimedia_commons","autor":"João Roma","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:Jo%C3%A3o_Roma.jpg"}'::jsonb),
    ('joaquim-barbosa', 'https://commons.wikimedia.org/wiki/Special:FilePath/Joaquim_Barbosa.jpg', '{"origem":"wikimedia_commons","autor":"Supremo Tribunal Federal","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Joaquim_Barbosa.jpg"}'::jsonb),
    ('jorginho-mello', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Governador_Jorginho_Mello_-_Foto_Eduardo_Valente_-_GOVSC-7.jpg/960px-Governador_Jorginho_Mello_-_Foto_Eduardo_Valente_-_GOVSC-7.jpg', '{"origem":"wikimedia_commons","autor":"Eduardo Valente","licenca":"Public domain","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Governador_Jorginho_Mello_-_Foto_Eduardo_Valente_-_GOVSC-7.jpg"}'::jsonb),
    ('jose-carlos-aleluia', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Jos%C3%A9_Carlos_Aleluia_20100612.jpg/960px-Jos%C3%A9_Carlos_Aleluia_20100612.jpg', '{"origem":"wikimedia_commons","autor":"Fabio Rodrigues Pozzebom/ABr","licenca":"CC BY 3.0 br","licenca_url":"https://creativecommons.org/licenses/by/3.0/br/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:Jos%C3%A9_Carlos_Aleluia_20100612.jpg"}'::jsonb),
    ('jose-eliton', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Retrato_de_Jos%C3%A9_Eliton_como_governador_de_Goi%C3%A1s.png/960px-Retrato_de_Jos%C3%A9_Eliton_como_governador_de_Goi%C3%A1s.png', '{"origem":"wikimedia_commons","autor":"Record TV Goiás","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Retrato_de_Jos%C3%A9_Eliton_como_governador_de_Goi%C3%A1s.png"}'::jsonb),
    ('juliana-brizola', 'https://upload.wikimedia.org/wikipedia/commons/e/e7/JulianaFotoWiki.jpg', '{"origem":"wikimedia_commons","autor":"Diegofsilveira","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:JulianaFotoWiki.jpg"}'::jsonb),
    ('lahesio-bonfim', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Lahesio-bonfim.jpg', '{"origem":"wikimedia_commons","autor":"Lahesio Bonfim","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:Lahesio-bonfim.jpg"}'::jsonb),
    ('laurez-moreira', 'https://upload.wikimedia.org/wikipedia/commons/3/32/FTO270001652199_div.jpg', '{"origem":"wikimedia_commons","autor":"Portal de Dados Abertos do Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:FTO270001652199_div.jpg"}'::jsonb),
    ('leandro-grass', 'https://upload.wikimedia.org/wikipedia/commons/1/12/Leandro_Grass_em_dezembro_de_2018.png', '{"origem":"wikimedia_commons","autor":"Café com Política","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Leandro_Grass_em_dezembro_de_2018.png"}'::jsonb),
    ('leonardo-avalanche', 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Leonardo_Avalanche.jpg', '{"origem":"wikimedia_commons","autor":"LFLN","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Leonardo_Avalanche.jpg"}'::jsonb),
    ('lucas-ribeiro', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Lucas_Ribeiro_-_Vice-governador_da_Para%C3%ADba_2025.jpg/960px-Lucas_Ribeiro_-_Vice-governador_da_Para%C3%ADba_2025.jpg', '{"origem":"wikimedia_commons","autor":"Ascomlr","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:Lucas_Ribeiro_-_Vice-governador_da_Para%C3%ADba_2025.jpg"}'::jsonb),
    ('luciana-gurgel', 'https://upload.wikimedia.org/wikipedia/commons/8/82/2026_LUCIANA_GURGEL_CANDIDATA_VICE-GOVERNADORA_AP_TSE_%2830002530015%29.jpg?utm_source=pt.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', '{"origem":"wikimedia_commons","autor":"Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2026_LUCIANA_GURGEL_CANDIDATA_VICE-GOVERNADORA_AP_TSE_(30002530015).jpg"}'::jsonb),
    ('lula', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Foto_oficial_de_Luiz_In%C3%A1cio_Lula_da_Silva_%28ombros%29_denoise.jpg/960px-Foto_oficial_de_Luiz_In%C3%A1cio_Lula_da_Silva_%28ombros%29_denoise.jpg', '{"origem":"wikimedia_commons","autor":"Ricardo Stuckert/PR","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_oficial_de_Luiz_In%C3%A1cio_Lula_da_Silva_(ombros)_denoise.jpg"}'::jsonb),
    ('mailza-assis', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Foto_oficial_de_Vice-governadora_Mailza_Assis_em_ambiente_institucional.jpg/960px-Foto_oficial_de_Vice-governadora_Mailza_Assis_em_ambiente_institucional.jpg', '{"origem":"wikimedia_commons","autor":"Geisy Araújo","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_oficial_de_Vice-governadora_Mailza_Assis_em_ambiente_institucional.jpg"}'::jsonb),
    ('marcio-franca', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Ordem_do_Ipiranga_-_M%C3%A1rcio_Fran%C3%A7a.jpg/960px-Ordem_do_Ipiranga_-_M%C3%A1rcio_Fran%C3%A7a.jpg', '{"origem":"wikimedia_commons","autor":"Governo do Estado de São Paulo","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Ordem_do_Ipiranga_-_M%C3%A1rcio_Fran%C3%A7a.jpg"}'::jsonb),
    ('marconi-perillo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Foto_Oficial_%285958772460%29.jpg/960px-Foto_Oficial_%285958772460%29.jpg', '{"origem":"wikimedia_commons","autor":"Marconi Perillo","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_Oficial_(5958772460).jpg"}'::jsonb),
    ('marcos-rogerio', 'https://upload.wikimedia.org/wikipedia/commons/9/93/Marcos_Rog%C3%A9rio_%28Rond%C3%B4nia%29.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Marcos_Rog%C3%A9rio_(Rond%C3%B4nia).jpg"}'::jsonb),
    ('margarete-coelho', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Margarete_Coelho_em_abril_de_2019_%28recorte%29.jpg/960px-Margarete_Coelho_em_abril_de_2019_%28recorte%29.jpg', '{"origem":"wikimedia_commons","autor":"Michel Jesus/Câmara dos Deputados","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Margarete_Coelho_em_abril_de_2019_(recorte).jpg"}'::jsonb),
    ('mario-couto', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Mario_couto_senador.JPG', '{"origem":"wikimedia_commons","autor":"Waldemir Barreto/Agência Senado","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Mario_couto_senador.JPG"}'::jsonb),
    ('mateus-simoes', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Mateus_Sim%C3%B5es%2C_April_2024_%28cropped%29.jpg/960px-Mateus_Sim%C3%B5es%2C_April_2024_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Jonas Pereira/Agência Senado","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Mateus_Sim%C3%B5es,_April_2024_(cropped).jpg"}'::jsonb),
    ('naf-nascimento', 'https://upload.wikimedia.org/wikipedia/commons/1/13/2026_NAF_NASCIMENTO_CANDIDATA_VICE-GOVERNADORA_RS_TSE_%28210002533354%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', '{"origem":"wikimedia_commons","autor":"Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2026_NAF_NASCIMENTO_CANDIDATA_VICE-GOVERNADORA_RS_TSE_(210002533354).jpg"}'::jsonb),
    ('natasha-slhessarenko', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Dr.natasha_Slhessarenko.jpg/960px-Dr.natasha_Slhessarenko.jpg', '{"origem":"wikimedia_commons","autor":"Odanilobarreto","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Dr.natasha_Slhessarenko.jpg"}'::jsonb),
    ('nikolas-ferreira', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Nikolas_Ferreira_in_2023_%28cropped%29.jpg/960px-Nikolas_Ferreira_in_2023_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Pablo Valadares / Câmara dos Deputados","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Nikolas_Ferreira_in_2023_(cropped).jpg"}'::jsonb),
    ('omar-aziz', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Senadores_da_56%C2%AA_Legislatura_-_Omar_Aziz_%2846293125674%29.jpg/960px-Senadores_da_56%C2%AA_Legislatura_-_Omar_Aziz_%2846293125674%29.jpg', '{"origem":"wikimedia_commons","autor":"Senado Federal","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Senadores_da_56%C2%AA_Legislatura_-_Omar_Aziz_(46293125674).jpg"}'::jsonb),
    ('otaviano-pivetta', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Otaviano_Pivetta_out_2022.jpg', '{"origem":"wikimedia_commons","autor":"Banco de Dados Abertos do Tribunal Superior Eleitoral (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Otaviano_Pivetta_out_2022.jpg"}'::jsonb),
    ('patrus-ananias', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Deputado-patrus-ananias_-Foto_-Lula-Marques-_Ag%C3%AAncia-PT-1_%2833037635854%29.jpg/960px-Deputado-patrus-ananias_-Foto_-Lula-Marques-_Ag%C3%AAncia-PT-1_%2833037635854%29.jpg', '{"origem":"wikimedia_commons","autor":"Partido dos Trabalhadores","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Deputado-patrus-ananias_-Foto_-Lula-Marques-_Ag%C3%AAncia-PT-1_(33037635854).jpg"}'::jsonb),
    ('paula-belmonte', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Paula_Belmonte_em_outubro_de_2024.jpg/960px-Paula_Belmonte_em_outubro_de_2024.jpg', '{"origem":"wikimedia_commons","autor":"Alemotta79","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:Paula_Belmonte_em_outubro_de_2024.jpg"}'::jsonb),
    ('paulo-hartung', 'https://upload.wikimedia.org/wikipedia/commons/8/82/Paulo_Hartung_as_Governor_of_Esp%C3%ADrito_Santo%2C_January_2015_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Reinaldo Carvalho/ALES","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Paulo_Hartung_as_Governor_of_Esp%C3%ADrito_Santo,_January_2015_(cropped).jpg"}'::jsonb),
    ('paulo-serra', 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Paulo_Serra_3x4.jpeg', '{"origem":"wikimedia_commons","autor":"Governo do Estado de São Paulo","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Paulo_Serra_3x4.jpeg"}'::jsonb),
    ('pazolini', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Lorenzo_Pazolini_%28sess%C3%A3o%29.jpg/960px-Lorenzo_Pazolini_%28sess%C3%A3o%29.jpg', '{"origem":"wikimedia_commons","autor":"Assembleia Legislativa do Espírito Santo","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Lorenzo_Pazolini_(sess%C3%A3o).jpg"}'::jsonb),
    ('pedro-cunha-lima', 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Pedro_Cunha_Lima_em_novembro_de_2015.jpg', '{"origem":"wikimedia_commons","autor":"Alex Ferreira","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Pedro_Cunha_Lima_em_novembro_de_2015.jpg"}'::jsonb),
    ('prof-meire-reis', 'https://upload.wikimedia.org/wikipedia/commons/9/9f/2026_PROF%C2%AA_MEIRE_REIS_CANDIDATA_VICE-GOVERNADORA_BA_TSE_%2850002532270%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', '{"origem":"wikimedia_commons","autor":"Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2026_PROF%C2%AA_MEIRE_REIS_CANDIDATA_VICE-GOVERNADORA_BA_TSE_(50002532270).jpg"}'::jsonb),
    ('rafael-fonteles', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Rafael_Fonteles_%28Foto_Oficial%29.jpg', '{"origem":"wikimedia_commons","autor":"Unknown author Unknown author","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:Rafael_Fonteles_(Foto_Oficial).jpg"}'::jsonb),
    ('rafael-greca', 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Rafael_Greca_toma_posse_em_seu_Terceiro_Mandato_de_Prefeito_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Rodrigo Fonseca/CMC","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Rafael_Greca_toma_posse_em_seu_Terceiro_Mandato_de_Prefeito_(cropped).jpg"}'::jsonb),
    ('rafaell-milas', 'https://upload.wikimedia.org/wikipedia/commons/3/33/Rafaell_Milas.png', '{"origem":"wikimedia_commons","autor":"Gemini","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:Rafaell_Milas.png"}'::jsonb),
    ('raquel-lyra', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/RL45_14-09.jpg/960px-RL45_14-09.jpg', '{"origem":"wikimedia_commons","autor":"Américo Nunes","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:RL45_14-09.jpg"}'::jsonb),
    ('ratinho-junior', 'https://upload.wikimedia.org/wikipedia/commons/3/31/Ratinho_J%C3%BAnior_as_governor_of_Paran%C3%A1%2C_January_2023_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Assembleia Legislativa do Paraná","licenca":"Public domain","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Ratinho_J%C3%BAnior_as_governor_of_Paran%C3%A1,_January_2023_(cropped).jpg"}'::jsonb),
    ('renan-filho', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Senadores_da_57%C2%AA_Legislatura_%2852689452405%29.jpg/960px-Senadores_da_57%C2%AA_Legislatura_%2852689452405%29.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado from Brasilia, Brazil","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Senadores_da_57%C2%AA_Legislatura_(52689452405).jpg"}'::jsonb),
    ('renan-santos', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/2026-01-11_Renan_Santos_%2855036684938%29_%283x4%29.jpg/960px-2026-01-11_Renan_Santos_%2855036684938%29_%283x4%29.jpg', '{"origem":"wikimedia_commons","autor":"Romerito Pontes from São Carlos","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2026-01-11_Renan_Santos_(55036684938)_(3x4).jpg"}'::jsonb),
    ('requiao-filho', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/2024-01-22_Janeiro_Branco%2C_Requi%C3%A3o_Filho_%28PT%29_05_%28cropped%29.jpg/960px-2024-01-22_Janeiro_Branco%2C_Requi%C3%A3o_Filho_%28PT%29_05_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Assembleia Legislativa do Paraná (ALEP)","licenca":"CC0","licenca_url":"http://creativecommons.org/publicdomain/zero/1.0/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:2024-01-22_Janeiro_Branco,_Requi%C3%A3o_Filho_(PT)_05_(cropped).jpg"}'::jsonb),
    ('ricardo-cappelli', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Ricardo_Cappelli.img20230116110526822_%28cropped%29.jpg/960px-Ricardo_Cappelli.img20230116110526822_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Bruno Spada/Câmara dos Deputados","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Ricardo_Cappelli.img20230116110526822_(cropped).jpg"}'::jsonb),
    ('ricardo-ferraco', 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Foto_oficial_de_Ricardo_Ferra%C3%A7o.jpg', '{"origem":"wikimedia_commons","autor":"Senado Federal","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_oficial_de_Ricardo_Ferra%C3%A7o.jpg"}'::jsonb),
    ('ricardo-leite', 'https://upload.wikimedia.org/wikipedia/commons/8/8d/2026_RICARDO_LEITE_CANDIDATO_VICE-GOVERNADOR_AC_TSE_%2810002532493%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', '{"origem":"wikimedia_commons","autor":"Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2026_RICARDO_LEITE_CANDIDATO_VICE-GOVERNADOR_AC_TSE_(10002532493).jpg"}'::jsonb),
    ('roberto-cidade', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Presidente_da_ALEAM.jpg/960px-Presidente_da_ALEAM.jpg', '{"origem":"wikimedia_commons","autor":"Ana Beatriz Melo da Silva","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Presidente_da_ALEAM.jpg"}'::jsonb),
    ('roberto-claudio', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Roberto_Cl%C3%A1udio_em_2018.jpg/960px-Roberto_Cl%C3%A1udio_em_2018.jpg', '{"origem":"wikimedia_commons","autor":"Senado Federal","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Roberto_Cl%C3%A1udio_em_2018.jpg"}'::jsonb),
    ('robson-raymundo', 'https://upload.wikimedia.org/wikipedia/commons/2/2a/2026_PROFESSOR_ROBSON_CANDIDATO_GOVERNADOR_TSE_DF_%2870002535930%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', '{"origem":"wikimedia_commons","autor":"Tribunal Superior Eleitoral","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2026_PROFESSOR_ROBSON_CANDIDATO_GOVERNADOR_TSE_DF_(70002535930).jpg"}'::jsonb),
    ('rodrigo-bacellar', 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Rodrigo_Bacellar_-_Foto_de_Urna_2022.jpg', '{"origem":"wikimedia_commons","autor":"TSE","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Rodrigo_Bacellar_-_Foto_de_Urna_2022.jpg"}'::jsonb),
    ('romeu-zema', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Romeu_Zema%2C_December_2024_%28cropped%29.jpg/960px-Romeu_Zema%2C_December_2024_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Andressa Anholete/Agência Senado","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Romeu_Zema,_December_2024_(cropped).jpg"}'::jsonb),
    ('ronaldo-caiado', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Foto_oficial_do_governador_de_Goi%C3%A1s%2C_Ronaldo_Caiado_em_2023_%28ombros%29.jpg/960px-Foto_oficial_do_governador_de_Goi%C3%A1s%2C_Ronaldo_Caiado_em_2023_%28ombros%29.jpg', '{"origem":"wikimedia_commons","autor":"Bianca Kida","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Foto_oficial_do_governador_de_Goi%C3%A1s,_Ronaldo_Caiado_em_2023_(ombros).jpg"}'::jsonb),
    ('rui-costa-pimenta', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Rui_Costa_Pimenta_Close.jpg/960px-Rui_Costa_Pimenta_Close.jpg', '{"origem":"wikimedia_commons","autor":"Calloshccp","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Rui_Costa_Pimenta_Close.jpg"}'::jsonb),
    ('sergio-goncalves', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/FRO220001609510_div.jpg', '{"origem":"wikimedia_commons","autor":"Portal de Dados Abertos do Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:FRO220001609510_div.jpg"}'::jsonb),
    ('sergio-moro-gov-pr', 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Senador_da_Rep%C3%BAblica_S%C3%A9rgio_Moro.jpg', '{"origem":"wikimedia_commons","autor":"Senado Federal","licenca":"Public domain","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Senador_da_Rep%C3%BAblica_S%C3%A9rgio_Moro.jpg"}'::jsonb),
    ('sergio-vidigal', 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Sergio_Vidigal_Serra_Deputado_Prefeito.jpg', '{"origem":"wikimedia_commons","autor":"Leocarraretto","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Sergio_Vidigal_Serra_Deputado_Prefeito.jpg"}'::jsonb),
    ('simao-jatene', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Sim%C3%A3o_Jatene%2C_December_2016_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Tribunal de Justica do Estado do Pará","licenca":"Public domain","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Sim%C3%A3o_Jatene,_December_2016_(cropped).jpg"}'::jsonb),
    ('soldado-sampaio', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Soldado_Sampaio.jpg/960px-Soldado_Sampaio.jpg', '{"origem":"wikimedia_commons","autor":"Soldado Sampaio","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Soldado_Sampaio.jpg"}'::jsonb),
    ('tadeu-de-souza', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/TV_Norte_Amazonas_entrevistando_Tadeu_de_Souza_%28cropped%29.jpg/250px-TV_Norte_Amazonas_entrevistando_Tadeu_de_Souza_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"TV Norte Amazonas","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:TV_Norte_Amazonas_entrevistando_Tadeu_de_Souza_(cropped).jpg"}'::jsonb),
    ('tarcisio', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Governador_do_Estado_de_S%C3%A3o_Paulo%2C_Tarc%C3%ADsio_de_Freitas_-_Foto_Oficial_%28cropped%29.jpg/960px-Governador_do_Estado_de_S%C3%A3o_Paulo%2C_Tarc%C3%ADsio_de_Freitas_-_Foto_Oficial_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Ciete Silvério/Governo do Estado de SP","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Governador_do_Estado_de_S%C3%A3o_Paulo,_Tarc%C3%ADsio_de_Freitas_-_Foto_Oficial_(cropped).jpg"}'::jsonb),
    ('tarcisio-gov-sp', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Governador_do_Estado_de_S%C3%A3o_Paulo%2C_Tarc%C3%ADsio_de_Freitas_-_Foto_Oficial_%28cropped%29.jpg/960px-Governador_do_Estado_de_S%C3%A3o_Paulo%2C_Tarc%C3%ADsio_de_Freitas_-_Foto_Oficial_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Ciete Silvério/Governo do Estado de SP","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Governador_do_Estado_de_S%C3%A3o_Paulo,_Tarc%C3%ADsio_de_Freitas_-_Foto_Oficial_(cropped).jpg"}'::jsonb),
    ('tarcisio-motta', 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Discuss%C3%A3o_e_vota%C3%A7%C3%A3o_de_propostas._Dep._Tarc%C3%ADsio_Motta_%28PSOL_-_RJ%29_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Zeca Ribeiro/Câmara dos Deputados","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Discuss%C3%A3o_e_vota%C3%A7%C3%A3o_de_propostas._Dep._Tarc%C3%ADsio_Motta_(PSOL_-_RJ)_(cropped).jpg"}'::jsonb),
    ('teresa-surita', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Teresa_Surita_em_fevereiro_de_2022.jpg/960px-Teresa_Surita_em_fevereiro_de_2022.jpg', '{"origem":"wikimedia_commons","autor":"Guimarães Claudia","licenca":"CC BY-SA 4.0","licenca_url":"https://creativecommons.org/licenses/by-sa/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Teresa_Surita_em_fevereiro_de_2022.jpg"}'::jsonb),
    ('tiao-bocalom', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Ti%C3%A3o_Bocalom_2022.jpg/960px-Ti%C3%A3o_Bocalom_2022.jpg', '{"origem":"wikimedia_commons","autor":"Palácio do Planalto","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Ti%C3%A3o_Bocalom_2022.jpg"}'::jsonb),
    ('tony-garcia', 'https://upload.wikimedia.org/wikipedia/commons/1/10/Tony_Garcia_propaganda_de_1990_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Campanha de Tony Garcia","licenca":"Public domain","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Tony_Garcia_propaganda_de_1990_(cropped).jpg"}'::jsonb),
    ('valmir-de-francisquinho', 'https://upload.wikimedia.org/wikipedia/commons/6/66/2024_VALMIR_DE_FRANCISQUINHO_CANDIDATO_PREFEITO_SE_ITABAIANA_TSE_%28260001935426%29.jpg', '{"origem":"wikimedia_commons","autor":"Portal de Dados Abertos do Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2024_VALMIR_DE_FRANCISQUINHO_CANDIDATO_PREFEITO_SE_ITABAIANA_TSE_(260001935426).jpg"}'::jsonb),
    ('vera-lucia', 'https://upload.wikimedia.org/wikipedia/commons/f/fc/-2022-08-20-_Vera-e-Raquel_07_%2852305375940%29_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"Romerito Pontes from São Carlos","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:-2022-08-20-_Vera-e-Raquel_07_(52305375940)_(cropped).jpg"}'::jsonb),
    ('vicentinho-junior', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Vicentinho_J%C3%BAnior_em_setembro_de_2015.jpg/960px-Vicentinho_J%C3%BAnior_em_setembro_de_2015.jpg', '{"origem":"wikimedia_commons","autor":"Gustavo Lima","licenca":"CC BY 3.0","licenca_url":"https://creativecommons.org/licenses/by/3.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Vicentinho_J%C3%BAnior_em_setembro_de_2015.jpg"}'::jsonb),
    ('vittorio-medioli', 'https://upload.wikimedia.org/wikipedia/commons/4/48/2016_VITTORIO_MEDIOLI_CANDIDATO_PREFEITO_MG_BETIM_TSE_%28130000080259%29.jpg', '{"origem":"wikimedia_commons","autor":"Portal de Dados Abertos do Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:2016_VITTORIO_MEDIOLI_CANDIDATO_PREFEITO_MG_BETIM_TSE_(130000080259).jpg"}'::jsonb),
    ('washington-reis', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Conven%C3%A7%C3%A3o_MDB_Rio_de_Janeiro_15_02_2024_-_Washington_Reis.jpg/960px-Conven%C3%A7%C3%A3o_MDB_Rio_de_Janeiro_15_02_2024_-_Washington_Reis.jpg', '{"origem":"wikimedia_commons","autor":"MDB Nacional","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Conven%C3%A7%C3%A3o_MDB_Rio_de_Janeiro_15_02_2024_-_Washington_Reis.jpg"}'::jsonb),
    ('wellington-fagundes', 'https://upload.wikimedia.org/wikipedia/commons/5/56/Senador_Wellington_Fagundes.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado","licenca":"Attribution","licenca_url":null,"fonte_url":"https://commons.wikimedia.org/wiki/File:Senador_Wellington_Fagundes.jpg"}'::jsonb),
    ('wilder-morais', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Senadores_da_57%C2%AA_Legislatura_%2852689032731%29.jpg/960px-Senadores_da_57%C2%AA_Legislatura_%2852689032731%29.jpg', '{"origem":"wikimedia_commons","autor":"Agência Senado from Brasilia, Brazil","licenca":"CC BY 2.0","licenca_url":"https://creativecommons.org/licenses/by/2.0","fonte_url":"https://commons.wikimedia.org/wiki/File:Senadores_da_57%C2%AA_Legislatura_(52689032731).jpg"}'::jsonb),
    ('wilson-witzel', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Wilson_Witzel_com_faixa_de_Governador_2_%28cropped%29.jpg/250px-Wilson_Witzel_com_faixa_de_Governador_2_%28cropped%29.jpg', '{"origem":"wikimedia_commons","autor":"André Gomes de Melo","licenca":"CC BY 2.0 br","licenca_url":"https://creativecommons.org/licenses/by/2.0/br/deed.en","fonte_url":"https://commons.wikimedia.org/wiki/File:Wilson_Witzel_com_faixa_de_Governador_2_(cropped).jpg"}'::jsonb),
    ('ze-coca', 'https://upload.wikimedia.org/wikipedia/commons/3/30/FBA50000605234_div_Ze_Coca.jpg?utm_source=pt.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', '{"origem":"wikimedia_commons","autor":"Portal de Dados Abertos do Tribunal Superior Eleitoral do Brasil (TSE)","licenca":"CC BY 4.0","licenca_url":"https://creativecommons.org/licenses/by/4.0","fonte_url":"https://commons.wikimedia.org/wiki/File:FBA50000605234_div_Ze_Coca.jpg"}'::jsonb),
    ('alex-pucineli', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/47/110000010149/90670', '{"origem":"tse"}'::jsonb),
    ('andre-portugues', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2030402020/190000874427/58572', '{"origem":"tse"}'::jsonb),
    ('araceli-lemos', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2022802018/140000604416/PA', '{"origem":"tse"}'::jsonb),
    ('caiubi-kuhn', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/110002246420/90670', '{"origem":"tse"}'::jsonb),
    ('cintia-dias', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/90002192685/93734', '{"origem":"tse"}'::jsonb),
    ('cleber-rabelo', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2040602022/140001650519/PA', '{"origem":"tse"}'::jsonb),
    ('cyro-garcia', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/190001951101/60011', '{"origem":"tse"}'::jsonb),
    ('jenilson-leite', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/10002171655/01392', '{"origem":"tse"}'::jsonb),
    ('juliete-pantoja', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/190002135108/60011', '{"origem":"tse"}'::jsonb),
    ('laudicerio-aguiar', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/110002118851/90670', '{"origem":"tse"}'::jsonb),
    ('lourdes-melo', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/180002337603/12190', '{"origem":"tse"}'::jsonb),
    ('luan-monteiro', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/190002346684/60011', '{"origem":"tse"}'::jsonb),
    ('lucia-santos', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2030402020/180001057808/12190', '{"origem":"tse"}'::jsonb),
    ('luiz-carlos-teodoro', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2030402020/220000977509/00019', '{"origem":"tse"}'::jsonb),
    ('marcelo-maluf', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/680/110000000004/MT', '{"origem":"tse"}'::jsonb),
    ('mauricio-coelho', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2030402020/110000951550/90700', '{"origem":"tse"}'::jsonb),
    ('mauricio-tonha', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2030402020/110001033922/91910', '{"origem":"tse"}'::jsonb),
    ('priscila-voigt', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/210001945324/88013', '{"origem":"tse"}'::jsonb),
    ('ralf-zimmer', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2040602022/240001611148/SC', '{"origem":"tse"}'::jsonb),
    ('rejane-oliveira', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2040602022/210001605930/RS', '{"origem":"tse"}'::jsonb),
    ('samuel-costa', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/220002330987/00035', '{"origem":"tse"}'::jsonb),
    ('sandro-alex', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2040602022/160001622302/PR', '{"origem":"tse"}'::jsonb),
    ('toni-rodrigues', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2/180000004911/10073', '{"origem":"tse"}'::jsonb),
    ('tonny-kerley', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/180001885637/12190', '{"origem":"tse"}'::jsonb),
    ('tulio-lopes', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2022802018/130000606639/MG', '{"origem":"tse"}'::jsonb),
    ('wanderlei-barbosa', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2040602022/270001652198/TO', '{"origem":"tse"}'::jsonb),
    ('william-siri', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/2045202024/190002142537/60011', '{"origem":"tse"}'::jsonb),
    ('wilson-grassi-junior', 'https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002548139/BR', '{"origem":"tse"}'::jsonb)
)
-- @write tabela=candidatos ref=creditos_fotos_20260815 campos=foto_credito
UPDATE public.candidatos AS c
SET foto_credito = creditos_fotos_20260815.credito
FROM creditos_fotos_20260815
WHERE c.slug = creditos_fotos_20260815.slug
  AND c.foto_url = creditos_fotos_20260815.foto_url
  AND 'creditos_fotos_20260815'::text IS NOT NULL
  AND c.foto_credito IS DISTINCT FROM creditos_fotos_20260815.credito;

-- paulo-martins-gov-pr permanece nulo: a API respondeu arquivo ausente
-- para File:Paulo Martins.jpeg, sem autor ou licença recuperáveis.
